// tmp_g8nabwz_text.c
// Generated by decompiling tmp_g8nabwz
// using Reko decompiler version 0.11.6.0.

#include "tmp_g8nabwz.h"

// 0000000000002300: void fn0000000000002300(Register (ptr64 (ptr64 charconst )) rsi, Register int32const  edi, Register (ptr32 Eq_4) fs, Register word128 xmm0)
void fn0000000000002300(const char ** rsi, const int32 edi, struct Eq_4 * fs, word128 xmm0)
{
	ptr64 fp;
	word64 rax_32 = fs->qw0028;
	CommandLine::CommandLine();
	const char ** rbx_48 = (const char **) _config_GOT;
	word32 eax_74 = (word32) _Z16ParseCommandLineR11CommandLine7APT_CMDPKP13ConfigurationPP9pkgSystemiPPKcPFbS0_EPFSt6vectorI19aptDispatchWithHelpSaISF_EEvE(0x00, 0x00, _system_GOT, (uint64) edi, edi, rbx_48, fp - 0x0078, 0x00, fp - 88, rsi, &g_t25C0, &g_t2630);
	(*rbx_48, (const int32 &) &g_t33AC);
	if (eax_74 == 0x02)
	{
		(*rbx_48, (const int32) &g_t33B2);
		(*rbx_48, (const int32 &) &g_t33AC);
	}
	InitSignals();
	_Z10InitOutputPSt15basic_streambufIcSt11char_traitsIcEE(*((const char *) _ZSt4cout_GOT + 0x00F0));
	CheckIfCalledByScript(edi, rsi);
	CheckIfSimulateMode((CommandLine &) (fp - 88));
	_Z19DispatchCommandLineR11CommandLineRKSt6vectorINS_8DispatchESaIS2_EE(fp - 88, fp - 0x0078);
	int64 qwLoc78;
	if (qwLoc78 != 0x00)
	{
		word64 qwLoc68;
		uint64 rdx_116;
		((real64) xmm0, qwLoc78, qwLoc68 - qwLoc78, rdx_116);
	}
	CommandLine::~CommandLine();
	if (rax_32 == fs->qw0028)
		return;
	__stack_chk_fail();
}

// 00000000000024D0: void fn00000000000024D0(Register (ptr64 Eq_116) rdx, Stack word32 dwArg00, Stack (ptr64 charconst ) ptrArg08)
void fn00000000000024D0(void (* rdx)(), word32 dwArg00, const char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t2300, (const int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

<unknown> g_t25C0 = // 00000000000025C0;
<unknown> g_t2630 = // 0000000000002630;
// tmp_g8nabwz_data.c
// Generated by decompiling tmp_g8nabwz
// using Reko decompiler version 0.11.6.0.

#include "tmp_g8nabwz.h"

<anonymous> * __gcc_personality_v0_GOT = null; // 0000000000005010
// tmp_g8nabwz_rodata.c
// Generated by decompiling tmp_g8nabwz
// using Reko decompiler version 0.11.6.0.

#include "tmp_g8nabwz.h"

<unknown> g_t33AC = // 00000000000033AC;
<unknown> g_t33B2 = // 00000000000033B2;
// tmp_g8nabwz_got.c
// Generated by decompiling tmp_g8nabwz
// using Reko decompiler version 0.11.6.0.

#include "tmp_g8nabwz.h"

<anonymous> * _Z10InitOutputPSt15basic_streambufIcSt11char_traitsIcEE_GOT = &g_t2030; // 0000000000004E78
<anonymous> * strlen_GOT = &g_t2040; // 0000000000004E80
<anonymous> * _Z19CheckIfSimulateModeR11CommandLine_GOT = &g_t2050; // 0000000000004E88
<anonymous> * _ZN11CommandLineD1Ev_GOT = &g_t2060; // 0000000000004E90
<anonymous> * dgettext_GOT = &g_t2070; // 0000000000004E98
<anonymous> * _ZNK13Configuration5FindIEPKcRKi_GOT = &g_t2080; // 0000000000004EA0
<anonymous> * _Z21CheckIfCalledByScriptiPPKc_GOT = &g_t2090; // 0000000000004EA8
<anonymous> * __cxa_atexit_GOT = &g_t20A0; // 0000000000004EB0
<anonymous> * _Znwm_GOT = &g_t20B0; // 0000000000004EB8
<anonymous> * _ZdlPvm_GOT = &g_t20C0; // 0000000000004EC0
<anonymous> * _ZN11CommandLineC1Ev_GOT = &g_t20D0; // 0000000000004EC8
<anonymous> * __stack_chk_fail_GOT = &g_t20E0; // 0000000000004ED0
<anonymous> * _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l_GOT = &g_t20F0; // 0000000000004ED8
<anonymous> * _Z19DispatchCommandLineR11CommandLineRKSt6vectorINS_8DispatchESaIS2_EE_GOT = &g_t2100; // 0000000000004EE0
<anonymous> * _Z16ParseCommandLineR11CommandLine7APT_CMDPKP13ConfigurationPP9pkgSystemiPPKcPFbS0_EPFSt6vectorI19aptDispatchWithHelpSaISF_EEvE_GOT = &g_t2110; // 0000000000004EE8
<anonymous> * _ZNSt8ios_base4InitC1Ev_GOT = &g_t2120; // 0000000000004EF0
<anonymous> * _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate_GOT = &g_t2130; // 0000000000004EF8
<anonymous> * _Unwind_Resume_GOT = &g_t2140; // 0000000000004F00
<anonymous> * _ZN13Configuration6CndSetEPKci_GOT = &g_t2150; // 0000000000004F08
<anonymous> * _ZN13Configuration3SetEPKcRKi_GOT = &g_t2160; // 0000000000004F10
<anonymous> * _Z11InitSignalsv_GOT = &g_t2170; // 0000000000004F18
<anonymous> * _Z8RDependsR11CommandLine_GOT = null; // 0000000000004F20
<anonymous> * _Z7DoCleanR11CommandLine_GOT = null; // 0000000000004F28
<anonymous> * _Z9DoUpgradeR11CommandLine_GOT = null; // 0000000000004F30
<anonymous> * _Z8DoSourceR11CommandLine_GOT = null; // 0000000000004F38
<anonymous> * _Z8DoUpdateR11CommandLine_GOT = null; // 0000000000004F40
<anonymous> * _Z9DoInstallR11CommandLine_GOT = null; // 0000000000004F48
<anonymous> * __cxa_finalize_GOT = null; // 0000000000004F50
<anonymous> * _Z6DoListR11CommandLine_GOT = null; // 0000000000004F58
<anonymous> * _Z7DependsR11CommandLine_GOT = null; // 0000000000004F60
<anonymous> * __libc_start_main_GOT = null; // 0000000000004F68
<anonymous> * _Z10DoBuildDepR11CommandLine_GOT = null; // 0000000000004F70
<anonymous> * _Z11ShowPackageR11CommandLine_GOT = null; // 0000000000004F78
<anonymous> * _Z5DoMooR11CommandLine_GOT = null; // 0000000000004F80
<anonymous> * _Z10DoDownloadR11CommandLine_GOT = null; // 0000000000004F88
<anonymous> * _Z11EditSourcesR11CommandLine_GOT = null; // 0000000000004F90
<anonymous> * _Z11DoChangelogR11CommandLine_GOT = null; // 0000000000004F98
<anonymous> * _Z14ShowSrcPackageR11CommandLine_GOT = null; // 0000000000004FA0
<anonymous> * _system_GOT = null; // 0000000000004FA8
<anonymous> * _Z8DoSearchR11CommandLine_GOT = null; // 0000000000004FB0
<anonymous> * _Z11DoAutoCleanR11CommandLine_GOT = null; // 0000000000004FB8
<anonymous> * _ZSt4cout_GOT = null; // 0000000000004FC0
<anonymous> * _config_GOT = null; // 0000000000004FC8
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000004FD0
<anonymous> * _Z6PolicyR11CommandLine_GOT = null; // 0000000000004FD8
<anonymous> * __gmon_start___GOT = null; // 0000000000004FE0
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000004FE8
<anonymous> * _Z13DoDistUpgradeR11CommandLine_GOT = null; // 0000000000004FF0
<anonymous> * _ZNSt8ios_base4InitD1Ev_GOT = null; // 0000000000004FF8
// tmp_g8nabwz_plt.c
// Generated by decompiling tmp_g8nabwz
// using Reko decompiler version 0.11.6.0.

#include "tmp_g8nabwz.h"

<anonymous> g_t2030 = <code>; // 0000000000002030
<anonymous> g_t2040 = <code>; // 0000000000002040
<anonymous> g_t2050 = <code>; // 0000000000002050
<anonymous> g_t2060 = <code>; // 0000000000002060
<anonymous> g_t2070 = <code>; // 0000000000002070
<anonymous> g_t2080 = <code>; // 0000000000002080
<anonymous> g_t2090 = <code>; // 0000000000002090
<anonymous> g_t20A0 = <code>; // 00000000000020A0
<anonymous> g_t20B0 = <code>; // 00000000000020B0
<anonymous> g_t20C0 = <code>; // 00000000000020C0
<anonymous> g_t20D0 = <code>; // 00000000000020D0
<anonymous> g_t20E0 = <code>; // 00000000000020E0
<anonymous> g_t20F0 = <code>; // 00000000000020F0
<anonymous> g_t2100 = <code>; // 0000000000002100
<anonymous> g_t2110 = <code>; // 0000000000002110
<anonymous> g_t2120 = <code>; // 0000000000002120
<anonymous> g_t2130 = <code>; // 0000000000002130
<anonymous> g_t2140 = <code>; // 0000000000002140
<anonymous> g_t2150 = <code>; // 0000000000002150
<anonymous> g_t2160 = <code>; // 0000000000002160
<anonymous> g_t2170 = <code>; // 0000000000002170
