// tmp6ahl_fni_text.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

// 0000000000001160: void main(Register (ptr32 Eq_8) fs)
void main(struct Eq_8 * fs)
{
	word32 edx_30;
	askdo(fs, out edx_30);
}

// 0000000000001180: void _start(Register (ptr64 Eq_16) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t1160, (int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

// 00000000000011B0: void deregister_tm_clones()
// Called from:
//      __do_global_dtors_aux
void deregister_tm_clones()
{
	if (&g_b4010 == &g_b4010 || _ITM_deregisterTMCloneTable == null)
		return;
	_ITM_deregisterTMCloneTable();
}

// 00000000000011E0: void register_tm_clones()
// Called from:
//      frame_dummy
void register_tm_clones()
{
	Eq_51 rsi_6 = &g_b4010 - &g_b4010;
	if ((rsi_6 >> 0x3F) + (rsi_6 >> 0x03) >> 0x01 == 0x00 || _ITM_registerTMCloneTable == null)
		return;
	_ITM_registerTMCloneTable();
}

// 0000000000001220: void __do_global_dtors_aux()
void __do_global_dtors_aux()
{
	if (g_b4010 != 0x00)
		return;
	if (__cxa_finalize != 0x00)
		__cxa_finalize(g_qw4008);
	deregister_tm_clones();
	g_b4010 = 0x01;
}

// 0000000000001260: void frame_dummy()
void frame_dummy()
{
	register_tm_clones();
}

// 0000000000001270: Register word32 askdo(Register (ptr32 Eq_8) fs, Register out word32 edxOut)
// Called from:
//      main
//      askdo
//      repeat
word32 askdo(struct Eq_8 * fs, word32 & edxOut)
{
	word64 rax_15 = fs->qw0028;
	system("clear");
	puts("\x1B[1;32m---------------------------------------\x1B[0m");
	word64 v14_22 = g_qw4058;
	Eq_106 v16_27;
	v16_27.u1 = g_t4050.u1;
	__printf_chk(2, "\x1B[1;32m%Lf\x1B[0m\n", SEQ((word16) v14_22, v16_27));
	__printf_chk(2, "\x1B[1;32m---------------------------------------\x1B[0m");
	puts("\n0. Clear all\n1. Addition\n2. Subtraction\n3. Multiplication\n4. Division\n5. sin (deg)\n6. cos (deg)\n7.tan (deg)\n8. n Power\n9. n Root");
	__printf_chk(2, "Enter function option number/memory input num>9: ");
	__isoc99_scanf("%Lf", (<unknown>) &g_r4020);
	Eq_142 rLoc1_376;
	rLoc1_376.u0 = (real64) g_r4020;
	word24 eax_24_8_191 = SLICE(v16_27, word24, 8);
	word24 edx_24_8_199 = SLICE(v14_22, word24, 8);
	Eq_142 rLoc1_381 = rLoc1_376;
	if (!PARITY_EVEN(rLoc1_376 - rLoc1_376) && rLoc1_376 == rLoc1_376)
	{
		g_r4030 = (real80) 0.0;
		g_t4050.u0 = (real80) (real64) g_r4030;
		system("clear");
		word64 rdx_95 = <invalid>;
		word32 edx_454;
		eax_24_8_191 = SLICE((uint64) askdo(fs, out edx_454), word24, 8);
		edx_24_8_199 = SLICE(rdx_95, word24, 8);
		rLoc1_381.u0 = (real64) g_r4020;
	}
	if (rLoc1_381 >= rLoc1_381)
	{
		g_r4030 = (real80) rLoc1_381;
		g_t4050.u0 = (real80) rLoc1_381;
		system("clear");
		word64 rdx_139 = <invalid>;
		word32 edx_455;
		eax_24_8_191 = SLICE((uint64) askdo(fs, out edx_455), word24, 8);
		edx_24_8_199 = SLICE(rdx_139, word24, 8);
	}
	real64 rLoc2_395 = (real64) g_t4050.u0;
	if (!PARITY_EVEN(rLoc2_395 - 0.0) && rLoc2_395 == 0.0)
	{
		real64 rLoc1_397 = (real64) g_r4020;
		ui32 eax_174 = SEQ(eax_24_8_191, (byte) !PARITY_EVEN((real64) 2.0F - rLoc1_397));
		if (rLoc1_397 != 1.0)
			eax_174 = 0x00;
		real64 rLoc2_402 = (real64) 3.0F;
		ui32 edx_188 = SEQ(edx_24_8_199, (byte) !PARITY_EVEN(rLoc2_402 - rLoc1_397));
		if (rLoc2_402 != rLoc1_397)
			edx_188 = 0x00;
		byte al_219 = (byte) (eax_174 | edx_188);
		byte dl_214 = (byte) !PARITY_EVEN(rLoc2_402 - rLoc1_397);
		if (rLoc2_402 != rLoc1_397)
			dl_214 = 0x00;
		byte al_222 = al_219 | dl_214;
		if (al_222 != 0x00)
		{
l00000000000013AA:
			__printf_chk(2, "Enter memory number/primary number:");
			__isoc99_scanf("%Lf", (<unknown>) &g_t4050);
			goto l00000000000013CE;
		}
		real64 rLoc2_407 = (real64) 4.0F;
		byte dl_242 = (byte) !PARITY_EVEN(rLoc2_407 - rLoc1_397);
		if (rLoc2_407 == rLoc1_397)
			al_222 = dl_242;
		if (al_222 != 0x00)
			goto l00000000000013AA;
	}
l00000000000013CE:
	__printf_chk(2, "Enter performing number:");
	__isoc99_scanf("%Lf", (<unknown>) &g_t4040);
	real64 rLoc1_409 = (real64) g_r4020;
	Eq_212 wLoc3A_410 = __fstcw();
	__fldcw(SEQ(SLICE((uint64) wLoc3A_410, byte, 8) | 0x0C, (byte) wLoc3A_410));
	__fldcw(wLoc3A_410);
	if ((int32) rLoc1_409 > 0x09)
	{
		real64 rLoc1_413 = (real64) g_r4030;
		g_t4050.u0 = (real80) rLoc1_413;
		system("clear");
		word32 edx_456;
		askdo(fs, out edx_456);
		if (rax_15 != fs->qw0028)
			__stack_chk_fail();
		else
		{
			edxOut = <invalid>;
			return 0x00;
		}
	}
}

// 0000000000001690: void repeat(Register (ptr32 Eq_8) fs)
void repeat(struct Eq_8 * fs)
{
	g_t4050.u0 = (real80) (real64) g_r4030;
	system("clear");
	word32 edx_30;
	askdo(fs, out edx_30);
}

// tmp6ahl_fni_init.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

// 0000000000001000: void _init()
void _init()
{
	if (__gmon_start__ != 0x00)
		__gmon_start__();
}

// tmp6ahl_fni_bss.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

byte g_b4010 = 0x00; // 0000000000004010
real80 g_r4020 = // 0000000000004020
	{
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	};
real80 g_r4030 = // 0000000000004030
	{
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	};
<unknown> g_t4040 = // 0000000000004040;
Eq_106 g_t4050 = // 0000000000004050
	{
		
		{
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
		}
	};
word64 g_qw4058 = 0x00; // 0000000000004058
// tmp6ahl_fni_got.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

<anonymous> * puts_GOT = &g_t1030; // 0000000000003F90
<anonymous> * pow_GOT = &g_t1040; // 0000000000003F98
<anonymous> * __stack_chk_fail_GOT = &g_t1050; // 0000000000003FA0
<anonymous> * system_GOT = &g_t1060; // 0000000000003FA8
<anonymous> * cos_GOT = &g_t1070; // 0000000000003FB0
<anonymous> * tan_GOT = &g_t1080; // 0000000000003FB8
<anonymous> * __printf_chk_GOT = &g_t1090; // 0000000000003FC0
<anonymous> * sin_GOT = &g_t10A0; // 0000000000003FC8
<anonymous> * __isoc99_scanf_GOT = &g_t10B0; // 0000000000003FD0
<anonymous> * __libc_start_main_GOT = null; // 0000000000003FD8
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000003FE0
<anonymous> * __gmon_start___GOT = null; // 0000000000003FE8
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000003FF0
<anonymous> * __cxa_finalize_GOT = null; // 0000000000003FF8
// tmp6ahl_fni_fini.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

// 00000000000016C0: void _fini()
void _fini()
{
}

// tmp6ahl_fni_rodata.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

real32 g_r2008 = 2.0F; // 0000000000002008
real32 g_r200C = 3.0F; // 000000000000200C
real32 g_r2010 = 4.0F; // 0000000000002010
// tmp6ahl_fni_plt.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

<anonymous> g_t1030 = <code>; // 0000000000001030
<anonymous> g_t1040 = <code>; // 0000000000001040
<anonymous> g_t1050 = <code>; // 0000000000001050
<anonymous> g_t1060 = <code>; // 0000000000001060
<anonymous> g_t1070 = <code>; // 0000000000001070
<anonymous> g_t1080 = <code>; // 0000000000001080
<anonymous> g_t1090 = <code>; // 0000000000001090
<anonymous> g_t10A0 = <code>; // 00000000000010A0
<anonymous> g_t10B0 = <code>; // 00000000000010B0
// tmp6ahl_fni_data.c
// Generated by decompiling tmp6ahl_fni
// using Reko decompiler version 0.11.6.0.

#include "tmp6ahl_fni.h"

word64 g_qw4008 = 0x4008; // 0000000000004008
