// tmphm3bt701_text.c
// Generated by decompiling tmphm3bt701
// using Reko decompiler version 0.11.6.0.

#include "tmphm3bt701.h"

// 0000000000001280: void main(Register word64 rsi, Register word32 edi, Register (ptr32 Eq_4) fs)
void main(word64 rsi, word32 edi, struct Eq_4 * fs)
{
	word64 rax_24 = fs->qw0028;
	word64 rax_34 = gedit_app_get_type(rax_24);
	word64 rdi_33;
	gedit_dirs_init((word32) rdi_33);
	setlocale(6, "");
	char * rax_56 = gedit_dirs_get_gedit_locale_dir(0x06, 0x06, "");
	bindtextdomain("gedit", rax_56);
	bind_textdomain_codeset("gedit", "gedit", rax_56, &g_t2004);
	textdomain("gedit");
	word64 rax_93 = g_object_new(0x0C, 0x0C, 0x00, 0x00, &g_t200A, "gedit", rax_34, &g_t2010, &g_t2020);
	word64 rdi_92;
	g_application_run(edi, g_type_check_instance_cast(rax_93, g_application_get_type((word32) rdi_92, rax_93)), rsi, (uint64) edi);
	word64 rdi_126;
	gedit_settings_unref_singleton((word32) rdi_126);
	g_object_run_dispose(g_type_check_instance_cast(0x50, rax_93, 0x50));
	ptr64 fp;
	g_object_add_weak_pointer(g_type_check_instance_cast(0x50, rax_93, 0x50), fp - 0x38);
	g_object_unref(rax_93);
	if (rax_93 != 0x00)
		gedit_debug_message(0x0100, 161, &g_t202F, (uint64) g_type_check_instance_cast(0x50, 0x50)->dw0008, &g_t2055, 0x0100, 161, &g_t2044);
	gedit_dirs_shutdown();
	if (rax_24 == fs->qw0028)
		return;
	__stack_chk_fail();
}

// 00000000000013F0: void _start(Register (ptr64 Eq_126) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
void _start(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t1280, (int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

// tmphm3bt701_plt.c
// Generated by decompiling tmphm3bt701
// using Reko decompiler version 0.11.6.0.

#include "tmphm3bt701.h"

<anonymous> g_t1030 = <code>; // 0000000000001030
<anonymous> g_t1040 = <code>; // 0000000000001040
<anonymous> g_t1050 = <code>; // 0000000000001050
<anonymous> g_t1060 = <code>; // 0000000000001060
<anonymous> g_t1070 = <code>; // 0000000000001070
<anonymous> g_t1080 = <code>; // 0000000000001080
<anonymous> g_t1090 = <code>; // 0000000000001090
<anonymous> g_t10A0 = <code>; // 00000000000010A0
<anonymous> g_t10B0 = <code>; // 00000000000010B0
<anonymous> g_t10C0 = <code>; // 00000000000010C0
<anonymous> g_t10D0 = <code>; // 00000000000010D0
<anonymous> g_t10E0 = <code>; // 00000000000010E0
<anonymous> g_t10F0 = <code>; // 00000000000010F0
<anonymous> g_t1100 = <code>; // 0000000000001100
<anonymous> g_t1110 = <code>; // 0000000000001110
<anonymous> g_t1120 = <code>; // 0000000000001120
<anonymous> g_t1130 = <code>; // 0000000000001130
<anonymous> g_t1140 = <code>; // 0000000000001140
// tmphm3bt701_rodata.c
// Generated by decompiling tmphm3bt701
// using Reko decompiler version 0.11.6.0.

#include "tmphm3bt701.h"

<unknown> g_t2004 = // 0000000000002004;
<unknown> g_t200A = // 000000000000200A;
<unknown> g_t2010 = // 0000000000002010;
<unknown> g_t2020 = // 0000000000002020;
<unknown> g_t202F = // 000000000000202F;
<unknown> g_t2044 = // 0000000000002044;
<unknown> g_t2055 = // 0000000000002055;
// tmphm3bt701_got.c
// Generated by decompiling tmphm3bt701
// using Reko decompiler version 0.11.6.0.

#include "tmphm3bt701.h"

<anonymous> * g_application_run_GOT = &g_t1030; // 0000000000003F48
<anonymous> * g_type_check_instance_cast_GOT = &g_t1040; // 0000000000003F50
<anonymous> * __stack_chk_fail_GOT = &g_t1050; // 0000000000003F58
<anonymous> * gedit_dirs_get_gedit_locale_dir_GOT = &g_t1060; // 0000000000003F60
<anonymous> * bindtextdomain_GOT = &g_t1070; // 0000000000003F68
<anonymous> * bind_textdomain_codeset_GOT = &g_t1080; // 0000000000003F70
<anonymous> * g_object_add_weak_pointer_GOT = &g_t1090; // 0000000000003F78
<anonymous> * g_application_get_type_GOT = &g_t10A0; // 0000000000003F80
<anonymous> * g_object_run_dispose_GOT = &g_t10B0; // 0000000000003F88
<anonymous> * gedit_debug_message_GOT = &g_t10C0; // 0000000000003F90
<anonymous> * gedit_dirs_init_GOT = &g_t10D0; // 0000000000003F98
<anonymous> * setlocale_GOT = &g_t10E0; // 0000000000003FA0
<anonymous> * gedit_app_get_type_GOT = &g_t10F0; // 0000000000003FA8
<anonymous> * g_object_new_GOT = &g_t1100; // 0000000000003FB0
<anonymous> * textdomain_GOT = &g_t1110; // 0000000000003FB8
<anonymous> * g_object_unref_GOT = &g_t1120; // 0000000000003FC0
<anonymous> * gedit_dirs_shutdown_GOT = &g_t1130; // 0000000000003FC8
<anonymous> * gedit_settings_unref_singleton_GOT = &g_t1140; // 0000000000003FD0
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000003FD8
<anonymous> * __cxa_finalize_GOT = null; // 0000000000003FE0
<anonymous> * __gmon_start___GOT = null; // 0000000000003FE8
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000003FF0
<anonymous> * __libc_start_main_GOT = null; // 0000000000003FF8
