// tmpzpz4fq5n_text.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

// 00000000000025B0: void fn00000000000025B0(Register (arr (ptr64 char)) rsi, Register word32 edi, Register (ptr32 Eq_4) fs)
void fn00000000000025B0(char * rsi[], word32 edi, struct Eq_4 * fs)
{
	Eq_7 rbx_20;
	rbx_20.u0 = rsi[0];
	if (rbx_20 != 0x00)
	{
		Eq_34 rax_32 = strrchr(rbx_20, '/');
		if (rax_32 != 0x00 && ((rax_32 + (char *) 1) - rbx_20 > 0x06 && strncmp(rax_32 - (char *) 6, "/.libs/", 7) == 0x00))
		{
			rbx_20.u0 = rax_32 + (char *) 1;
			if (strncmp(rax_32 + (char *) 1, "lt-", 3) == 0x00)
			{
				*program_invocation_short_name_GOT = rax_32 + (char *) 4;
				rbx_20.u0 = rax_32 + (char *) 4;
			}
		}
		union Eq_7 * rax_66 = program_invocation_name_GOT;
		g_t81C0.u0 = (char *) rbx_20;
		rax_66->u0 = (char *) rbx_20;
		setlocale(6, "");
		bindtextdomain("coreutils", "/usr/share/locale");
		textdomain("coreutils");
		fn0000000000004D00(&g_t4C80);
		fn0000000000002F60(0x00, rsi, edi, "8.32", fs);
		int64 rax_129 = (int64) *optind_GOT;
		if ((word32) rax_129 != edi)
		{
			fn0000000000004AE0(&g_t8040, rsi[rax_129], fs);
			error(0, 0, dcgettext(null, "extra operand %s", 5), 0x00);
			fn0000000000002990(0x01);
		}
		int32 * rax_171 = __errno_location();
		*rax_171 = 0x00;
		Eq_168 eax_174 = geteuid();
		if (eax_174 != ~0x00 || *rax_171 == 0x00)
		{
			struct passwd * rax_185 = getpwuid(eax_174);
			if (rax_185 != null)
			{
				puts(rax_185->pw_name);
				return;
			}
		}
		error(1, *rax_171, dcgettext(null, "cannot find name for user ID %lu", 5), 0x00);
	}
	fwrite(&g_v5560, 0x01, 55, *stderr_GOT);
	abort();
}

// 00000000000027B0: void fn00000000000027B0(Register (ptr64 Eq_211) rdx, Stack word32 dwArg00, Stack (ptr64 char) ptrArg08)
// Called from:
//      fn00000000000025B0
void fn00000000000027B0(void (* rdx)(), word32 dwArg00, char * ptrArg08)
{
	__align_stack<word64>(&ptrArg08);
	word64 qwArg00;
	void * fp;
	__libc_start_main(&g_t25B0, (int32) qwArg00, &ptrArg08, null, null, rdx, fp);
	__halt();
}

// 00000000000028A0: Register word32 fn00000000000028A0(Register (ptr64 Eq_240) rdi, Register (ptr64 Eq_240) rsi, Register byte dl, Register byte cl)
// Called from:
//      fn0000000000002D10
word32 fn00000000000028A0(struct Eq_240 * rdi, struct Eq_240 * rsi, byte dl, byte cl)
{
	word64 rdx;
	dl = (byte) rdx;
	word64 rcx;
	cl = (byte) rcx;
	word32 r8d_13 = (word32) rdi->b0007;
	byte r8b_18 = (byte) r8d_13;
	byte sil_21;
	if ((int32) dl <= 0x5A && (int32) dl >= 0x41)
		sil_21 = (byte) (((byte) r8d_13 & 223) == dl);
	else
		sil_21 = (byte) (dl == r8b_18);
	if (sil_21 == 0x00)
		return 0x00;
	word32 r8d_159 = 0x01;
	if (dl == 0x00)
		return r8d_159;
	word32 esi_46 = (word32) rdi->b0008;
	byte sil_53 = (byte) esi_46;
	byte dl_56;
	if ((int32) cl <= 0x5A && (int32) cl >= 0x41)
		dl_56 = (byte) (((byte) esi_46 & 223) == cl);
	else
		dl_56 = (byte) (cl == sil_53);
	if (dl_56 == 0x00)
		return 0x00;
	r8d_159 = 0x01;
	if (cl != 0x00 && rdi != rsi)
	{
		Eq_303 rcx_141;
		rcx_141.u1 = 0x09;
		up32 r9d_149;
		byte dl_133;
		up32 r8d_119;
		byte sil_142;
		do
		{
			up32 r9d_94 = (word32) *(rdi + rcx_141);
			r9d_149 = r9d_94;
			uint64 rdx_108 = SEQ(SLICE((uint64) r9d_94, word56, 8), (byte) r9d_94);
			if (r9d_94 <= 0x5A && r9d_94 >= 0x41)
			{
				r9d_149 = r9d_94 + 0x20;
				rdx_108 = (uint64) (r9d_94 + 0x20);
			}
			up32 r8d_115 = (word32) *(rsi + rcx_141);
			dl_133 = (byte) rdx_108;
			r8d_119 = r8d_115;
			uint64 rsi_129 = SEQ(SLICE((uint64) r8d_115, word56, 8), (byte) r8d_115);
			if (r8d_115 <= 0x5A && r8d_115 >= 0x41)
			{
				r8d_119 = r8d_115 + 0x20;
				rsi_129 = (uint64) (r8d_115 + 0x20);
			}
			sil_142 = (byte) rsi_129;
			if (dl_133 == 0x00)
				break;
			rcx_141 = (word64) rcx_141 + 1;
		} while (dl_133 == sil_142);
		r8d_159 = (word32) (r9d_149 == r8d_119);
	}
	return r8d_159;
}

// 0000000000002990: void fn0000000000002990(Register int32 edi)
// Called from:
//      fn00000000000025B0
//      fn0000000000002F60
void fn0000000000002990(int32 edi)
{
	ptr64 fp;
	if (edi != 0x00)
	{
		__fprintf_chk(*stderr_GOT, 1, dcgettext(null, "Try '%s --help' for more information.\n", 5), 0x00);
		goto l00000000000029F1;
	}
	__printf_chk(1, dcgettext(null, "Usage: %s [OPTION]...\n", 5), 0x00);
	FILE ** r13_54 = (FILE **) stdout_GOT;
	fputs_unlocked(dcgettext(null, "Print the user name associated with the current effective user ID.\nSame as id -un.\n\n", 5), *r13_54);
	fputs_unlocked(dcgettext(null, "      --help     display this help and exit\n", 5), *r13_54);
	fputs_unlocked(dcgettext(null, "      --version  output version information and exit\n", 5), *r13_54);
	struct Eq_434 * rbx_113 = fp - 0xB8 + 16;
	char * rsi_115;
	do
	{
		rsi_115 = rbx_113->qw0000;
		++rbx_113;
	} while (rsi_115 != null && strcmp("whoami", rsi_115) != 0x00);
	char * r14_130 = rbx_113->qw0008;
	if (r14_130 != null)
	{
		__printf_chk(1, dcgettext(null, "\n%s online help: <%s>\n", 5), 0x00);
		char * rax_218 = setlocale(5, null);
		if (rax_218 == null || strncmp(rax_218, "en_", 3) == 0x00)
			goto l0000000000002BA6;
	}
	else
	{
		__printf_chk(1, dcgettext(null, "\n%s online help: <%s>\n", 5), 0x00);
		char * rax_160 = setlocale(5, null);
		if (rax_160 == null || strncmp(rax_160, "en_", 3) == 0x00)
		{
			__printf_chk(1, dcgettext(null, "Full documentation <%s%s>\n", 5), 0x00);
l0000000000002BE3:
			__printf_chk(1, dcgettext(null, "or available locally via: info '(coreutils) %s%s'\n", 5), 0x00);
l00000000000029F1:
			exit(edi);
		}
		r14_130 = (char *) "whoami";
	}
	fputs_unlocked(dcgettext(null, "Report any translation bugs to <https://translationproject.org/team/>\n", 5), *r13_54);
l0000000000002BA6:
	__printf_chk(1, dcgettext(null, "Full documentation <%s%s>\n", 5), 0x00);
	goto l0000000000002BE3;
}

// 0000000000002CD0: void fn0000000000002CD0()
// Called from:
//      fn0000000000004AE0
void fn0000000000002CD0()
{
	dcgettext(null, "memory exhausted", 5);
	error(g_dw8024, 0, "%s", 0x00);
	abort();
}

// 0000000000002D10: Register (ptr64 Eq_641) fn0000000000002D10(Register up32 esi, Register (ptr64 Eq_641) rdi, Register out word32 edxOut)
// Called from:
//      fn0000000000003640
union Eq_641 * fn0000000000002D10(up32 esi, union Eq_641 * rdi, word32 & edxOut)
{
	word64 rsi;
	esi = (word32) rsi;
	struct Eq_240 * rax_18 = nl_langinfo(0x0E);
	if (rax_18 != null)
	{
		word32 eax_24 = (word32) rax_18->a0000[0];
		if ((byte) eax_24 != 0x00)
		{
			byte al_34 = (byte) eax_24 & 223;
			if (al_34 == 0x55)
			{
				if ((rax_18->b0001 & 223) == 0x54 && ((rax_18->b0002 & 223) == 0x46 && (rax_18->b0003 == 0x2D && (rax_18->b0004 == 0x38 && rax_18->b0005 == 0x00))))
				{
					union Eq_641 * rax_137 = (union Eq_641 *) &g_u50E5;
					if (rdi->u0 != 0x60)
						rax_137 = (union Eq_641 *) &g_u50D6;
					edxOut = <invalid>;
					return rax_137;
				}
			}
			else if (al_34 == 0x47 && ((rax_18->b0001 & 223) == 66 && (rax_18->b0002 == 0x31 && (rax_18->b0003 == 0x38 && (rax_18->b0004 == 0x30 && (rax_18->b0005 == 0x33 && (rax_18->b0006 == 0x30 && fn00000000000028A0(rax_18, &g_t50E9, 0x00, 0x00) != 0x00)))))))
			{
				union Eq_641 * rax_196 = (union Eq_641 *) &g_u50E1;
				if (rdi->u0 != 0x60)
					rax_196 = (union Eq_641 *) &g_u50DA;
				edxOut = <invalid>;
				return rax_196;
			}
		}
	}
	union Eq_641 * rax_122 = (union Eq_641 *) &g_u50DD;
	if (esi != 0x09)
		rax_122 = (union Eq_641 *) &g_u50DF;
	edxOut = <invalid>;
	return rax_122;
}

// 0000000000002E00: void fn0000000000002E00(Register (ptr64 Eq_762) rdi)
// Called from:
//      fn0000000000004AE0
void fn0000000000002E00(FILE * rdi)
{
	Eq_14 rax_21 = __fpending(rdi);
	word32 rax_32_32_281 = SLICE(rax_21, word32, 32);
	ui32 ebx_126 = rdi->dw0000 & 0x20;
	word64 rax_342;
	if (fileno(rdi) < 0x00)
	{
l0000000000002E9F:
		rax_342 = SEQ(rax_32_32_281, fclose(rdi));
		goto l0000000000002EA4;
	}
	if (__freading(rdi) != 0x00)
	{
		Eq_797 rax_48 = lseek(fileno(rdi), 0x00, 1);
		rax_32_32_281 = SLICE(rax_48, word32, 32);
		if (rax_48 == ~0x00)
			goto l0000000000002E9C;
	}
	if (__freading(rdi) != 0x00 && (rdi->dw0000 & 0x0100) != 0x00)
	{
		word64 rax_63 = (word64) (&rdi->dw0000)[2];
		rax_32_32_281 = SLICE(rax_63, word32, 32);
		if ((&rdi->dw0000)[4] == rax_63)
		{
			word64 rax_66 = (word64) (&rdi->dw0000)[8];
			rax_32_32_281 = SLICE(rax_66, word32, 32);
			if ((&rdi->dw0000)[0x0A] == rax_66 && (&rdi->dw0000)[18] == 0x00)
			{
				Eq_797 rax_79 = lseek(fileno(rdi), 0x00, 1);
				rax_32_32_281 = SLICE(rax_79, word32, 32);
				if (rax_79 != ~0x00)
				{
					rdi->dw0000 &= ~0x10;
					rdi->t0090.u0 = (uint64) rax_79;
				}
				goto l0000000000002E41;
			}
		}
		fseeko(rdi, 0x00, 1);
		goto l0000000000002E41;
	}
	else
	{
l0000000000002E41:
		if (fflush(rdi) != 0x00)
		{
			int32 * rax_110 = __errno_location();
			int32 r14d_114 = *rax_110;
			rax_342 = SEQ(SLICE(rax_110, word32, 32), fclose(rdi));
			if (r14d_114 != 0x00)
			{
				*rax_110 = r14d_114;
				if (ebx_126 != 0x00)
					return;
				goto l0000000000002EB0;
			}
l0000000000002EA4:
			word32 eax_134 = (word32) rax_342;
			if (ebx_126 != 0x00)
			{
				if (eax_134 == 0x00)
					*__errno_location() = 0x00;
				return;
			}
			if (eax_134 == 0x00)
				return;
l0000000000002EB0:
			if (rax_21 != 0x00)
				return;
			__errno_location();
			return;
		}
l0000000000002E9C:
		goto l0000000000002E9F;
	}
}

// 0000000000002F60: void fn0000000000002F60(Register byte al, Register (ptr64 (arr (ptr64 char))) rsi, Register word32 edi, Register (ptr64 char) r8, Register (ptr32 Eq_4) fs)
// Called from:
//      fn00000000000025B0
void fn0000000000002F60(byte al, char * (* rsi)[], word32 edi, char * r8, struct Eq_4 * fs)
{
	ptr64 fp;
	word64 rdi;
	word32 * rbx_47 = opterr_GOT;
	word64 rax_54 = fs->qw0028;
	word32 r12d_59 = *rbx_47;
	*rbx_47 = 0x01;
	int32 eax_66 = getopt_long((int32) rdi, rsi, "", &g_t7BE0, null);
	switch (eax_66)
	{
	case ~0x00:
		*rbx_47 = r12d_59;
		if (rax_54 == fs->qw0028)
			return;
		__stack_chk_fail();
		break;
	case 0x68:
		fn0000000000002990(0x00);
		break;
	case 118:
		byte dil_155 = 0x00;
		byte r8b_167 = 0x00;
		uint64 rbx_108;
		up32 edx_124 = 0x30;
		word64 * rcx_120 = fp + 0x10;
		FILE * r12_123 = *stdout_GOT;
		for (rbx_108 = 0x00; rbx_108 != 0x0A; ++rbx_108)
		{
			word64 * rax_134;
			if (edx_124 > 0x2F)
			{
				rax_134 = rcx_120;
				dil_155 = 0x01;
				++rcx_120;
			}
			else
			{
				r8b_167 = 0x01;
				edx_124 += 0x08;
				rax_134 = (uint64) edx_124 + (fp - 232);
			}
			word64 rax_145 = *rax_134;
			(fp - 0x0148)[rbx_108] = rax_145;
			if (rax_145 == 0x00)
			{
				__fprintf_chk(r12_123, 1, "%s (%s) %s\n", "whoami", "GNU coreutils", r8);
				char * rax_205 = dcgettext(null, "(C)", 5);
				__fprintf_chk(r12_123, 1, "Copyright %s %d Free Software Foundation, Inc.", rax_205, 2020);
				fputc_unlocked(0x00, 0x0A, 0x05, 0x01, 0x01, "GNU coreutils", 2020, 2020, r8, "whoami", rax_205, r12_123, 0x00, r12_123, 0x0A, &g_t50E9.b0008, 0x05, &g_t5920, 0x01, "(C)", 0x01, r12_123);
				__fprintf_chk(r12_123, 1, dcgettext(null, "License GPLv3+: GNU GPL version 3 or later <%s>.\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n", 5), 0x00);
				fputc_unlocked(0x0A, 0x0A, r12_123);
				if (rbx_108 > 0x09 || rbx_108 < 0x01)
					goto l000000000000322B;
			}
		}
		__fprintf_chk(r12_123, 1, "%s (%s) %s\n", "whoami", "GNU coreutils", r8);
		char * rax_344 = dcgettext(null, "(C)", 5);
		__fprintf_chk(r12_123, 1, "Copyright %s %d Free Software Foundation, Inc.", rax_344, 2020);
		fputc_unlocked(0x00, 0x0A, 0x05, 0x01, 0x01, "GNU coreutils", 2020, 2020, r8, "whoami", rax_344, r12_123, 0x00, r12_123, 0x0A, &g_t50E9.b0008, 0x05, &g_t5920, 0x01, "(C)", 0x01, r12_123);
		__fprintf_chk(r12_123, 1, dcgettext(null, "License GPLv3+: GNU GPL version 3 or later <%s>.\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n", 5), 0x00);
		fputc_unlocked(0x0A, 0x0A, r12_123);
		char * rax_426 = dcgettext(null, "Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n", 5);
		__fprintf_chk(r12_123, 1, rax_426, 0x00);
l000000000000322B:
		exit(0);
		break;
	default:
		fn0000000000002990(g_dw8024);
		break;
	}
}

// 0000000000003570: Register byte fn0000000000003570(Register (ptr32 Eq_4) fs)
// Called from:
//      fn0000000000003640
byte fn0000000000003570(struct Eq_4 * fs)
{
	word64 qwLoc0128;
	word64 rax_16 = fs->qw0028;
	char * rax_20 = setlocale(0, null);
	uint32 r12d_27;
	if (rax_20 != null)
	{
		r12d_27 = 0x00;
		Eq_14 rax_35 = strlen(rax_20);
		if (rax_35 <= 0x0100)
		{
			char * rax_43 = __memcpy_chk(&qwLoc0128, rax_20, (word64) rax_35 + 1, 0x0101);
			if (qwLoc0128 != 0x43 || qwLoc0128.b0001 != 0x00)
				r12d_27 = (uint32) (strcmp(rax_43, "POSIX") != 0x00);
		}
	}
	else
		r12d_27 = 0x00;
	if (rax_16 == fs->qw0028)
		return (byte) r12d_27;
	__stack_chk_fail();
}

// 0000000000003640: Register Eq_1255 fn0000000000003640(Register up32 ecx, Register (ptr64 Eq_128) rdx, Register Eq_1255 rsi, Register Eq_1259 rdi, Register ui32 r8d, Register (ptr64 (arr uint32)) r9, Register (ptr32 Eq_4) fs, Stack (ptr64 Eq_641) qwArg08, Stack (ptr64 Eq_641) qwArg10)
// Called from:
//      fn0000000000004AE0
Eq_1255 fn0000000000003640(up32 ecx, struct Eq_128 * rdx, Eq_1255 rsi, Eq_1259 rdi, ui32 r8d, uint32 (* r9)[], struct Eq_4 * fs, union Eq_641 * qwArg08, union Eq_641 * qwArg10)
{
	word64 r8;
	r8d = (word32) r8;
	up32 r11d_3530 = ecx;
	Eq_14 r14_1172;
	r14_1172.u0 = ~0x00;
	Eq_1259 r13_18 = rdi;
	Eq_1255 r12_1175 = rsi;
	union Eq_641 * qwLoc68_4075 = qwArg08;
	ui32 dwLoc80_4077 = r8d;
	uint32 (* qwLocF0_4078)[] = r9;
	union Eq_641 * qwLoc70_4079 = qwArg10;
	word64 rax_43 = fs->qw0028;
l00000000000036B0:
	up32 r11d_334 = r11d_3530;
	Eq_14 qwLocA0_4083 = __ctype_get_mb_cur_max();
	ui32 ebx_150 = dwLoc80_4077 & 0x02;
	if (r11d_3530 > 0x0A)
		abort();
	word24 edx_24_8_1571 = SLICE(g_a55E4, word24, 8);
	ui24 eax_24_8_1408 = SLICE((char *) g_a55E4 + (int64) g_a55E4[(uint64) r11d_3530], word24, 8);
	byte bLocD2_4101;
	byte bpl_325;
	Eq_1255 r15_1204;
	Eq_14 qwLocE0_4103;
	union Eq_641 * qwLocB0_4102;
	word24 ebp_24_8_2604;
	uint32 esi_319;
	byte bLoc7C_4124;
	byte bLocD8_4123;
	Eq_1255 qwLocA8_4125;
	byte al_3279;
	switch (r11d_3530)
	{
	case 0x00:
		bLocD2_4101 = 0x00;
		bpl_325 = 0x00;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x00;
		qwLocB0_4102 = null;
		break;
	case 0x01:
		goto l0000000000003B6C;
	case 0x02:
		if (ebx_150 == 0x00)
		{
			bpl_325 = 0x00;
l0000000000003C88:
			ebp_24_8_2604 = 0x00;
			eax_24_8_1408 = SLICE(&g_u50DF, word24, 8);
			bLocD2_4101 = 0x00;
			esi_319 = 0x00;
			r11d_334 = 0x02;
			qwLocB0_4102 = (union Eq_641 *) &g_u50DF;
			r15_1204.u0 = 0x01;
			qwLocE0_4103.u0 = 0x01;
			bLoc7C_4124 = 0x00;
			bLocD8_4123 = 0x01;
			qwLocA8_4125.u0 = 0x00;
			if (r12_1175 != 0x00)
			{
				al_3279 = 0x00;
				goto l0000000000004509;
			}
			goto l00000000000037A1;
		}
		eax_24_8_1408 = SLICE(&g_u50DF, word24, 8);
		bLocD2_4101 = 0x01;
		bpl_325 = 0x00;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x01;
		qwLocB0_4102 = (union Eq_641 *) &g_u50DF;
		break;
	case 0x03:
		bpl_325 = 0x01;
		goto l0000000000003B1D;
	case 0x04:
		if (ebx_150 == 0x00)
			goto l0000000000003C83;
l0000000000003B6C:
		bpl_325 = 0x00;
l0000000000003B1D:
		bLocD2_4101 = 0x01;
		eax_24_8_1408 = SLICE(&g_u50DF, word24, 8);
		r15_1204.u0 = 0x00;
		r11d_334 = 0x02;
		qwLocE0_4103.u0 = 0x01;
		qwLocB0_4102 = (union Eq_641 *) &g_u50DF;
		break;
	case 0x05:
		if (ebx_150 == 0x00)
		{
l0000000000003AC0:
			eax_24_8_1408 = SLICE(&g_u50DD, word24, 8);
			bLocD2_4101 = 0x00;
			bpl_325 = 0x01;
			ebp_24_8_2604 = 0x00;
			esi_319 = 0x00;
			qwLocB0_4102 = (union Eq_641 *) &g_u50DD;
			r11d_334 = 0x05;
			r15_1204.u0 = 0x01;
			qwLocE0_4103.u0 = 0x01;
			bLoc7C_4124 = 0x00;
			bLocD8_4123 = 0x01;
			qwLocA8_4125.u0 = 0x00;
			if (r12_1175 != 0x00)
				*r13_18.u1 = (char) 0x22;
			goto l00000000000037A1;
		}
		eax_24_8_1408 = SLICE(&g_u50DD, word24, 8);
		bLocD2_4101 = 0x01;
		bpl_325 = 0x01;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x01;
		qwLocB0_4102 = (union Eq_641 *) &g_u50DD;
		break;
	case 0x06:
		eax_24_8_1408 = SLICE(&g_u50DD, word24, 8);
		bLocD2_4101 = 0x01;
		bpl_325 = 0x01;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x01;
		r11d_334 = 0x05;
		qwLocB0_4102 = (union Eq_641 *) &g_u50DD;
		break;
	case 0x07:
		bLocD2_4101 = 0x00;
		bpl_325 = 0x01;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x00;
		qwLocB0_4102 = null;
		break;
	case 0x08:
	case 0x09:
	case 0x0A:
		if (r11d_3530 != 0x0A)
		{
			union Eq_641 * rax_84 = dcgettext(null, &g_u514A, 5);
			qwLoc68_4075 = rax_84;
			if (rax_84 == &g_u514A)
			{
				word32 edx_8221;
				qwLoc68_4075 = fn0000000000002D10(r11d_3530, rax_84, out edx_8221);
			}
			union Eq_641 * rax_120 = dcgettext(null, &g_u50DF, 5);
			edx_24_8_1571 = 0x00;
			qwLoc70_4079 = rax_120;
			if (rax_120 == &g_u50DF)
			{
				word64 rdx_132 = <invalid>;
				edx_24_8_1571 = SLICE(rdx_132, word24, 8);
				word32 edx_8222;
				qwLoc70_4079 = fn0000000000002D10(r11d_3530, rax_120, out edx_8222);
			}
		}
		r15_1204.u0 = 0x00;
		if (ebx_150 == 0x00)
		{
			edx_24_8_1571 = SLICE(qwLoc68_4075, word24, 8);
			byte al_162 = qwLoc68_4075->u0;
			while (al_162 != 0x00)
			{
				if (r12_1175 > r15_1204)
					*(r13_18 + r15_1204) = (word64) al_162;
				r15_1204.u0 = (word128) r15_1204 + 1;
				al_162 = (byte) *(qwLoc68_4075 + r15_1204);
			}
		}
		Eq_14 rax_209 = strlen(qwLoc70_4079);
		bpl_325 = 0x01;
		bLocD2_4101 = (byte) (ebx_150 != 0x00);
		eax_24_8_1408 = SLICE(rax_209, word24, 8);
		qwLocB0_4102 = qwLoc70_4079;
		r11d_334 = r11d_3530;
		qwLocE0_4103 = rax_209;
		break;
	}
	ebp_24_8_2604 = 0x00;
	bLocD8_4123 = 0x01;
	esi_319 = 0x00;
	bLoc7C_4124 = 0x00;
	qwLocA8_4125.u0 = 0x00;
l00000000000037A1:
	word24 nLoc7F_7025 = SLICE(dwLoc80_4077, word24, 8);
	byte bLoc80_5437 = (byte) dwLoc80_4077;
	byte bLocD3_4126 = bpl_325;
	Eq_1255 r10_1174 = r12_1175;
	Eq_14 r12_1142 = r14_1172;
	up32 r13d_3661 = r11d_334;
	uint32 r11d_3712 = esi_319;
	Eq_14 r9_1085;
	uint64 r11_7920;
	word32 r11_32_32_7254;
	byte r11b_1690;
	word24 r11d_24_8_1090;
	byte bpl_2065;
	while (true)
	{
		r9_1085.u0 = 0x00;
		r11_7920 = (uint64) r11d_3712;
l00000000000037C0:
		uint32 r11d_486 = (word32) r11_7920;
		r11_32_32_7254 = SLICE(r11_7920, word32, 32);
		r11b_1690 = (byte) r11d_486;
		r11d_24_8_1090 = SLICE(r11d_486, word24, 8);
		bpl_2065 = (byte) (r9_1085 != r12_1142);
		if (r12_1142 == ~0x00)
		{
			eax_24_8_1408 = SLICE(rdx, word24, 8);
			bpl_2065 = (byte) (*(rdx + r9_1085) != 0x00);
		}
		if (bpl_2065 != 0x00)
			break;
		uint8 al_372 = (byte) (r13d_3661 == 0x02);
		ui32 edi_366 = (word32) bLocD2_4101;
		ui32 edx_386 = edi_366 & SEQ(eax_24_8_1408, al_372);
		edx_24_8_1571 = SLICE((uint64) edx_386, word24, 8);
		if (((byte) (r15_1204 == 0x00) & (byte) edx_386) != 0x00)
		{
			r14_1172 = r12_1142;
			r12_1175 = r10_1174;
			if (bLocD3_4126 != 0x00)
			{
l0000000000003C6B:
				qwLocF0_4078 = null;
				qwLocA0_4083 = __ctype_get_mb_cur_max();
				dwLoc80_4077 = SEQ(nLoc7F_7025, bLoc80_5437 & ~0x02);
l0000000000003C83:
				bpl_325 = 0x01;
				goto l0000000000003C88;
			}
			else
			{
l000000000000467C:
				r12_1175 = r10_1174;
				bpl_325 = 0x00;
				qwLocF0_4078 = null;
				qwLocA0_4083 = __ctype_get_mb_cur_max();
				dwLoc80_4077 = SEQ(nLoc7F_7025, bLoc80_5437 & ~0x02);
				goto l0000000000003C88;
			}
		}
		uint64 rdi_409 = (uint64) (edi_366 ^ 0x01);
		word32 edi_410 = (word32) rdi_409;
		uint64 rdx_412 = (uint64) edi_410;
		uint8 al_414 = al_372 & (byte) rdi_409;
		edx_24_8_1571 = SLICE(rdx_412, word24, 8);
		ui32 eax_421 = SEQ(eax_24_8_1408, al_414);
		word64 rdx_7924 = SEQ(SLICE(rdx_412, word56, 8), (byte) edi_410);
		if (al_414 == 0x00)
		{
l00000000000048BA:
			byte dl_509 = (byte) rdx_7924;
			if (qwLocB0_4102 != null && dl_509 != 0x00)
			{
				byte cl_519 = qwLocB0_4102->u0;
				if (cl_519 != 0x00)
				{
					Eq_1255 rdx_526 = r15_1204;
					int64 rax_527 = qwLocB0_4102 - r15_1204;
					do
					{
						if (r10_1174 > rdx_526)
							*(rdi + rdx_526) = (word64) cl_519;
						rdx_526.u1 = rdx_526 + (char *) 0x01;
						cl_519 = rdx_526.u1[rax_527];
					} while (cl_519 != 0x00);
					r15_1204 = rdx_526;
				}
			}
			if (r10_1174 > r15_1204)
				*(rdi + r15_1204) = (word64) 0x00;
			if (rax_43 == fs->qw0028)
				return r15_1204;
			__stack_chk_fail();
		}
		if (bLoc7C_4124 == 0x00)
		{
			rdx_7924 = SEQ(SLICE((uint64) eax_421, word56, 8), al_414);
			goto l00000000000048BA;
		}
		if (bLocD8_4123 == 0x00)
		{
			bpl_325 = bLocD3_4126;
			ebp_24_8_2604 = SLICE((uint64) bLocD3_4126, word24, 8);
			esi_319 = r11d_486;
			r14_1172 = r12_1142;
			al_3279 = (byte) (r10_1174 == 0x00) & (byte) (qwLocA8_4125 != 0x00);
			if (al_3279 != 0x00)
			{
				r12_1175 = qwLocA8_4125;
l0000000000004509:
				*r13_18.u1 = (char) 0x27;
				bLoc7C_4124 = al_3279;
				eax_24_8_1408 = SLICE(&g_u50DF, word24, 8);
				r15_1204.u0 = 0x01;
				r11d_334 = 0x02;
				bLocD2_4101 = 0x00;
				qwLocE0_4103.u0 = 0x01;
				qwLocB0_4102 = (union Eq_641 *) &g_u50DF;
				goto l00000000000037A1;
			}
			rdx_7924 = SEQ(SLICE((uint64) bLoc7C_4124, word56, 8), bLoc7C_4124);
			goto l00000000000048BA;
		}
		r13d_3661 = 0x05;
		r15_1204.u0 = 0x00;
		qwLocE0_4103.u0 = 0x01;
		qwLocA0_4083 = __ctype_get_mb_cur_max();
		qwLocB0_4102 = (union Eq_641 *) &g_u50DD;
		if ((bLoc80_5437 & 0x02) == 0x00)
		{
			r14_1172 = r12_1142;
			r12_1175 = qwLocA8_4125;
			goto l0000000000003AC0;
		}
		eax_24_8_1408 = SLICE((uint64) bLocD8_4123, word24, 8);
		r10_1174 = qwLocA8_4125;
		bLoc7C_4124 = 0x00;
		r11d_3712 = 0x00;
		qwLocA8_4125.u0 = 0x00;
		bLocD2_4101 = bLocD8_4123;
		bLocD3_4126 = bLocD8_4123;
	}
	uint8 al_596 = (byte) (r13d_3661 != 0x02) & bLocD3_4126;
	ui32 eax_602 = SEQ(eax_24_8_1408, al_596);
	uint64 r8_604 = (uint64) eax_602;
	byte * rbx_601 = rdx + r9_1085;
	uint8 r8b_1701 = al_596;
	ui32 r8d_1004 = eax_602;
	word24 r8d_24_8_1007 = SLICE(r8_604, word24, 8);
	word56 r8_56_8_7367 = SLICE(r8_604, word56, 8);
	ui32 ebx_1039;
	ui32 ebx_7964;
	uint32 ebp_1209;
	uint64 r8_7869;
	uint64 r8_7939;
	uint64 r11_8164;
	ui32 ecx_1369;
	uint64 r8_8035;
	uint64 r11_8105;
	Eq_14 r9_1140;
	uint32 eax_1128;
	uint64 r8_7883;
	uint64 r11_8121;
	ui32 eax_1015;
	uint64 r11_8197;
	uint64 r11_8200;
	uint8 cl_2779;
	uint64 r8_7909;
	uint64 r11_8026;
	uint64 r8_7889;
	byte dl_1559;
	word32 eax_3205;
	uint64 r11_8086;
	uint8 dl_1021;
	uint64 r8_7903;
	uint64 r11_8092;
	uint64 r11_8078;
	byte al_2340;
	uint64 r11_8048;
	uint64 r11_8173;
	if (al_596 != 0x00)
	{
		uint64 r8_7961;
		uint64 r11_8115;
		ui32 ecx_1480;
		uip64 r8_7906;
		ui32 ebx_8045;
		if (qwLocE0_4103 != 0x00)
		{
			Eq_14 rdx_746 = qwLocE0_4103 + r9_1085;
			if (r12_1142 == ~0x00 && qwLocE0_4103 > 0x01)
			{
				r11d_24_8_1090 = SLICE((uint64) r11b_1690, word24, 8);
				r11_32_32_7254 = 0x00;
				r12_1142 = strlen(rdx);
				r8d_24_8_1007 = SLICE((uint64) al_596, word24, 8);
			}
			edx_24_8_1571 = SLICE(rdx_746, word24, 8);
			r8d_1004 = SEQ(r8d_24_8_1007, al_596);
			r11_7920 = SEQ(r11_32_32_7254, r11d_24_8_1090, r11b_1690);
			if (rdx_746 <= r12_1142)
			{
				ui32 r8d_788 = (word32) al_596;
				uint32 r11d_794 = (word32) r11b_1690;
				edx_24_8_1571 = SLICE(qwLocE0_4103, word24, 8);
				r8d_1004 = r8d_788;
				r8b_1701 = al_596;
				r8_56_8_7367 = SLICE((uint64) r8d_788, word56, 8);
				r11_7920 = (uint64) r11d_794;
				if (memcmp(rbx_601, qwLocB0_4102, qwLocE0_4103) == 0x00)
				{
					if (bLocD2_4101 != 0x00)
					{
l0000000000004929:
						r11d_3530 = r13d_3661;
						r14_1172 = r12_1142;
						r12_1175 = r10_1174;
						goto l00000000000039F1;
					}
					ui32 ebx_953 = (word32) *rbx_601;
					char bl_955 = (byte) ebx_953;
					ebx_1039 = ebx_953;
					word24 ebx_24_8_2449 = SLICE((uint64) ebx_953, word24, 8);
					if (bl_955 <= 0x3F)
					{
						ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
						if (bl_955 >= 0x00)
						{
							ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
							if (bl_955 <= 0x3F)
							{
								edx_24_8_1571 = SLICE(g_a5610, word24, 8);
								eax_24_8_1408 = SLICE((char *) g_a5610 + (int64) g_a5610[(uint64) bl_955], word24, 8);
								ebp_1209 = SEQ(ebp_24_8_2604, bpl_2065);
								r8_7869 = SEQ(r8_56_8_7367, al_596);
								r8_7869 = SEQ(r8_56_8_7367, al_596);
								r8_7939 = SEQ(r8_56_8_7367, al_596);
								r8_7961 = SEQ(r8_56_8_7367, al_596);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								r11_8115 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_8164 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								r11_7920 = (uint64) r11d_794;
								switch (bl_955)
								{
								case '\0':
									goto l0000000000003D3E;
								case '\x01':
								case '\x02':
								case '\x03':
								case '\x04':
								case '\x05':
								case '\x06':
								case '\x0E':
								case '\x0F':
								case '\x10':
								case '\x11':
								case '\x12':
								case '\x13':
								case '\x14':
								case '\x15':
								case '\x16':
								case '\x17':
								case '\x18':
								case '\x19':
								case '\x1A':
								case '\x1B':
								case '\x1C':
								case '\x1D':
								case '\x1E':
								case '\x1F':
									break;
								case '\a':
									goto l0000000000003D29;
								case '\b':
									goto l0000000000003CF2;
								case '\t':
									goto l0000000000003DBB;
								case '\n':
									goto l0000000000003D1D;
								case '\v':
									goto l0000000000003DE7;
								case '\f':
									goto l0000000000003CD8;
								case '\r':
									goto l0000000000003C2C;
								case ' ':
									ecx_1480 = r8d_788;
									r11_7920 = (uint64) r11d_794;
									goto l0000000000003DF6;
								case '!':
								case '"':
								case '$':
								case '&':
								case '(':
								case ')':
								case '*':
								case ';':
								case '<':
								case '=':
								case '>':
									goto l00000000000039B5;
								case '#':
									goto l0000000000003D9B;
								case '%':
								case '+':
								case ',':
								case '-':
								case '.':
								case '/':
								case '0':
								case '1':
								case '2':
								case '3':
								case '4':
								case '5':
								case '6':
								case '7':
								case '8':
								case '9':
								case ':':
									ecx_1480 = r8d_788;
									r11_7920 = (uint64) r11d_794;
									goto l00000000000038F0;
								case '\'':
									goto l0000000000003C11;
								case '?':
									goto l0000000000003BC6;
								}
							}
						}
						goto l0000000000003A0B;
					}
					if (bl_955 <= 122)
					{
						ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
						if (bl_955 == 0x40)
							goto l0000000000003A0B;
						ui64 rax_1032 = 0x01 << (byte) ebx_953 - 0x41;
						edx_24_8_1571 = 0x0053FFFF;
						ui32 eax_1042 = (word32) rax_1032;
						ecx_1480 = r8d_788;
						r11_7920 = (uint64) r11d_794;
						if ((rax_1032 & 0x3FFFFFF53FFFFFF) == 0x00)
						{
							ecx_1369 = ebx_953;
							r8_8035 = SEQ(r8_56_8_7367, al_596);
							r11_7920 = (uint64) r11d_794;
							if ((eax_1042 & 0xA4000000) == 0x00)
							{
								r8_7906 = SEQ(r8_56_8_7367, al_596);
								ebx_8045 = SEQ(ebx_24_8_2449, bl_955);
								r11_8105 = (uint64) r11d_794;
								goto l0000000000004322;
							}
							goto l0000000000004270;
						}
l00000000000038F0:
						r9_1140 = r9_1085;
						bpl_2065 = (byte) r8d_1004;
						ebp_24_8_2604 = SLICE((uint64) r8d_1004, word24, 8);
						eax_1128 = 0x00;
						ecx_1369 = ebx_1039;
						r8_7883 = SEQ(SLICE((uint64) ecx_1480, word56, 8), (byte) ecx_1480);
						r11_8121 = r11_7920;
						goto l0000000000003900;
					}
					r11_7920 = (uint64) r11d_794;
					if (bl_955 != 0x7D)
					{
						if (bl_955 > 0x7D)
						{
							eax_1015 = r8d_788;
							r11_7920 = (uint64) r11d_794;
							if (bl_955 != 0x7E)
							{
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								goto l0000000000003A0B;
							}
							goto l000000000000439A;
						}
						ecx_1369 = 0x7B;
						r11_7920 = (uint64) r11d_794;
						if (bl_955 != 0x7B)
						{
							ecx_1369 = 0x7C;
							r8_8035 = SEQ(r8_56_8_7367, al_596);
							r11_7920 = (uint64) r11d_794;
							if (bl_955 != 0x7C)
							{
								ebx_7964 = SEQ(ebx_24_8_2449, bl_955);
								goto l0000000000003A0B;
							}
							goto l0000000000004270;
						}
						goto l000000000000424C;
					}
l00000000000043E0:
					ecx_1369 = 0x7D;
					r11_8197 = r11_7920;
					r11_8200 = r11_7920;
					if (r12_1142 != ~0x00)
						goto l0000000000004260;
					goto l00000000000043EF;
				}
			}
		}
		ui32 ebx_800 = (word32) *rbx_601;
		r11b_1690 = (byte) r11_7920;
		char bl_802 = (byte) ebx_800;
		ebx_1039 = ebx_800;
		word24 ebx_24_8_2451 = SLICE((uint64) ebx_800, word24, 8);
		byte al_3215;
		uint64 r11_8052;
		if (bl_802 <= 0x3F)
		{
			if (bl_802 >= 0x00 && bl_802 <= 0x3F)
			{
				edx_24_8_1571 = SLICE(g_a5810, word24, 8);
				eax_24_8_1408 = SLICE((char *) g_a5810 + (int64) g_a5810[(uint64) bl_802], word24, 8);
				ebp_1209 = SEQ(ebp_24_8_2604, bpl_2065);
				r11_8115 = r11_7920;
				switch (bl_802)
				{
				case '\0':
					goto l0000000000003D30;
				case '\x01':
				case '\x02':
				case '\x03':
				case '\x04':
				case '\x05':
				case '\x06':
				case '\x0E':
				case '\x0F':
				case '\x10':
				case '\x11':
				case '\x12':
				case '\x13':
				case '\x14':
				case '\x15':
				case '\x16':
				case '\x17':
				case '\x18':
				case '\x19':
				case '\x1A':
				case '\x1B':
				case '\x1C':
				case '\x1D':
				case '\x1E':
				case '\x1F':
					goto l0000000000003A08;
				case '\a':
l0000000000003D29:
					cl_2779 = 0x61;
					uint64 r11_8118 = r11_7920;
					goto l0000000000003CDD;
				case '\b':
l0000000000003CF2:
					cl_2779 = 0x62;
					ui32 eax_1648 = SEQ(eax_24_8_1408, (byte) (r13d_3661 == 0x02));
					uint64 r11_8089 = r11_8115;
					if (bLocD2_4101 != 0x00)
						goto l0000000000003D05;
					goto l0000000000003CEB;
				case '\t':
					r8_7961 = 0x00;
l0000000000003DBB:
					ecx_1369 = 0x09;
					ebx_1039 = 116;
					r8_7909 = r8_7961;
					goto l0000000000003DC8;
				case '\n':
l0000000000003D1D:
					cl_2779 = 110;
					r11_8105 = r11_7920;
					break;
				case '\v':
l0000000000003DE7:
					cl_2779 = 118;
					r11_8105 = r11_7920;
					break;
				case '\f':
l0000000000003CD8:
					cl_2779 = 0x66;
					r11_8118 = r11_7920;
l0000000000003CDD:
					eax_1648 = SEQ(eax_24_8_1408, (byte) (r13d_3661 == 0x02));
					r11_8089 = r11_8118;
					if (bLocD2_4101 != 0x00)
					{
l0000000000003D05:
						r14_1172 = r12_1142;
						r12_1175 = r10_1174;
						al_3215 = (byte) eax_1648 & bLocD2_4101;
l0000000000003C63:
						r11d_3530 = r13d_3661;
						if (al_3215 != 0x00)
							goto l0000000000003C6B;
						goto l00000000000039F1;
					}
					else
					{
l0000000000003CEB:
						r9_1140 = r9_1085;
						bpl_2065 = 0x00;
						ebp_24_8_2604 = 0x00;
						r11_8052 = r11_8089;
l0000000000003972:
						if (r15_1204 < r10_1174)
							*(r13_18 + r15_1204) = (word64) 0x5C;
						r15_1204.u0 = (word128) r15_1204 + 1;
						r9_1085 = (word64) r9_1140 + 1;
						r11_8026 = r11_8052;
l0000000000003984:
						if (r15_1204 < r10_1174)
							*(r13_18 + r15_1204) = (word64) cl_2779;
						byte al_3525 = bLocD8_4123;
						eax_24_8_1408 = SLICE((uint64) bLocD8_4123, word24, 8);
						r15_1204.u0 = (word128) r15_1204 + 1;
						if (bpl_2065 == 0x00)
						{
							al_3525 = 0x00;
							eax_24_8_1408 = 0x00;
						}
						bLocD8_4123 = al_3525;
						r11_7920 = r11_8026;
						goto l00000000000037C0;
					}
				case '\r':
l0000000000003C2C:
					cl_2779 = 114;
					r11_8105 = r11_7920;
					break;
				case ' ':
					ecx_1480 = 0x00;
l0000000000003DF6:
					ebx_1039 = 0x20;
					goto l00000000000038F0;
				case '!':
				case '"':
				case '$':
				case '&':
				case '(':
				case ')':
				case '*':
				case ';':
				case '<':
				case '=':
				case '>':
					bpl_2065 = 0x00;
					ebp_24_8_2604 = 0x00;
					r8_7889 = 0x00;
					goto l00000000000039B7;
				case '#':
					r8d_1004 = 0x00;
					ecx_1369 = 0x23;
					goto l0000000000003DA0;
				case '%':
				case '+':
				case ',':
				case '-':
				case '.':
				case '/':
				case '0':
				case '1':
				case '2':
				case '3':
				case '4':
				case '5':
				case '6':
				case '7':
				case '8':
				case '9':
				case ':':
					ecx_1480 = 0x00;
					goto l00000000000038F0;
				case '\'':
					r8_7869 = 0x00;
					goto l0000000000003C11;
				case '?':
					r8_7869 = 0x00;
					goto l0000000000003BC6;
				}
				goto l0000000000003C33;
			}
			goto l0000000000003A08;
		}
		if (bl_802 <= 122)
		{
			if (bl_802 != 0x40)
			{
				ui64 rax_840 = 0x01 << (byte) ebx_800 - 0x41;
				edx_24_8_1571 = 0x0053FFFF;
				ui32 eax_852 = (word32) rax_840;
				ecx_1480 = 0x00;
				if ((rax_840 & 0x3FFFFFF53FFFFFF) != 0x00)
					goto l00000000000038F0;
				ecx_1369 = ebx_800;
				r8_7906 = 0x00;
				r8_8035 = 0x00;
				ebx_8045 = SEQ(ebx_24_8_2451, bl_802);
				r11_8105 = r11_7920;
				if ((eax_852 & 0xA4000000) == 0x00)
				{
l0000000000004322:
					r8b_1701 = (byte) r8_7906;
					edx_24_8_1571 = 0x0053FFFF;
					r11b_1690 = (byte) r11_8105;
					ebx_7964 = ebx_8045;
					if ((byte) ebx_8045 == 0x5C)
					{
						if ((bLocD3_4126 & bLocD2_4101) != 0x00)
						{
							r11_7920 = r11_8105;
							if (qwLocE0_4103 != 0x00)
								goto l0000000000004347;
						}
						cl_2779 = 0x5C;
l0000000000003C33:
						dl_1559 = (byte) (r13d_3661 == 0x02);
						ebp_24_8_2604 = 0x00;
						bpl_2065 = 0x00;
						r9_1140 = r9_1085;
						eax_3205 = SEQ(edx_24_8_1571, dl_1559);
						r11_8086 = r11_8105;
						if (bLocD2_4101 == 0x00)
						{
l0000000000003939:
							word32 r11d_3299 = (word32) r11_8086;
							byte al_3313 = ((byte) r11d_3299 ^ 0x01) & dl_1559;
							uint32 eax_3351 = SEQ(SLICE((uint64) (r11d_3299 ^ 0x01), word24, 8), al_3313);
							r11_8052 = r11_8086;
							if (al_3313 != 0x00)
							{
								if (r10_1174 > r15_1204)
									*(r13_18 + r15_1204) = (word64) 0x27;
								if (r10_1174 > (word128) r15_1204 + 1)
									r15_1204.u1[r13_18 + (char *) 1] = (char) 0x24;
								Eq_1255 rdx_3338;
								rdx_3338.u1 = r15_1204 + (uint8 *) 2;
								edx_24_8_1571 = SLICE(rdx_3338, word24, 8);
								if (r10_1174 > rdx_3338)
									r15_1204.u1[r13_18 + (char *) 2] = (char) 0x27;
								r15_1204.u1 = r15_1204 + (char *) 0x03;
								r11_8052 = (uint64) eax_3351;
							}
							goto l0000000000003972;
						}
l0000000000003C50:
						r14_1172 = r12_1142;
						r12_1175 = r10_1174;
						al_3215 = (byte) eax_3205 & bLocD3_4126;
						goto l0000000000003C63;
					}
					goto l0000000000003A0B;
				}
				goto l0000000000004270;
			}
			goto l0000000000003A08;
		}
		if (bl_802 == 0x7D)
		{
			r8d_1004 = 0x00;
			ecx_1369 = 0x7D;
			goto l000000000000424C;
		}
		if (bl_802 > 0x7D)
		{
			eax_1015 = 0x00;
			if (bl_802 == 0x7E)
			{
l000000000000439A:
				if (r9_1085 == 0x00)
				{
					bpl_2065 = (byte) r8d_1004;
					ebp_24_8_2604 = SLICE((uint64) r8d_1004, word24, 8);
					ecx_1369 = 0x7E;
					dl_1021 = (byte) (r13d_3661 == 0x02);
					r8_7869 = SEQ(SLICE((uint64) eax_1015, word56, 8), (byte) eax_1015);
l0000000000003A81:
					uint64 rax_2475 = (uint64) ((word32) bLocD3_4126 ^ 0x01);
					byte al_2483 = (byte) rax_2475 | dl_1021;
					r9_1140 = r9_1085;
					cl_2779 = (byte) ecx_1369;
					eax_1128 = SEQ(SLICE(rax_2475, word24, 8), al_2483);
					r8_7883 = r8_7869;
					r11_8121 = r11_7920;
					if (al_2483 == 0x00)
						goto l0000000000003900;
					eax_1128 = 0x00;
					r8_7883 = r8_7869;
					r11_8121 = r11_7920;
					if (bLocD2_4101 != 0x00)
						goto l0000000000003900;
					r8_7903 = r8_7869;
					r11_8092 = r11_7920;
l0000000000003AA0:
					r9_1140 = r9_1085;
					eax_1128 = 0x00;
					r11_8078 = r11_8092;
					if ((byte) r8_7903 == 0x00)
					{
l0000000000003AA9:
						r9_1085 = (word64) r9_1140 + 1;
						al_2340 = ((byte) eax_1128 ^ 0x01) & (byte) r11_8078;
						r11_8048 = r11_8078;
						goto l0000000000004358;
					}
					goto l0000000000003925;
				}
				ecx_1369 = 0x7E;
				r11_8173 = r11_7920;
l00000000000043A8:
				dl_1021 = (byte) (r13d_3661 == 0x02);
				bpl_2065 = 0x00;
				ebp_24_8_2604 = 0x00;
				r8_7869 = SEQ(SLICE((uint64) eax_1015, word56, 8), (byte) eax_1015);
				r11_7920 = r11_8173;
				goto l0000000000003A81;
			}
l0000000000003A08:
			r8b_1701 = 0x00;
			ebx_7964 = SEQ(ebx_24_8_2451, bl_802);
			goto l0000000000003A0B;
		}
		r8d_1004 = 0x00;
		r8b_1701 = 0x00;
		ecx_1369 = 0x7B;
		if (bl_802 == 0x7B)
			goto l000000000000424C;
		ecx_1369 = 0x7C;
		r8_8035 = 0x00;
		if (bl_802 == 0x7C)
		{
l0000000000004270:
			dl_1021 = (byte) (r13d_3661 == 0x02);
			bpl_2065 = 0x00;
			ebp_24_8_2604 = 0x00;
			r8_7869 = r8_8035;
			goto l0000000000003A81;
		}
		ebx_7964 = SEQ(ebx_24_8_2451, bl_802);
		goto l0000000000003A0B;
	}
	ui32 ebx_606 = (word32) *rbx_601;
	char bl_1763 = (byte) ebx_606;
	ebx_1039 = ebx_606;
	word24 ebx_24_8_2453 = SLICE((uint64) ebx_606, word24, 8);
	uint64 r8_8042;
	ui32 ebx_7917;
	if (bl_1763 > 0x3F)
	{
		uint64 r11_8169;
		byte al_2140;
		if (bl_1763 <= 122)
		{
			ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
			if (bl_1763 == 0x40)
				goto l0000000000003A0B;
			ui64 rax_636 = 0x01 << (byte) ebx_606 - 0x41;
			edx_24_8_1571 = 0x0053FFFF;
			ui32 eax_641 = (word32) rax_636;
			eax_24_8_1408 = SLICE(rax_636, word24, 8);
			r8_8042 = SEQ(r8_56_8_7367, al_596);
			if ((rax_636 & 0x3FFFFFF53FFFFFF) != 0x00)
			{
l0000000000003A78:
				dl_1021 = (byte) (r13d_3661 == 0x02);
				r8_7889 = r8_8042;
				r11_8169 = r11_7920;
				goto l0000000000003A7F;
			}
			if ((eax_641 & 0xA4000000) == 0x00)
			{
				ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
				if (bl_1763 != 0x5C)
					goto l0000000000003A0B;
				if (r13d_3661 != 0x02)
				{
					edx_24_8_1571 = SLICE((uint64) bLocD3_4126, word24, 8);
					byte dl_659 = bLocD3_4126 & bLocD2_4101 & (byte) (qwLocE0_4103 != 0x00);
					word56 r8_56_8_7429 = SLICE((uint64) SEQ(edx_24_8_1571, dl_659), word56, 8);
					if (dl_659 == 0x00)
					{
						ecx_1369 = 0x5C;
						r8_7909 = SEQ(r8_56_8_7429, dl_659);
						goto l0000000000003DC8;
					}
				}
				else if (bLocD2_4101 != 0x00)
				{
l000000000000454B:
					r11d_3530 = r13d_3661;
					r14_1172 = r12_1142;
					al_2140 = bLocD3_4126;
					goto l00000000000039E9;
				}
l0000000000004347:
				r9_1085 = (word64) r9_1085 + 1;
				al_2340 = (byte) r11_7920;
				bpl_2065 = 0x00;
				ebp_24_8_2604 = 0x00;
				cl_2779 = 0x5C;
				r11_8048 = r11_7920;
				goto l0000000000004358;
			}
		}
		else
		{
			if (bl_1763 == 0x7D)
				goto l00000000000043E0;
			if (bl_1763 > 0x7D)
			{
				ecx_1369 = 0x7E;
				if (bl_1763 != 0x7E)
				{
					ebx_7917 = SEQ(ebx_24_8_2453, bl_1763);
					Eq_2062 rdi_1823;
					uint32 r11d_2886;
					byte dl_2067;
					if (qwLocA0_4083 == 0x01)
					{
l0000000000003A20:
						struct Eq_2860 * rdx_2062 = (struct Eq_2860 *) *__ctype_b_loc();
						uint64 rax_2058 = (uint64) (byte) ebx_7917;
						rdi_1823.u0 = 0x01;
						r11d_2886 = (word32) r11b_1690;
						edx_24_8_1571 = SLICE(rdx_2062, word24, 8);
						bpl_2065 = (byte) ((rdx_2062->a0001[rax_2058].b0000 & 0x40) != 0x00);
						dl_2067 = (byte) ((rdx_2062->a0001[rax_2058].b0000 & 0x40) == 0x00) & bLocD3_4126;
						ebx_1039 = ebx_7917;
						r8_8042 = SEQ(SLICE((uint64) r8b_1701, word56, 8), r8b_1701);
						goto l0000000000003A6D;
					}
l0000000000003F79:
					if (r12_1142 == ~0x00)
						r12_1142 = strlen(rdx);
					byte bLocD1_4312 = bpl_2065;
					Eq_2062 rbx_1767;
					rbx_1767.u0 = 0x00;
					ptr64 fp;
					word56 r8_56_8_7389;
					word32 edx_7949;
					do
					{
						Eq_14 r15_1776 = r9_1085 + rbx_1767;
						Eq_14 rbp_1778 = r12_1142 - r15_1776;
						char * r13_1779 = rdx + r15_1776;
						Eq_14 rax_1782 = mbrtowc(fp - 0x4C, r13_1779, rbp_1778, fp - 0x48);
						Eq_14 r12_1783 = rax_1782;
						uint64 rdi_1814;
						word32 dwLoc4C;
						if (rax_1782 > ~0x02 && rbp_1778 != 0x00)
						{
							if (fn0000000000003570(fs) == 0x00)
							{
								word32 edi_1813 = (word32) *r13_1779;
								rdi_1814 = (uint64) edi_1813;
								r12_1783.u0 = 0x01;
								dwLoc4C = edi_1813;
								goto l0000000000004097;
							}
							if (rax_1782 != ~0x00)
								goto l0000000000004074;
l00000000000045D3:
							rdi_1823 = rbx_1767;
							r8_56_8_7389 = SLICE((uint64) r8b_1701, word56, 8);
							bpl_2065 = 0x00;
							ebp_24_8_2604 = 0x00;
							r11d_2886 = (word32) r11b_1690;
							ebx_1039 = (word32) bl_1763;
							edx_7949 = SEQ(SLICE((uint64) bLocD3_4126, word24, 8), bLocD3_4126);
							goto l0000000000004105;
						}
						if (rax_1782 == 0x00)
							break;
						if (rax_1782 == ~0x00)
							goto l00000000000045D3;
l0000000000004074:
						if (rax_1782 == ~0x01)
						{
							rdi_1823 = rbx_1767;
							Eq_14 rax_1859 = r15_1776;
							r8_56_8_7389 = SLICE((uint64) r8b_1701, word56, 8);
							ebx_1039 = (word32) bl_1763;
							Eq_2062 rdx_1865 = rbx_1767;
							r11d_2886 = (word32) r11b_1690;
							if (r15_1776 < r12_1142)
							{
								while (*(rdx + rax_1859) != 0x00)
								{
									rdx_1865 = (word64) rdx_1865 + 1;
									rax_1859 = r9_1085 + rdx_1865;
									if (r12_1142 <= rax_1859)
										break;
								}
								rdi_1823 = rdx_1865;
							}
							bpl_2065 = 0x00;
							ebp_24_8_2604 = 0x00;
							edx_7949 = SEQ(SLICE((uint64) bLocD3_4126, word24, 8), bLocD3_4126);
							goto l0000000000004105;
						}
						if (r13d_3661 == 0x02 && (bLocD2_4101 != 0x00 && rax_1782 > 0x01))
						{
							byte * rdx_1911 = rdx->a0001 + r15_1776;
							byte * rsi_1912 = rdx + r15_1776;
							do
							{
								uint64 rax_1920 = (uint64) ((word32) *rdx_1911 - 0x5B);
								edx_24_8_1571 = SLICE(rdx_1911, word24, 8);
								if ((byte) rax_1920 <= 33 && !__bt<word64>(0x20000002B, rax_1920))
								{
									r14_1172 = r12_1142;
									r12_1175 = r10_1174;
									if (bLocD3_4126 != 0x00)
										goto l0000000000003C6B;
									goto l000000000000467C;
								}
								++rdx_1911;
							} while (rsi_1912 != rdx_1911);
						}
						rdi_1814 = (uint64) dwLoc4C;
l0000000000004097:
						byte al_1996 = bLocD1_4312;
						if (iswprint((wint_t) rdi_1814) == 0x00)
							al_1996 = 0x00;
						rbx_1767 += r12_1783;
						bLocD1_4312 = al_1996;
					} while (mbsinit(fp - 0x48) == 0x00);
					word32 ebp_2008 = (word32) bLocD1_4312;
					uint64 rdx_2027 = (uint64) (ebp_2008 ^ 0x01);
					bpl_2065 = bLocD1_4312;
					ebp_24_8_2604 = SLICE((uint64) ebp_2008, word24, 8);
					rdi_1823 = rbx_1767;
					r8_56_8_7389 = SLICE((uint64) r8b_1701, word56, 8);
					r11d_2886 = (word32) r11b_1690;
					ebx_1039 = (word32) bl_1763;
					edx_7949 = SEQ(SLICE(rdx_2027, word24, 8), (byte) rdx_2027 & bLocD3_4126);
l0000000000004105:
					edx_24_8_1571 = SLICE(edx_7949, word24, 8);
					dl_2067 = (byte) edx_7949;
					word32 edx_7894 = edx_7949;
					uint64 r8_7955 = SEQ(r8_56_8_7389, r8b_1701);
					r8_8042 = SEQ(r8_56_8_7389, r8b_1701);
					if (rdi_1823 > 0x01)
					{
l000000000000410F:
						word24 edx_24_8_3909 = SLICE(edx_7894, word24, 8);
						byte dl_3850 = (byte) edx_7894;
						Eq_14 rcx_2112 = rdi_1823 + r9_1085;
						uip32 esi_7897 = 0x00;
						uint64 r8_7900 = r8_7955;
						uint64 r11_8056 = (uint64) r11d_2886;
l00000000000041E1:
						byte r8b_2311 = (byte) r8_7900;
						edx_24_8_1571 = edx_24_8_3909;
						uint8 bl_2383 = (byte) ebx_1039;
						word32 r11d_2148 = (word32) r11_8056;
						edx_24_8_1571 = edx_24_8_3909;
						if (dl_3850 == 0x00)
						{
							al_2340 = ((byte) esi_7897 ^ 0x01) & (byte) r11d_2148;
							if (r8b_2311 != 0x00)
							{
								if (r10_1174 > r15_1204)
									*(r13_18 + r15_1204) = (word64) 0x5C;
								r15_1204.u1 = r15_1204 + (char *) 0x01;
							}
							r9_1085 = (word64) r9_1085 + 1;
							if (rcx_2112 > r9_1085)
							{
								if (al_2340 != 0x00)
								{
									if (r10_1174 > r15_1204)
										*(r13_18 + r15_1204) = (word64) 0x27;
									if (r10_1174 > r15_1204 + (char *) 1)
										r15_1204.u1[r13_18 + (char *) 1] = (char) 0x27;
									r15_1204.u1 = r15_1204 + (char *) 0x02;
									r8_7900 = 0x00;
									r11_8056 = 0x00;
								}
								else
									r8_7900 = 0x00;
								goto l00000000000041CF;
							}
							ebp_24_8_2604 = SLICE((uint64) bpl_2065, word24, 8);
							cl_2779 = (byte) ebx_1039;
							r11_8048 = r11_8056;
l0000000000004358:
							r11_8026 = r11_8048;
							if (al_2340 != 0x00)
							{
								if (r10_1174 > r15_1204)
									*(r13_18 + r15_1204) = (word64) 0x27;
								if (r10_1174 > (word128) r15_1204 + 1)
									r15_1204.u1[r13_18 + (char *) 1] = 0x27;
								r15_1204.u0 = (word128) r15_1204 + 2;
								r11_8026 = 0x00;
							}
							goto l0000000000003984;
						}
						byte sil_2122 = (byte) (r13d_3661 == 0x02);
						al_2140 = sil_2122;
						if (bLocD2_4101 == 0x00)
						{
							byte al_2155 = ((byte) r11d_2148 ^ 0x01) & sil_2122;
							uint32 eax_2185 = SEQ(SLICE((uint64) (r11d_2148 ^ 0x01), word24, 8), al_2155);
							if (al_2155 != 0x00)
							{
								if (r10_1174 > r15_1204)
									*(r13_18 + r15_1204) = (word64) 0x27;
								if (r10_1174 > r15_1204 + (char *) 1)
									r15_1204.u1[r13_18 + (char *) 1] = (char) 0x24;
								if (r10_1174 > r15_1204 + (char *) 2)
									r15_1204.u1[r13_18 + (char *) 2] = (char) 0x27;
								r15_1204.u1 = r15_1204 + (char *) 0x03;
								r11_8056 = (uint64) eax_2185;
							}
							if (r10_1174 > r15_1204)
								*(r13_18 + r15_1204) = (word64) 0x5C;
							if (r10_1174 > r15_1204 + (char *) 1)
								r15_1204.u1[r13_18 + (char *) 1] = (char) (((byte) ebx_1039 >> 0x06) + 0x30);
							if (r10_1174 > r15_1204 + (char *) 2)
								r15_1204.u1[r13_18 + (char *) 2] = (char) (((byte) ebx_1039 >> 0x03 & 0x07) + 0x30);
							uint64 rbx_2258 = (uint64) ((ebx_1039 & 0x07) + 0x30);
							r9_1085 = (word64) r9_1085 + 1;
							r15_1204.u1 = r15_1204 + (char *) 0x03;
							word32 ebx_2287 = (word32) rbx_2258;
							bl_2383 = (byte) rbx_2258;
							if (rcx_2112 <= r9_1085)
							{
								ebp_24_8_2604 = SLICE((uint64) bpl_2065, word24, 8);
								cl_2779 = (byte) ebx_2287;
								r11_8026 = r11_8056;
								goto l0000000000003984;
							}
							esi_7897 = SEQ(SLICE((uint64) edx_7894, word24, 8), dl_3850);
l00000000000041CF:
							if (r10_1174 > r15_1204)
								*(r13_18 + r15_1204) = (word64) bl_2383;
							ebx_1039 = (word32) *(rdx + r9_1085);
							r15_1204.u1 = r15_1204 + (char *) 0x01;
							goto l00000000000041E1;
						}
						r11d_3530 = r13d_3661;
						r14_1172 = r12_1142;
l00000000000039E9:
						r12_1175 = r10_1174;
						if (al_2140 != 0x00)
							goto l0000000000003C6B;
						goto l00000000000039F1;
					}
l0000000000003A6D:
					if (dl_2067 == 0x00)
					{
						r11_7920 = (uint64) r11d_2886;
						goto l0000000000003A78;
					}
					bpl_2065 = 0x00;
					edx_7894 = SEQ(SLICE((uint64) bLocD3_4126, word24, 8), bLocD3_4126);
					r8_7955 = r8_8042;
					goto l000000000000410F;
				}
				goto l0000000000003DA0;
			}
			ecx_1369 = 0x7B;
			if (bl_1763 == 0x7B)
			{
l000000000000424C:
				r11_8197 = r11_7920;
				if (r12_1142 != ~0x00)
				{
					r11_8200 = r11_7920;
l0000000000004260:
					uint8 r8b_2517 = (byte) r8d_1004;
					uint56 r8_56_8_7405 = (uint56) SLICE(r8d_1004, word24, 8);
					r11_7920 = r11_8200;
					if (r12_1142 != 0x01)
					{
						r8_8035 = SEQ(r8_56_8_7405, r8b_2517);
						r11_7920 = r11_8200;
						goto l0000000000004270;
					}
					goto l0000000000003DA0;
				}
l00000000000043EF:
				r8_8035 = SEQ((uint56) SLICE(r8d_1004, word24, 8), (byte) r8d_1004);
				r11_7920 = r11_8197;
				if (rdx->a0001[0] != 0x00)
					goto l0000000000004270;
				r11_7920 = r11_8197;
l0000000000003DA0:
				byte r8b_2498 = (byte) r8d_1004;
				eax_1015 = r8d_1004;
				eax_24_8_1408 = SLICE((uint64) r8d_1004, word24, 8);
				uint56 r8_56_8_7384 = (uint56) SLICE(r8d_1004, word24, 8);
				r11_8173 = r11_7920;
				if (r9_1085 != 0x00)
					goto l00000000000043A8;
				ebx_1039 = ecx_1369;
				r8_7889 = SEQ(r8_56_8_7384, r8b_2498);
l00000000000039B7:
				uint8 al_1394 = (byte) (r13d_3661 == 0x02);
				dl_1021 = al_1394;
				edx_24_8_1571 = SLICE((uint64) SEQ(eax_24_8_1408, al_1394), word24, 8);
				r11_8169 = r11_7920;
				if (bLocD2_4101 == 0x00)
					goto l0000000000003A7F;
				r11_8169 = r11_7920;
				if (al_1394 == 0x00)
				{
l0000000000003A7F:
					ecx_1369 = ebx_1039;
					r8_7869 = r8_7889;
					r11_7920 = r11_8169;
					goto l0000000000003A81;
				}
l00000000000039D3:
				r11d_3530 = 0x02;
				r14_1172 = r12_1142;
				al_2140 = bLocD3_4126;
				goto l00000000000039E9;
			}
			ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
			if (bl_1763 != 0x7C)
				goto l0000000000003A0B;
		}
l00000000000039B5:
		bpl_2065 = 0x00;
		ebp_24_8_2604 = 0x00;
		r8_7889 = SEQ(r8_56_8_7367, al_596);
		goto l00000000000039B7;
	}
	else
	{
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		if (bl_1763 < 0x00)
			goto l0000000000003A0B;
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		if (bl_1763 > 0x3F)
		{
l0000000000003A0B:
			bl_1763 = (byte) ebx_7964;
			if (qwLocA0_4083 == 0x01)
			{
				ebx_7917 = ebx_7964;
				goto l0000000000003A20;
			}
			goto l0000000000003F79;
		}
		edx_24_8_1571 = SLICE(g_a5710, word24, 8);
		eax_24_8_1408 = SLICE((char *) g_a5710 + (int64) g_a5710[(uint64) bl_1763], word24, 8);
		ebp_1209 = SEQ(ebp_24_8_2604, bpl_2065);
		r8_7869 = SEQ(r8_56_8_7367, al_596);
		r8_7869 = SEQ(r8_56_8_7367, al_596);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		ebx_7964 = SEQ(ebx_24_8_2453, bl_1763);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		r8_8042 = SEQ(r8_56_8_7367, al_596);
		switch (bl_1763)
		{
		case '\0':
			byte dl_2537;
			if (bLocD3_4126 != 0x00)
			{
l0000000000003D30:
				if (bLocD2_4101 == 0x00)
				{
					r8_7939 = 0x00;
					r11_8164 = r11_7920;
l0000000000003D3E:
					uint32 r11d_2532 = (word32) r11_8164;
					dl_2537 = (byte) (r13d_3661 == 0x02);
					byte al_2542 = ((byte) r11d_2532 ^ 0x01) & dl_2537;
					r9_1140 = r9_1085;
					eax_1128 = SEQ(SLICE((uint64) (r11d_2532 ^ 0x01), word24, 8), al_2542);
					Eq_1255 rsi_2549;
					uint64 r11_8134;
					if (al_2542 != 0x00)
					{
						if (r10_1174 > r15_1204)
							*(r13_18 + r15_1204) = (word64) 0x27;
						if (r10_1174 > r15_1204 + (char *) 1)
							r15_1204.u1[r13_18 + (char *) 1] = (char) 0x24;
						if (r10_1174 > r15_1204 + (char *) 2)
							r15_1204.u1[r13_18 + (char *) 2] = (char) 0x27;
						rsi_2549.u1 = r15_1204 + (char *) 3;
						if (r10_1174 <= rsi_2549)
						{
							r15_1204.u1 = r15_1204 + (char *) 0x04;
							bpl_2065 = 0x00;
							ebp_24_8_2604 = 0x00;
							cl_2779 = 0x30;
							r8_7869 = r8_7939;
							r11_8092 = (uint64) eax_1128;
							goto l000000000000391C;
						}
					}
					else
					{
						rsi_2549 = r15_1204;
						r11_8134 = r11_8164;
						if (r10_1174 <= r15_1204)
							goto l00000000000046B3;
						eax_1128 = r11d_2532;
					}
					*(r13_18 + rsi_2549) = (word64) 0x5C;
					r11_8134 = (uint64) eax_1128;
l00000000000046B3:
					r15_1204.u1 = rsi_2549 + (char *) 1;
					if (r13d_3661 == 0x02)
					{
						eax_1128 = ebp_1209;
						cl_2779 = 0x30;
						bpl_2065 = 0x00;
						ebp_24_8_2604 = 0x00;
						r8_7869 = r8_7939;
						r11_8092 = r11_8134;
						goto l000000000000391C;
					}
					ecx_1369 = 0x30;
					r8_7869 = r8_7939;
					r11_7920 = r11_8134;
					if ((word64) r9_1085 + 1 < r12_1142)
					{
						r8_7869 = r8_7939;
						r11_7920 = r11_8134;
						if (*(rdx->a0001 + r9_1085) <= 0x39)
						{
							if (r10_1174 > r15_1204)
								*(r13_18 + r15_1204) = (word64) 0x30;
							if (r10_1174 > rsi_2549 + (char *) 2)
								rsi_2549.u1[r13_18 + (char *) 2] = (char) 0x30;
							r15_1204.u1 = rsi_2549 + (char *) 3;
							ecx_1369 = 0x30;
							r8_7869 = r8_7939;
							r11_7920 = r11_8134;
						}
					}
l00000000000046E9:
					cl_2779 = (byte) ecx_1369;
					eax_1128 = ebp_1209;
					bpl_2065 = 0x00;
					ebp_24_8_2604 = 0x00;
					r8_7883 = r8_7869;
					r11_8121 = r11_7920;
					if ((bLocD3_4126 ^ 0x01 | dl_2537) != 0x00)
					{
						r11_8092 = r11_7920;
						goto l000000000000391C;
					}
					goto l0000000000003900;
				}
				r11d_3530 = r13d_3661;
				r14_1172 = r12_1142;
				r12_1175 = r10_1174;
				if (r13d_3661 != 0x02)
				{
l00000000000039F1:
					dwLoc80_4077 &= ~0x02;
					qwLocF0_4078 = null;
					goto l00000000000036B0;
				}
				goto l0000000000003C6B;
			}
			else
			{
				ecx_1369 = 0x00;
				r8_7909 = 0x00;
				if ((bLoc80_5437 & 0x01) == 0x00)
					goto l0000000000003DD3;
				r9_1085 = (word64) r9_1085 + 1;
				goto l00000000000037C0;
			}
		case '\x01':
		case '\x02':
		case '\x03':
		case '\x04':
		case '\x05':
		case '\x06':
		case '\x0E':
		case '\x0F':
		case '\x10':
		case '\x11':
		case '\x12':
		case '\x13':
		case '\x14':
		case '\x15':
		case '\x16':
		case '\x17':
		case '\x18':
		case '\x19':
		case '\x1A':
		case '\x1B':
		case '\x1C':
		case '\x1D':
		case '\x1E':
		case '\x1F':
			goto l0000000000003A0B;
		case '\a':
			ecx_1369 = 0x07;
			ebx_1039 = 0x61;
			r8_7909 = SEQ(r8_56_8_7367, al_596);
			break;
		case '\b':
			ecx_1369 = 0x08;
			ebx_1039 = 0x62;
			r8_7909 = SEQ(r8_56_8_7367, al_596);
			break;
		case '\t':
			ecx_1369 = 0x09;
			ebx_1039 = 116;
			goto l0000000000003E47;
		case '\n':
			ecx_1369 = 0x0A;
			ebx_1039 = 110;
			goto l0000000000003E47;
		case '\v':
			ecx_1369 = 11;
			ebx_1039 = 118;
			r8_7909 = SEQ(r8_56_8_7367, al_596);
			break;
		case '\f':
			ecx_1369 = 0x0C;
			ebx_1039 = 0x66;
			r8_7909 = SEQ(r8_56_8_7367, al_596);
			break;
		case '\r':
			ecx_1369 = 0x0D;
			ebx_1039 = 114;
l0000000000003E47:
			uint8 al_711 = (byte) (r13d_3661 == 0x02) & bLocD2_4101;
			r8_7909 = SEQ(SLICE((uint64) SEQ(eax_24_8_1408, al_711), word56, 8), al_711);
			if (al_711 != 0x00)
				goto l00000000000039D3;
			break;
		case ' ':
			ebx_1039 = 0x20;
			r8_7889 = SEQ(r8_56_8_7367, al_596);
			goto l00000000000039B7;
		case '!':
		case '"':
		case '$':
		case '&':
		case '(':
		case ')':
		case '*':
		case ';':
		case '<':
		case '=':
		case '>':
			goto l00000000000039B5;
		case '#':
l0000000000003D9B:
			ecx_1369 = 0x23;
			goto l0000000000003DA0;
		case '%':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
			goto l0000000000003A78;
		case '\'':
l0000000000003C11:
			r9_1140 = r9_1085;
			if (r13d_3661 != 0x02)
			{
				bLoc7C_4124 = bpl_2065;
				dl_1021 = 0x00;
				edx_24_8_1571 = 0x00;
				ecx_1369 = 0x27;
				goto l0000000000003A81;
			}
			if (bLocD2_4101 == 0x00)
			{
				if (r10_1174 != 0x00 && qwLocA8_4125 == 0x00)
				{
					qwLocA8_4125 = r10_1174;
					r10_1174.u0 = 0x00;
				}
				else
				{
					if (r10_1174 > r15_1204)
						*(r13_18 + r15_1204) = (word64) 0x27;
					if (r10_1174 > r15_1204 + (char *) 1)
						r15_1204.u1[r13_18 + (char *) 1] = (char) 0x5C;
					if (r10_1174 > r15_1204 + (char *) 2)
						r15_1204.u1[r13_18 + (char *) 2] = (char) 0x27;
				}
				bLoc7C_4124 = bpl_2065;
				r15_1204.u1 = r15_1204 + (char *) 0x03;
				eax_1128 = 0x00;
				cl_2779 = 0x27;
				r11_8092 = 0x00;
				goto l000000000000391C;
			}
			goto l000000000000454B;
		case '?':
l0000000000003BC6:
			r9_1140 = r9_1085;
			if (r13d_3661 == 0x02)
			{
				if (bLocD2_4101 == 0x00)
				{
					bpl_2065 = 0x00;
					ebp_24_8_2604 = 0x00;
					eax_1128 = 0x00;
					cl_2779 = 0x3F;
					r11_8092 = r11_7920;
					goto l000000000000391C;
				}
				goto l000000000000454B;
			}
			if (r13d_3661 == 0x05 && (bLoc80_5437 & 0x04) != 0x00)
			{
				Eq_14 rax_1141 = (word64) r9_1085 + 2;
				if (rax_1141 < r12_1142 && *(rdx->a0001 + r9_1085) == 0x3F)
				{
					ui32 ecx_1148 = (word32) *(rdx + rax_1141);
					cu8 cl_1150 = (byte) ecx_1148;
					ecx_1369 = ecx_1148;
					if (cl_1150 <= 0x3E)
					{
						uint64 rdx_1157 = (uint64) ((word32) (0x7000A38200000000 >> cl_1150) & 0x01);
						dl_1021 = (byte) rdx_1157;
						edx_24_8_1571 = SLICE(rdx_1157, word24, 8);
						if ((word32) rdx_1157 != 0x00)
						{
							if (bLocD2_4101 == 0x00)
							{
								if (r10_1174 > r15_1204)
									*(r13_18 + r15_1204) = (word64) 0x3F;
								if (r10_1174 > r15_1204 + (char *) 1)
									r15_1204.u1[r13_18 + (char *) 1] = (char) 0x22;
								if (r10_1174 > r15_1204 + (char *) 2)
									r15_1204.u1[r13_18 + (char *) 2] = (char) 0x22;
								if (r10_1174 > r15_1204 + (char *) 3)
									r15_1204.u1[r13_18 + (char *) 3] = (char) 0x3F;
								r15_1204.u1 = r15_1204 + (char *) 0x04;
								dl_2537 = 0x00;
								edx_24_8_1571 = 0x00;
								ebp_1209 = 0x00;
								r9_1140 = rax_1141;
								goto l00000000000046E9;
							}
							goto l0000000000004929;
						}
						else
						{
							bpl_2065 = 0x00;
							ebp_24_8_2604 = 0x00;
							ecx_1369 = 0x3F;
							goto l0000000000003A81;
						}
					}
				}
			}
			dl_1021 = 0x00;
			edx_24_8_1571 = 0x00;
			bpl_2065 = 0x00;
			ebp_24_8_2604 = 0x00;
			ecx_1369 = 0x3F;
			goto l0000000000003A81;
		}
l0000000000003DC8:
		if (bLocD3_4126 != 0x00)
		{
			cl_2779 = (byte) ebx_1039;
			r11_8105 = r11_7920;
			goto l0000000000003C33;
		}
l0000000000003DD3:
		r9_1140 = r9_1085;
		cl_2779 = (byte) ecx_1369;
		bpl_2065 = 0x00;
		ebp_24_8_2604 = 0x00;
		eax_1128 = 0x00;
		r8_7883 = r8_7909;
		r11_8121 = r11_7920;
		if (bLocD2_4101 == 0x00)
		{
			r8_7903 = r8_7909;
			r11_8092 = r11_7920;
			goto l0000000000003AA0;
		}
l0000000000003900:
		cl_2779 = (byte) ecx_1369;
		r8_7869 = r8_7883;
		r11_8092 = r11_8121;
		if (qwLocF0_4078 == null)
			goto l000000000000391C;
		uint64 rdx_2784 = (uint64) (qwLocF0_4078[(uint64) ((byte) ecx_1369 >> 0x05)] >> cl_2779 & 0x01);
		edx_24_8_1571 = SLICE(rdx_2784, word24, 8);
		r8_7869 = r8_7883;
		r11_8092 = r11_8121;
		r11_8092 = r11_8121;
		if ((word32) rdx_2784 == 0x00)
		{
l000000000000391C:
			r11_8078 = r11_8092;
			if ((byte) r8_7869 != 0x00)
				goto l0000000000003925;
			goto l0000000000003AA9;
		}
l0000000000003925:
		dl_1559 = (byte) (r13d_3661 == 0x02);
		eax_3205 = SEQ(edx_24_8_1571, dl_1559);
		r11_8086 = r11_8092;
		if (bLocD2_4101 == 0x00)
			goto l0000000000003939;
		goto l0000000000003C50;
	}
}

// 0000000000004AE0: void fn0000000000004AE0(Register (ptr64 Eq_127) rsi, Register (ptr64 Eq_128) rdi, Register (ptr32 Eq_4) fs)
// Called from:
//      fn00000000000025B0
void fn0000000000004AE0(struct Eq_127 * rsi, struct Eq_128 * rdi, struct Eq_4 * fs)
{
	int32 * rax_27 = __errno_location();
	int32 r12d_28 = g_dw8020;
	struct Eq_2995 * rbp_30 = g_ptr8090;
	int32 eax_32 = *rax_27;
	if (r12d_28 <= 0x00)
	{
		if (rbp_30 != &g_t8080)
		{
			struct Eq_2995 * rax_59 = realloc(rbp_30, 0x10);
			rbp_30 = rax_59;
			if (rax_59 == null)
				goto l0000000000004C72;
			g_ptr8090 = rax_59;
		}
		else
		{
			struct Eq_2995 * rax_47 = malloc(0x10);
			rbp_30 = rax_47;
			if (rax_47 == null)
				goto l0000000000004C72;
			Eq_1255 xmm0_53;
			xmm0_53.u0 = g_t8080.u0;
			g_ptr8090 = rax_47;
			rax_47->t0000.u0 = (word128) xmm0_53;
		}
		memset(&rbp_30->t0000.u0 + (int64) r12d_28, 0, (int64) (0x01 - r12d_28) << 0x04);
		g_dw8020 = 0x01;
	}
	Eq_1255 rsi_90;
	rsi_90.u1 = rbp_30->t0000.u1;
	Eq_1259 r15_95;
	r15_95.u1 = rbp_30->t0008.u1;
	ui32 r12d_109 = rsi->dw0004 | 0x01;
	Eq_1255 rax_126 = fn0000000000003640(rsi->dw0000, rdi, rsi_90, r15_95, r12d_109, &rsi->dw0004 + 1, fs, rsi->ptr0028, rsi->ptr0030);
	if (rsi_90 <= rax_126)
	{
		rbp_30->t0000.u1 = (char *) ((word128) rax_126 + 1);
		if (r15_95 != 0x80C0)
			free(r15_95);
		Eq_1259 rax_160 = malloc((word128) rax_126 + 1);
		if (rax_160 == 0x00 && rax_126 != ~0x00)
		{
l0000000000004C72:
			fn0000000000002CD0();
		}
		rbp_30->t0008.u1 = (char *) rax_160;
		fn0000000000003640(rsi->dw0000, rdi, (word128) rax_126 + 1, rax_160, r12d_109, &rsi->dw0004 + 1, fs, rsi->ptr0028, rsi->ptr0030);
	}
	*rax_27 = eax_32;
}

void g_t4C80(void * rdi) = ??/* Unexpected function type (fn void ((ptr64 void))) */ ; // 0000000000004C80
// 0000000000004D00: void fn0000000000004D00(Register (ptr64 Eq_66) rdi)
// Called from:
//      fn00000000000025B0
void fn0000000000004D00(void (* rdi)(void * rdi))
{
	__cxa_atexit(rdi, null, g_ptr8008);
}

// tmpzpz4fq5n_got.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

<anonymous> * free_GOT = &g_t2030; // 0000000000007E48
<anonymous> * abort_GOT = &g_t2040; // 0000000000007E50
<anonymous> * __errno_location_GOT = &g_t2050; // 0000000000007E58
<anonymous> * strncmp_GOT = &g_t2060; // 0000000000007E60
<anonymous> * _exit_GOT = &g_t2070; // 0000000000007E68
<anonymous> * __fpending_GOT = &g_t2080; // 0000000000007E70
<anonymous> * puts_GOT = &g_t2090; // 0000000000007E78
<anonymous> * textdomain_GOT = &g_t20A0; // 0000000000007E80
<anonymous> * fclose_GOT = &g_t20B0; // 0000000000007E88
<anonymous> * getpwuid_GOT = &g_t20C0; // 0000000000007E90
<anonymous> * bindtextdomain_GOT = &g_t20D0; // 0000000000007E98
<anonymous> * dcgettext_GOT = &g_t20E0; // 0000000000007EA0
<anonymous> * __ctype_get_mb_cur_max_GOT = &g_t20F0; // 0000000000007EA8
<anonymous> * strlen_GOT = &g_t2100; // 0000000000007EB0
<anonymous> * __stack_chk_fail_GOT = &g_t2110; // 0000000000007EB8
<anonymous> * getopt_long_GOT = &g_t2120; // 0000000000007EC0
<anonymous> * mbrtowc_GOT = &g_t2130; // 0000000000007EC8
<anonymous> * strrchr_GOT = &g_t2140; // 0000000000007ED0
<anonymous> * lseek_GOT = &g_t2150; // 0000000000007ED8
<anonymous> * memset_GOT = &g_t2160; // 0000000000007EE0
<anonymous> * geteuid_GOT = &g_t2170; // 0000000000007EE8
<anonymous> * memcmp_GOT = &g_t2180; // 0000000000007EF0
<anonymous> * fputs_unlocked_GOT = &g_t2190; // 0000000000007EF8
<anonymous> * strcmp_GOT = &g_t21A0; // 0000000000007F00
<anonymous> * fputc_unlocked_GOT = &g_t21B0; // 0000000000007F08
<anonymous> * __memcpy_chk_GOT = &g_t21C0; // 0000000000007F10
<anonymous> * fileno_GOT = &g_t21D0; // 0000000000007F18
<anonymous> * malloc_GOT = &g_t21E0; // 0000000000007F20
<anonymous> * fflush_GOT = &g_t21F0; // 0000000000007F28
<anonymous> * nl_langinfo_GOT = &g_t2200; // 0000000000007F30
<anonymous> * __freading_GOT = &g_t2210; // 0000000000007F38
<anonymous> * realloc_GOT = &g_t2220; // 0000000000007F40
<anonymous> * setlocale_GOT = &g_t2230; // 0000000000007F48
<anonymous> * __printf_chk_GOT = &g_t2240; // 0000000000007F50
<anonymous> * error_GOT = &g_t2250; // 0000000000007F58
<anonymous> * fseeko_GOT = &g_t2260; // 0000000000007F60
<anonymous> * __cxa_atexit_GOT = &g_t2270; // 0000000000007F68
<anonymous> * exit_GOT = &g_t2280; // 0000000000007F70
<anonymous> * fwrite_GOT = &g_t2290; // 0000000000007F78
<anonymous> * __fprintf_chk_GOT = &g_t22A0; // 0000000000007F80
<anonymous> * mbsinit_GOT = &g_t22B0; // 0000000000007F88
<anonymous> * iswprint_GOT = &g_t22C0; // 0000000000007F90
<anonymous> * __ctype_b_loc_GOT = &g_t22D0; // 0000000000007F98
<anonymous> * __libc_start_main_GOT = null; // 0000000000007FA0
<anonymous> * _ITM_deregisterTMCloneTable_GOT = null; // 0000000000007FA8
<anonymous> * stdout_GOT = null; // 0000000000007FB0
<anonymous> * optind_GOT = null; // 0000000000007FB8
<anonymous> * __gmon_start___GOT = null; // 0000000000007FC0
<anonymous> * program_invocation_name_GOT = null; // 0000000000007FC8
<anonymous> * _ITM_registerTMCloneTable_GOT = null; // 0000000000007FD0
<anonymous> * program_invocation_short_name_GOT = null; // 0000000000007FD8
<anonymous> * __cxa_finalize_GOT = null; // 0000000000007FE0
<anonymous> * opterr_GOT = null; // 0000000000007FE8
<anonymous> * stderr_GOT = null; // 0000000000007FF0
// tmpzpz4fq5n_rodata.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

union Eq_641 g_u50D6 = // 00000000000050D6
	{
		'\xE2'
	};
union Eq_641 g_u50DA = // 00000000000050DA
	{
		'\xA1'
	};
union Eq_641 g_u50DD = // 00000000000050DD
	{
		'"'
	};
union Eq_641 g_u50DF = // 00000000000050DF
	{
		'\''
	};
union Eq_641 g_u50E1 = // 00000000000050E1
	{
		'\xA1'
	};
union Eq_641 g_u50E5 = // 00000000000050E5
	{
		'\xE2'
	};
struct Eq_240 g_t50E9 = // 00000000000050E9
	{
		
		{
		},
		66,
		0x31,
		0x38,
		0x30,
		0x33,
		0x30,
		0x00,
		0x25,
	};
union Eq_641 g_u514A = // 000000000000514A
	{
		'`'
	};
void g_v5560 = ??void??; // 0000000000005560
word32 g_a55E4[] = // 00000000000055E4
	{
	};
word32 g_a5610[] = // 0000000000005610
	{
	};
word32 g_a5710[] = // 0000000000005710
	{
	};
word32 g_a5810[] = // 0000000000005810
	{
	};
<unknown> g_t5920 = // 0000000000005920;
// tmpzpz4fq5n_bss.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

Eq_7 g_t81C0 = // 00000000000081C0
	{
		null
	};
// tmpzpz4fq5n_plt.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

<anonymous> g_t2030 = <code>; // 0000000000002030
<anonymous> g_t2040 = <code>; // 0000000000002040
<anonymous> g_t2050 = <code>; // 0000000000002050
<anonymous> g_t2060 = <code>; // 0000000000002060
<anonymous> g_t2070 = <code>; // 0000000000002070
<anonymous> g_t2080 = <code>; // 0000000000002080
<anonymous> g_t2090 = <code>; // 0000000000002090
<anonymous> g_t20A0 = <code>; // 00000000000020A0
<anonymous> g_t20B0 = <code>; // 00000000000020B0
<anonymous> g_t20C0 = <code>; // 00000000000020C0
<anonymous> g_t20D0 = <code>; // 00000000000020D0
<anonymous> g_t20E0 = <code>; // 00000000000020E0
<anonymous> g_t20F0 = <code>; // 00000000000020F0
<anonymous> g_t2100 = <code>; // 0000000000002100
<anonymous> g_t2110 = <code>; // 0000000000002110
<anonymous> g_t2120 = <code>; // 0000000000002120
<anonymous> g_t2130 = <code>; // 0000000000002130
<anonymous> g_t2140 = <code>; // 0000000000002140
<anonymous> g_t2150 = <code>; // 0000000000002150
<anonymous> g_t2160 = <code>; // 0000000000002160
<anonymous> g_t2170 = <code>; // 0000000000002170
<anonymous> g_t2180 = <code>; // 0000000000002180
<anonymous> g_t2190 = <code>; // 0000000000002190
<anonymous> g_t21A0 = <code>; // 00000000000021A0
<anonymous> g_t21B0 = <code>; // 00000000000021B0
<anonymous> g_t21C0 = <code>; // 00000000000021C0
<anonymous> g_t21D0 = <code>; // 00000000000021D0
<anonymous> g_t21E0 = <code>; // 00000000000021E0
<anonymous> g_t21F0 = <code>; // 00000000000021F0
<anonymous> g_t2200 = <code>; // 0000000000002200
<anonymous> g_t2210 = <code>; // 0000000000002210
<anonymous> g_t2220 = <code>; // 0000000000002220
<anonymous> g_t2230 = <code>; // 0000000000002230
<anonymous> g_t2240 = <code>; // 0000000000002240
<anonymous> g_t2250 = <code>; // 0000000000002250
<anonymous> g_t2260 = <code>; // 0000000000002260
<anonymous> g_t2270 = <code>; // 0000000000002270
<anonymous> g_t2280 = <code>; // 0000000000002280
<anonymous> g_t2290 = <code>; // 0000000000002290
<anonymous> g_t22A0 = <code>; // 00000000000022A0
<anonymous> g_t22B0 = <code>; // 00000000000022B0
<anonymous> g_t22C0 = <code>; // 00000000000022C0
<anonymous> g_t22D0 = <code>; // 00000000000022D0
// tmpzpz4fq5n_data_rel_ro.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

struct option g_t7BE0 = // 0000000000007BE0
	{
	};
// tmpzpz4fq5n_data.c
// Generated by decompiling tmpzpz4fq5n
// using Reko decompiler version 0.11.6.0.

#include "tmpzpz4fq5n.h"

void * g_ptr8008 = &g_v8008; // 0000000000008008
int32 g_dw8020 = 1; // 0000000000008020
int32 g_dw8024 = 1; // 0000000000008024
struct Eq_127 g_t8040 = // 0000000000008040
	{
		0x08,
		0x00,
		null,
		null,
	};
Eq_1255 g_t8080 = // 0000000000008080
	{
		
		{
			0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC0, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
		}
	};
struct Eq_2995 * g_ptr8090 = &g_t8080; // 0000000000008090
