// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x00001000
    asm("invalid");
    __r9 = __r9 - 8;
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
         *__rax();
    }
    __r9 = __r9 + 8;
}

L00001030()
{
    asm("invalid");
    _push(0);
    _push( *16256);
    goto ( *16264);
}

L00001040()
{
    asm("invalid");
    _push(1);
    _push( *16256);
    goto ( *16264);
}

L00001050()
{
    asm("invalid");
    _push(2);
    _push( *16256);
    goto ( *16264);
}

L00001060()
{
    asm("invalid");
    _push(3);
    _push( *16256);
    goto ( *16264);
}

L00001070()
{
    asm("invalid");
    _push(4);
    _push( *16256);
    goto ( *16264);
}

L00001080()
{
    asm("invalid");
    _push(5);
    _push( *16256);
    goto ( *16264);
}

L00001090()
{
    asm("invalid");
    _push(6);
    _push( *16256);
    goto ( *16264);
}

L000010A0()
{
    asm("invalid");
    _push(7);
    _push( *16256);
    goto ( *16264);
}

L000010B0()
{
    asm("invalid");
    _push(8);
    _push( *16256);
    goto ( *16264);
}

L000010C0()
{
    asm("invalid");
    goto __imp____cxa_finalize;
}

L000010D0()
{
    asm("invalid");
    goto __imp__puts;
}

L000010F0()
{
    asm("invalid");
    goto __imp____stack_chk_fail;
}

L00001100()
{
    asm("invalid");
    goto __imp__system;
}

L00001130()
{
    asm("invalid");
    goto __imp____printf_chk;
}

L00001150()
{
    asm("invalid");
    goto __imp____isoc99_scanf;
}

main(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001160
    __rax = __rax;
    asm("invalid");
    __r9 = __r9 - 8;
    askdo(__rcx);
    __r9 = __r9 + 8;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx,                       // r55
    _unknown_ __rdx                        // r56
)
{// addr = 0x00001180
    asm("invalid");
    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __imp____libc_start_main();
    asm("hlt");
    asm("o16 nop [cs:rax+rax]");
    if( &completed.0 !=  &completed.0 && __imp___ITM_deregisterTMCloneTable != 0) {
        goto __rax;
    }
}

deregister_tm_clones()
{// addr = 0x000011B0
    if( &completed.0 ==  &completed.0 || __imp___ITM_deregisterTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

register_tm_clones()
{// addr = 0x000011E0
    if( &completed.0 == 0 || __imp___ITM_registerTMCloneTable == 0) {
        return;
    } else {
        goto __rax;
    }
}

__do_global_dtors_aux(
    _unknown_ __rax                        // r53
)
{// addr = 0x00001220
    _unknown_ _t3;                         // _t3

    __rax = __rax;
    asm("invalid");
    if(completed.0 != 0) {
        return;
    } else {
        _push(_t3);
        if(__imp____cxa_finalize != 0) {
            L000010C0();
        }
        deregister_tm_clones();
        completed.0 = 1;
        _pop(__r8);
        return;
    }
}

frame_dummy()
{// addr = 0x00001260
    asm("invalid");
    if( &completed.0 != 0 && __imp___ITM_registerTMCloneTable != 0) {
        goto __rax;
    }
}

askdo(
    _unknown_ __rcx                        // r55
)
{// addr = 0x00001270
    signed long long _v32;                 // _cfa_ffffffe0
    signed short _v58;                     // _cfa_ffffffc6
    short _v60;                            // _cfa_ffffffc4
    intOrPtr _v80;                         // _cfa_ffffffb0
    _unknown_ __rbx;                       // r54
    _unknown_ __r8;                        // r59
    signed char _t31;                      // _t31
    _unknown_ _t37;                        // _t37
    _unknown_ _t39;                        // _t39
    _unknown_ _t41;                        // _t41
    intOrPtr _t52;                         // _t52
    intOrPtr _t53;                         // _t53
    intOrPtr _t54;                         // _t54
    _unknown_ _t57;                        // _t57
    intOrPtr _t61;                         // _t61
    signed long long _t65;                 // _t65
    _unknown_ _t69;                        // _t69
    _unknown_ _t72;                        // _t72
    _unknown_ _t92;                        // _t92

L0:
    while(1) {
L0:
        __rcx = __rcx;
        asm("invalid");
        _push(_t92);
        _push(_t69);
        __r9 = __r9 - 72;
        _t65 =  *fs:0x28];
        _v32 = _t65;
        L00001100();
        L000010D0();
        _push( *16472);
        _push(memory);
        L00001130();
        L00001130();
        L000010D0();
        L00001130();
        _t47 = 0;
        L00001150();
        _pop(__rax);
        _pop(__rdx);
        asm("fldz");
        _t52 = st0;
        asm("fxch st0, st2");
        asm("fucomi st0, st2");
        st2 = _t52;
        if(_t47 != 0) {
            st0 = _t52;
        } else {
            if(_t47 == 0) {
                st1 = _t52;
                tword [rip+0x2bc8] = _t52;
                tword [rip+0x2bd7] = tword [rip+0x2bc2];
                L00001100();
                askdo(__rcx);
            } else {
                st0 = _t52;
            }
        }
        _t53 =  *8196;
        asm("fxch st0, st1");
        asm("fcomi st0, st1");
        st1 = _t53;
        if(_t47 >= 0) {
            _t54 = st0;
            tword [rip+0x2bf0] = _t54;
            tword [rip+0x2c05] = _t54;
            L00001100();
            askdo(__rcx);
        } else {
            st0 = _t53;
        }
        asm("fldz");
        asm("fucomip st0, st1");
        st0 = tword [rip+0x2d04];
        if(_t47 != 0 || _t47 != 0) {
            goto L13;
        }
L8:
        asm("fucomip st0, st1");
        asm("fld1");
        _t29 =  !=  ? 0 : _t47 ?_? 0;
        asm("fucomip st0, st1");
        _t61 =  *8204;
        _t37 = _t47 ?_? 0;
        _t38 = _t37 != 0 ? 0 : _t37;
        _t30 = ( !=  ? 0 : _t47 ?_? 0) | (_t37 != 0 ? 0 : _t37);
        asm("fucomip st0, st1");
        _t39 = _t47 ?_? 0;
        _t40 = _t39 != 0 ? 0 : _t39;
        _t31 = ( !=  ? 0 : _t47 ?_? 0) | (_t37 != 0 ? 0 : _t37) | (_t39 != 0 ? 0 : _t39);
        if(_t31 != 0) {
L11:
            st0 = _t61;
L12:
            L00001130();
            L00001150();
            goto L13;
        }
L9:
        asm("fucomip st0, st1");
        st0 =  *8208;
        _t41 = _t48 ?_? 0;
        _t34 = _t41 == 0 ? _t41 : _t31;
        _t49 = _t41 == 0 ? _t41 : _t31;
        if((_t41 == 0 ? _t41 : _t31) == 0) {
            goto L13;
        }
L10:
        goto L12;
L13:
        L00001130();
        L00001150();
        asm("fnstcw word [rsp+0x1e]");
        _v60 = _v58 & 65535 | 12;
        asm("fldcw word [rsp+0x1c]");
        asm("fistp dword [rsp+0x8]");
        asm("fldcw word [rsp+0x1e]");
        _t47 = _v80 - 9;
        if(_v80 > 9) {
L19:
            _t57 = tword [rip+0x29b7];
            tword [rip+0x2b5a] = _t57;
            L00001100();
            askdo(__rcx);
            if(_v32 ==  *fs:0x28]) {
L18:
                __r9 = __r9 + 72;
                _pop(__rbx);
                _pop(__r8);
                return;
            }
L20:
            L000010F0();
            asm("o16 nop [cs:rax+rax]");
L21:
            asm("invalid");
            __r9 = __r9 - 8;
            tword [rip+0x29a3] = tword [rip+0x2989];
            L00001100();
            __r9 = __r9 + 8;
            continue;
        }
L14:
        _t65 =  *((intOrPtr*)(8596 + _t65 * 4)) + 8596;
        goto __rax;
    }
}

repeat(
    _unknown_ __rax,                       // r53
    _unknown_ __rcx                        // r55
)
{// addr = 0x00001690
    signed long long _v32;                 // _cfa_ffffffe0
    signed short _v58;                     // _cfa_ffffffc6
    short _v60;                            // _cfa_ffffffc4
    intOrPtr _v80;                         // _cfa_ffffffb0
    _unknown_ __rbx;                       // r54
    _unknown_ __r8;                        // r59
    signed char _t31;                      // _t31
    _unknown_ _t37;                        // _t37
    _unknown_ _t39;                        // _t39
    _unknown_ _t41;                        // _t41
    intOrPtr _t53;                         // _t53
    intOrPtr _t54;                         // _t54
    intOrPtr _t55;                         // _t55
    _unknown_ _t58;                        // _t58
    intOrPtr _t61;                         // _t61
    signed long long _t66;                 // _t66
    _unknown_ _t70;                        // _t70
    _unknown_ _t75;                        // _t75
    _unknown_ _t95;                        // _t95

L0:
    while(1) {
L0:
        asm("invalid");
        __r9 = __r9 - 8;
        tword [rip+0x29a3] = tword [rip+0x2989];
        L00001100();
        __r9 = __r9 + 8;
        asm("invalid");
        _push(_t95);
        _push(_t70);
        __r9 = __r9 - 72;
        _t66 =  *fs:0x28];
        _v32 = _t66;
        L00001100();
        L000010D0();
        _push( *16472);
        _push(memory);
        L00001130();
        L00001130();
        L000010D0();
        L00001130();
        _t47 = 0;
        L00001150();
        _pop(__rax);
        _pop(__rdx);
        asm("fldz");
        _t53 = st0;
        asm("fxch st0, st2");
        asm("fucomi st0, st2");
        st2 = _t53;
        if(_t47 != 0) {
            st0 = _t53;
        } else {
            if(_t47 == 0) {
                st1 = _t53;
                tword [rip+0x2bc8] = _t53;
                tword [rip+0x2bd7] = tword [rip+0x2bc2];
                L00001100();
                L1();
            } else {
                st0 = _t53;
            }
        }
        _t54 =  *8196;
        asm("fxch st0, st1");
        asm("fcomi st0, st1");
        st1 = _t54;
        if(_t47 >= 0) {
            _t55 = st0;
            tword [rip+0x2bf0] = _t55;
            tword [rip+0x2c05] = _t55;
            L00001100();
            L1();
        } else {
            st0 = _t54;
        }
        asm("fldz");
        asm("fucomip st0, st1");
        st0 = tword [rip+0x2d04];
        if(_t47 != 0 || _t47 != 0) {
            goto L14;
        }
L9:
        asm("fucomip st0, st1");
        asm("fld1");
        _t29 =  !=  ? 0 : _t47 ?_? 0;
        asm("fucomip st0, st1");
        _t61 =  *8204;
        _t37 = _t47 ?_? 0;
        _t38 = _t37 != 0 ? 0 : _t37;
        _t30 = ( !=  ? 0 : _t47 ?_? 0) | (_t37 != 0 ? 0 : _t37);
        asm("fucomip st0, st1");
        _t39 = _t47 ?_? 0;
        _t40 = _t39 != 0 ? 0 : _t39;
        _t31 = ( !=  ? 0 : _t47 ?_? 0) | (_t37 != 0 ? 0 : _t37) | (_t39 != 0 ? 0 : _t39);
        if(_t31 != 0) {
L12:
            st0 = _t61;
L13:
            L00001130();
            L00001150();
            goto L14;
        }
L10:
        asm("fucomip st0, st1");
        st0 =  *8208;
        _t41 = _t48 ?_? 0;
        _t34 = _t41 == 0 ? _t41 : _t31;
        _t49 = _t41 == 0 ? _t41 : _t31;
        if((_t41 == 0 ? _t41 : _t31) == 0) {
            goto L14;
        }
L11:
        goto L13;
L14:
        L00001130();
        L00001150();
        asm("fnstcw word [rsp+0x1e]");
        _v60 = _v58 & 65535 | 12;
        asm("fldcw word [rsp+0x1c]");
        asm("fistp dword [rsp+0x8]");
        asm("fldcw word [rsp+0x1e]");
        _t47 = _v80 - 9;
        if(_v80 > 9) {
L20:
            _t58 = tword [rip+0x29b7];
L18:
            tword [rip+0x2b5a] = _t58;
            L00001100();
            L1();
            if(_v32 !=  *fs:0x28]) {
L21:
                L000010F0();
                asm("o16 nop [cs:rax+rax]");
                continue;
            }
L19:
            __r9 = __r9 + 72;
            _pop(__rbx);
            _pop(__r8);
            return;
        }
L15:
        _t66 =  *((intOrPtr*)(8596 + _t66 * 4)) + 8596;
        goto __rax;
    }
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x000016C0
    __rax = __rax;
    asm("invalid");
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x000016C0
    __rax = __rax;
    asm("invalid");
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

// Statistics:
//      63 Register nodes
//     131 Temporaries nodes
//       2 Casts
//      82 Statements
//      52 Labels
//       8 Gotos
//      25 Blocks
//     911 Nodes
//      61 Assembly nodes
//      28 Unknown Types


Total time: 0 seconds.
