/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_2020();
void sub_2030();
void sub_2040();
void sub_2050();
void sub_2060();
void sub_2070();
void sub_2080();
void sub_2090();
void sub_20A0();
void sub_20B0();
void sub_20C0();
void sub_20D0();
void sub_20E0();
void sub_20F0();
void sub_2100();
void sub_2110();
void sub_2120();
void sub_2130();
void sub_2140();
void sub_2150();
void sub_2160();
void sub_2170();
// int _cxa_finalize(void *);
// __int64 __fastcall InitOutput(_QWORD); weak
// size_t strlen(const char *s);
// _QWORD CheckIfSimulateMode(CommandLine *); idb
// void CommandLine::~CommandLine(CommandLine *__hidden this); idb
// char *dgettext(const char *domainname, const char *msgid);
// _QWORD Configuration::FindI(Configuration *__hidden this, const char *, const int *); idb
// _QWORD CheckIfCalledByScript(int, const char **); idb
// _QWORD operator new(unsigned __int64); idb
// void operator delete(void *, unsigned __int64); idb
// CommandLine *CommandLine::CommandLine(CommandLine *__hidden this); idb
// __int64 __fastcall std::__ostream_insert<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall DispatchCommandLine(_QWORD, _QWORD); weak
// __int64 __fastcall ParseCommandLine(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// __int64 __fastcall std::ios::clear(_QWORD, _QWORD); weak
// _QWORD Configuration::CndSet(Configuration *__hidden this, const char *, int); idb
// _QWORD Configuration::Set(Configuration *__hidden this, const char *, const int *); idb
// _QWORD InitSignals(); idb
int sub_24A0();
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_2500();
__int64 sub_2530();
char *sub_2570();
__int64 sub_25B0();
__int64 sub_25C0(); // weak
const char ***__fastcall sub_2630(const char ***a1);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int _cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
// int system(const char *command);
// void std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); idb
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
void *off_5008 = &off_5008; // idb
char byte_5018; // weak
_UNKNOWN unk_5019; // weak
// extern _QWORD std::cout[31]; weak
// extern Configuration *config; weak


//----- (0000000000002000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 51A0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000002020) ----------------------------------------------------
void sub_2020()
{
  JUMPOUT(0);
}
// 2026: control flows out of bounds to 0

//----- (0000000000002030) ----------------------------------------------------
void sub_2030()
{
  sub_2020();
}

//----- (0000000000002040) ----------------------------------------------------
void sub_2040()
{
  sub_2020();
}

//----- (0000000000002050) ----------------------------------------------------
void sub_2050()
{
  sub_2020();
}

//----- (0000000000002060) ----------------------------------------------------
void sub_2060()
{
  sub_2020();
}

//----- (0000000000002070) ----------------------------------------------------
void sub_2070()
{
  sub_2020();
}

//----- (0000000000002080) ----------------------------------------------------
void sub_2080()
{
  sub_2020();
}

//----- (0000000000002090) ----------------------------------------------------
void sub_2090()
{
  sub_2020();
}

//----- (00000000000020A0) ----------------------------------------------------
void sub_20A0()
{
  sub_2020();
}

//----- (00000000000020B0) ----------------------------------------------------
void sub_20B0()
{
  sub_2020();
}

//----- (00000000000020C0) ----------------------------------------------------
void sub_20C0()
{
  sub_2020();
}

//----- (00000000000020D0) ----------------------------------------------------
void sub_20D0()
{
  sub_2020();
}

//----- (00000000000020E0) ----------------------------------------------------
void sub_20E0()
{
  sub_2020();
}

//----- (00000000000020F0) ----------------------------------------------------
void sub_20F0()
{
  sub_2020();
}

//----- (0000000000002100) ----------------------------------------------------
void sub_2100()
{
  sub_2020();
}

//----- (0000000000002110) ----------------------------------------------------
void sub_2110()
{
  sub_2020();
}

//----- (0000000000002120) ----------------------------------------------------
void sub_2120()
{
  sub_2020();
}

//----- (0000000000002130) ----------------------------------------------------
void sub_2130()
{
  sub_2020();
}

//----- (0000000000002140) ----------------------------------------------------
void sub_2140()
{
  sub_2020();
}

//----- (0000000000002150) ----------------------------------------------------
void sub_2150()
{
  sub_2020();
}

//----- (0000000000002160) ----------------------------------------------------
void sub_2160()
{
  sub_2020();
}

//----- (0000000000002170) ----------------------------------------------------
void sub_2170()
{
  sub_2020();
}

//----- (0000000000002300) ----------------------------------------------------
__int64 __fastcall main(unsigned int a1, const char **a2, char **a3)
{
  unsigned int v3; // r12d
  int v5; // [rsp+1Ch] [rbp-74h] BYREF
  void *v6[4]; // [rsp+20h] [rbp-70h] BYREF
  _BYTE v7[24]; // [rsp+40h] [rbp-50h] BYREF
  unsigned __int64 v8; // [rsp+58h] [rbp-38h]

  v8 = __readfsqword(0x28u);
  CommandLine::CommandLine((CommandLine *)v7);
  ParseCommandLine(v6, v7, 0, &config, &system, a1, a2, sub_25C0, sub_2630);
  v5 = 0;
  if ( (unsigned int)Configuration::FindI(config, "quiet", &v5) == 2 )
  {
    Configuration::CndSet(config, "quiet::NoProgress", 1);
    v5 = 1;
    Configuration::Set(config, "quiet", &v5);
  }
  InitSignals();
  InitOutput(std::cout[30]);
  CheckIfCalledByScript(a1, a2);
  CheckIfSimulateMode((CommandLine *)v7);
  v3 = (unsigned __int16)DispatchCommandLine(v7, v6);
  if ( v6[0] )
    operator delete(v6[0], (char *)v6[2] - (char *)v6[0]);
  CommandLine::~CommandLine((CommandLine *)v7);
  return v3;
}
// 2190: using guessed type __int64 __fastcall InitOutput(_QWORD);
// 2260: using guessed type __int64 __fastcall DispatchCommandLine(_QWORD, _QWORD);
// 2270: using guessed type __int64 __fastcall ParseCommandLine(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 25C0: using guessed type __int64 sub_25C0();
// 5128: using guessed type _QWORD std::cout[31];
// 5148: using guessed type Configuration *config;

//----- (00000000000024A0) ----------------------------------------------------
int sub_24A0()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&unk_5019);
  return _cxa_atexit((void (*)(void *))&std::ios_base::Init::~Init, &unk_5019, &off_5008);
}

//----- (00000000000024D0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 24DA: positive sp value 8 has been found
// 24E1: variable 'v3' is possibly undefined

//----- (0000000000002500) ----------------------------------------------------
char *sub_2500()
{
  return &byte_5018;
}
// 5018: using guessed type char byte_5018;

//----- (0000000000002530) ----------------------------------------------------
__int64 sub_2530()
{
  return 0;
}

//----- (0000000000002570) ----------------------------------------------------
char *sub_2570()
{
  char *result; // rax

  if ( !byte_5018 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_5008);
    result = sub_2500();
    byte_5018 = 1;
  }
  return result;
}
// 5018: using guessed type char byte_5018;

//----- (00000000000025B0) ----------------------------------------------------
// attributes: thunk
__int64 sub_25B0()
{
  return sub_2530();
}

//----- (00000000000025C0) ----------------------------------------------------
__int64 sub_25C0()
{
  char *v0; // rax
  char *v1; // rbp
  size_t v2; // rax

  v0 = dgettext(
         "apt",
         "Usage: apt [options] command\n"
         "\n"
         "apt is a commandline package manager and provides commands for\n"
         "searching and managing as well as querying information about packages.\n"
         "It provides the same functionality as the specialized APT tools,\n"
         "like apt-get and apt-cache, but enables options more suitable for\n"
         "interactive use by default.\n");
  if ( v0 )
  {
    v1 = v0;
    v2 = strlen(v0);
    std::__ostream_insert<char,std::char_traits<char>>(std::cout, v1, v2);
  }
  else
  {
    std::ios::clear(
      (char *)std::cout + *(_QWORD *)(std::cout[0] - 24LL),
      *(_DWORD *)((char *)&std::cout[4] + *(_QWORD *)(std::cout[0] - 24LL)) | 1u);
  }
  return 1;
}
// 2250: using guessed type __int64 __fastcall std::__ostream_insert<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD);
// 2290: using guessed type __int64 __fastcall std::ios::clear(_QWORD, _QWORD);
// 25C0: using guessed type __int64 sub_25C0();
// 5128: using guessed type _QWORD std::cout[31];

//----- (0000000000002630) ----------------------------------------------------
const char ***__fastcall sub_2630(const char ***a1)
{
  const char **v1; // rax
  const char *v2; // rcx
  const char *v4; // [rsp+0h] [rbp-308h] BYREF
  const char *v5; // [rsp+2C8h] [rbp-40h]

  v4 = "list";
  dgettext("apt", "list packages based on package names");
  dgettext("apt", "search in package descriptions");
  dgettext("apt", "show package details");
  dgettext("apt", "install packages");
  dgettext("apt", "reinstall packages");
  dgettext("apt", "remove packages");
  dgettext("apt", "Remove automatically all unused packages");
  dgettext("apt", "update list of available packages");
  dgettext("apt", "upgrade the system by installing/upgrading packages");
  dgettext("apt", "upgrade the system by removing/installing/upgrading packages");
  dgettext("apt", "edit the source information file");
  dgettext("apt", "satisfy dependency strings");
  *a1 = 0;
  a1[1] = 0;
  a1[2] = 0;
  v5 = 0;
  v1 = (const char **)operator new(0x2D0u);
  v2 = v4;
  *a1 = v1;
  a1[2] = v1 + 90;
  *v1 = v2;
  v1[89] = v5;
  qmemcpy(
    (void *)((unsigned __int64)(v1 + 1) & 0xFFFFFFFFFFFFFFF8LL),
    (const void *)((char *)&v4 - ((char *)v1 - ((unsigned __int64)(v1 + 1) & 0xFFFFFFFFFFFFFFF8LL))),
    8LL * (((unsigned int)v1 - (((_DWORD)v1 + 8) & 0xFFFFFFF8) + 720) >> 3));
  a1[1] = v1 + 90;
  return a1;
}

//----- (0000000000002BF8) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=99 queued=33 decompiled=33 lumina nreq=0 worse=0 better=0
// ALL OK, 33 function(s) have been successfully decompiled
