/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
// int _cxa_finalize(void *);
// __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *deregister_tm_clones();
__int64 register_tm_clones();
char *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int __cdecl foo();
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
char _TMC_END__; // weak


//----- (0000000000001000) ----------------------------------------------------
// Alternative name is '_init'
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4040: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 106A: positive sp value 8 has been found
// 1071: variable 'v3' is possibly undefined

//----- (0000000000001090) ----------------------------------------------------
char *deregister_tm_clones()
{
  return &_TMC_END__;
}
// 4010: using guessed type char _TMC_END__;

//----- (00000000000010C0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}

//----- (0000000000001100) ----------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // rax

  if ( !_TMC_END__ )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _TMC_END__ = 1;
  }
  return result;
}
// 4010: using guessed type char _TMC_END__;

//----- (0000000000001140) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1140: using guessed type __int64 frame_dummy();

//----- (0000000000001149) ----------------------------------------------------
int __cdecl foo()
{
  return 42;
}

//----- (0000000000001153) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  __printf_chk(1, "chmod", envp);
  return 42;
}
// 1050: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);

//----- (000000000000117C) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=17 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
