/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
void sub_10D0();
void sub_10E0();
void sub_10F0();
void sub_1100();
void sub_1110();
void sub_1120();
void sub_1130();
void sub_1140();
// int _cxa_finalize(void *);
// __int64 __fastcall g_application_run(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall g_type_check_instance_cast(_QWORD, _QWORD); weak
// __int64 gedit_dirs_get_gedit_locale_dir(void); weak
// char *bindtextdomain(const char *domainname, const char *dirname);
// char *bind_textdomain_codeset(const char *domainname, const char *codeset);
// __int64 __fastcall g_object_add_weak_pointer(_QWORD, _QWORD); weak
// __int64 g_application_get_type(void); weak
// __int64 __fastcall g_object_run_dispose(_QWORD); weak
// __int64 gedit_debug_message(_QWORD, _QWORD, _QWORD, _QWORD, const char *, ...); weak
// __int64 gedit_dirs_init(void); weak
// char *setlocale(int category, const char *locale);
// __int64 __fastcall gedit_app_get_type(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall g_object_new(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// char *textdomain(const char *domainname);
// __int64 __fastcall g_object_unref(_QWORD); weak
// __int64 gedit_dirs_shutdown(void); weak
// __int64 gedit_settings_unref_singleton(void); weak
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_1420();
__int64 sub_1450();
char *sub_1490();
__int64 sub_14D0();
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *off_4008 = &off_4008; // idb
char edata; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40C8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
  sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
  sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
  sub_1020();
}

//----- (00000000000010D0) ----------------------------------------------------
void sub_10D0()
{
  sub_1020();
}

//----- (00000000000010E0) ----------------------------------------------------
void sub_10E0()
{
  sub_1020();
}

//----- (00000000000010F0) ----------------------------------------------------
void sub_10F0()
{
  sub_1020();
}

//----- (0000000000001100) ----------------------------------------------------
void sub_1100()
{
  sub_1020();
}

//----- (0000000000001110) ----------------------------------------------------
void sub_1110()
{
  sub_1020();
}

//----- (0000000000001120) ----------------------------------------------------
void sub_1120()
{
  sub_1020();
}

//----- (0000000000001130) ----------------------------------------------------
void sub_1130()
{
  sub_1020();
}

//----- (0000000000001140) ----------------------------------------------------
void sub_1140()
{
  sub_1020();
}

//----- (0000000000001280) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  __int64 type; // rbp
  const char *gedit_locale_dir; // rax
  __int64 v5; // rax
  __int64 v6; // rax
  int v7; // r12d
  __int64 v8; // rax
  __int64 v9; // rax
  __int64 v10; // rax
  _QWORD v12[7]; // [rsp+0h] [rbp-38h] BYREF

  v12[1] = __readfsqword(0x28u);
  type = gedit_app_get_type(argc, argv, envp);
  gedit_dirs_init();
  setlocale(6, "");
  gedit_locale_dir = (const char *)gedit_dirs_get_gedit_locale_dir();
  bindtextdomain("gedit", gedit_locale_dir);
  bind_textdomain_codeset("gedit", "UTF-8");
  textdomain("gedit");
  v12[0] = g_object_new(type, "application-id", "org.gnome.gedit", "flags", 12, 0);
  v5 = g_application_get_type();
  v6 = g_type_check_instance_cast(v12[0], v5);
  v7 = g_application_run(v6, (unsigned int)argc, argv);
  gedit_settings_unref_singleton();
  v8 = g_type_check_instance_cast(v12[0], 80);
  g_object_run_dispose(v8);
  v9 = g_type_check_instance_cast(v12[0], 80);
  g_object_add_weak_pointer(v9, v12);
  g_object_unref(v12[0]);
  if ( v12[0] )
  {
    v10 = g_type_check_instance_cast(v12[0], 80);
    gedit_debug_message(256, "../gedit/gedit.c", 161, "main", "Leaking with %i refs", *(_DWORD *)(v10 + 8));
  }
  gedit_dirs_shutdown();
  return v7;
}
// 1160: using guessed type __int64 __fastcall g_application_run(_QWORD, _QWORD, _QWORD);
// 1170: using guessed type __int64 __fastcall g_type_check_instance_cast(_QWORD, _QWORD);
// 1190: using guessed type __int64 gedit_dirs_get_gedit_locale_dir(void);
// 11C0: using guessed type __int64 __fastcall g_object_add_weak_pointer(_QWORD, _QWORD);
// 11D0: using guessed type __int64 g_application_get_type(void);
// 11E0: using guessed type __int64 __fastcall g_object_run_dispose(_QWORD);
// 11F0: using guessed type __int64 gedit_debug_message(_QWORD, _QWORD, _QWORD, _QWORD, const char *, ...);
// 1200: using guessed type __int64 gedit_dirs_init(void);
// 1220: using guessed type __int64 __fastcall gedit_app_get_type(_QWORD, _QWORD, _QWORD);
// 1230: using guessed type __int64 __fastcall g_object_new(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 1250: using guessed type __int64 __fastcall g_object_unref(_QWORD);
// 1260: using guessed type __int64 gedit_dirs_shutdown(void);
// 1270: using guessed type __int64 gedit_settings_unref_singleton(void);

//----- (00000000000013F0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 13FA: positive sp value 8 has been found
// 1401: variable 'v3' is possibly undefined

//----- (0000000000001420) ----------------------------------------------------
char *sub_1420()
{
  return &edata;
}
// 4010: using guessed type char edata;

//----- (0000000000001450) ----------------------------------------------------
__int64 sub_1450()
{
  return 0;
}

//----- (0000000000001490) ----------------------------------------------------
char *sub_1490()
{
  char *result; // rax

  if ( !edata )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4008);
    result = sub_1420();
    edata = 1;
  }
  return result;
}
// 4010: using guessed type char edata;

//----- (00000000000014D0) ----------------------------------------------------
// attributes: thunk
__int64 sub_14D0()
{
  return sub_1450();
}

//----- (00000000000014DC) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=67 queued=27 decompiled=27 lumina nreq=0 worse=0 better=0
// ALL OK, 27 function(s) have been successfully decompiled
