/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <math.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
// int _cxa_finalize(void *);
// int puts(const char *s);
// double pow(double x, double y);
// int system(const char *command);
// double cos(double x);
// double tan(double x);
// __int64 __printf_chk(_QWORD, const char *, ...); weak
// double sin(double x);
// __int64 __isoc99_scanf(const char *, ...); weak
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
char *deregister_tm_clones();
__int64 register_tm_clones();
char *_do_global_dtors_aux();
__int64 frame_dummy(); // weak
__int64 askdo();
__int64 repeat(); // weak
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
char _bss_start; // weak
_TBYTE askdo_input; // weak
_TBYTE result; // weak
_TBYTE func_name; // weak
__int128 memory; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40C8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
  sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
  sub_1020();
}

//----- (0000000000001160) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  askdo();
  return 0;
}

//----- (0000000000001180) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 118A: positive sp value 8 has been found
// 1191: variable 'v3' is possibly undefined

//----- (00000000000011B0) ----------------------------------------------------
char *deregister_tm_clones()
{
  return &_bss_start;
}
// 4010: using guessed type char _bss_start;

//----- (00000000000011E0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}

//----- (0000000000001220) ----------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // rax

  if ( !_bss_start )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 4010: using guessed type char _bss_start;

//----- (0000000000001260) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1260: using guessed type __int64 frame_dummy();

//----- (0000000000001270) ----------------------------------------------------
__int64 askdo()
{
  __int64 v0; // rdx
  long double v1; // fst7
  unsigned __int8 v2; // al
  long double v3; // fst7
  long double v4; // fst7
  __int64 v6; // [rsp-8h] [rbp-60h]
  long double v7; // [rsp+20h] [rbp-38h] BYREF
  unsigned __int64 v8; // [rsp+38h] [rbp-20h]

  v8 = __readfsqword(0x28u);
  system("clear");
  puts("\x1B[1;32m---------------------------------------\x1B[0m");
  __printf_chk(2, "\x1B[1;32m%Lf\x1B[0m\n", *(long double *)&memory);
  __printf_chk(2, "\x1B[1;32m---------------------------------------\x1B[0m");
  puts(
    "\n"
    "0. Clear all\n"
    "1. Addition\n"
    "2. Subtraction\n"
    "3. Multiplication\n"
    "4. Division\n"
    "5. sin (deg)\n"
    "6. cos (deg)\n"
    "7.tan (deg)\n"
    "8. n Power\n"
    "9. n Root");
  __printf_chk(2, "Enter function option number/memory input num>9: ");
  __isoc99_scanf("%Lf", &askdo_input);
  v0 = v6;
  v1 = *(long double *)&askdo_input;
  if ( *(long double *)&askdo_input == 0.0 )
  {
    *(long double *)&result = 0.0;
    *(long double *)&memory = 0.0;
    system("clear");
    askdo();
    v1 = *(long double *)&askdo_input;
  }
  if ( v1 >= 10.0 )
  {
    *(long double *)&result = v1;
    *(long double *)&memory = v1;
    system("clear");
    askdo();
  }
  if ( *(long double *)&memory == 0.0 )
  {
    LOBYTE(v0) = 1;
    if ( 1.0 != *(long double *)&askdo_input )
      v0 = 0;
    v2 = v0 | (2.0 == *(long double *)&askdo_input);
    LOBYTE(v0) = 1;
    if ( 3.0 != *(long double *)&askdo_input )
      v0 = 0;
    if ( (unsigned __int8)v0 | v2 || (LOBYTE(v0) = 1, 4.0 == *(long double *)&askdo_input) )
    {
      __printf_chk(2, "Enter memory number/primary number:");
      __isoc99_scanf("%Lf", &memory);
    }
  }
  __printf_chk(2, "Enter performing number:", v0);
  __isoc99_scanf("%Lf", &func_name);
  switch ( (int)*(long double *)&askdo_input )
  {
    case 1:
      v4 = *(long double *)&memory + *(long double *)&func_name;
      *(long double *)&result = *(long double *)&memory + *(long double *)&func_name;
      break;
    case 2:
      v4 = *(long double *)&memory - *(long double *)&func_name;
      *(long double *)&result = *(long double *)&memory - *(long double *)&func_name;
      break;
    case 3:
      v4 = *(long double *)&memory * *(long double *)&func_name;
      *(long double *)&result = *(long double *)&memory * *(long double *)&func_name;
      break;
    case 4:
      v4 = *(long double *)&memory / *(long double *)&func_name;
      *(long double *)&result = *(long double *)&memory / *(long double *)&func_name;
      break;
    case 5:
      v4 = sin(*(long double *)&func_name / 57.2957795);
      *(long double *)&result = v4;
      break;
    case 6:
      v4 = cos(*(long double *)&func_name / 57.2957795);
      *(long double *)&result = v4;
      break;
    case 7:
      v4 = tan(*(long double *)&func_name / 57.2957795);
      *(long double *)&result = v4;
      break;
    case 8:
      __printf_chk(2, "Enter exponent value: ");
      __isoc99_scanf("%Lf", &v7);
      v3 = v7;
      goto LABEL_15;
    case 9:
      __printf_chk(2, "Enter root cap value: ");
      __isoc99_scanf("%Lf", &v7);
      v3 = 1.0 / v7;
LABEL_15:
      v4 = pow(*(long double *)&func_name, v3);
      *(long double *)&result = v4;
      break;
    default:
      v4 = *(long double *)&result;
      break;
  }
  *(long double *)&memory = v4;
  system("clear");
  askdo();
  return 0;
}
// 1270: too many cbuild loops
// 1314: variable 'v6' is possibly undefined
// 13DC: variable 'v0' is possibly undefined
// 1130: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);
// 1150: using guessed type __int64 __isoc99_scanf(const char *, ...);
// 4020: using guessed type _TBYTE askdo_input;
// 4030: using guessed type _TBYTE result;
// 4040: using guessed type _TBYTE func_name;
// 4050: using guessed type __int128 memory;

//----- (0000000000001690) ----------------------------------------------------
__int64 repeat()
{
  memory = *(__int128 *)&result;
  system("clear");
  return askdo();
}
// 1690: using guessed type __int64 repeat();
// 4030: using guessed type _TBYTE result;
// 4050: using guessed type __int128 memory;

//----- (00000000000016C0) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=42 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
