//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <libintl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _Unwind_Exception {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2000(void);
void function_2180(int64_t * d);
int64_t function_2190(int64_t * a1);
int32_t function_21a0(char * s);
int64_t function_21b0(int64_t * a1);
int64_t function_21c0(void);
char * function_21d0(char * domainname, char * msgid);
int64_t function_21e0(char * a1, int32_t * a2);
int64_t function_21f0(int32_t a1, char ** a2);
int32_t function_2200(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle);
int64_t function_2210(int64_t a1);
int64_t function_2220(int64_t * a1, int64_t a2);
int64_t function_2230(void);
void function_2240(void);
int64_t function_2250(int64_t * a1, char * a2, int32_t a3);
int64_t function_2260(int64_t * a1, int64_t * a2);
int64_t function_2270(int64_t * a1, int64_t a2, int64_t ** a3, int64_t ** a4, int32_t a5, char ** a6, bool (*a7)(int64_t *), int64_t (*a8)());
int64_t function_2280(void);
int64_t function_2290(int64_t a1);
void function_22a0(struct _Unwind_Exception * object);
int64_t function_22b0(char * a1, int32_t a2);
int64_t function_22c0(char * a1, int32_t * a2);
int64_t function_22d0(void);
int64_t function_22e0(int64_t a1, int64_t a2, int64_t a3);
int64_t function_2465(void);
int64_t function_246e(void);
int64_t function_2500(void);
int64_t function_2530(void);
int64_t function_2570(void);
int64_t function_25b0(void);
int64_t function_25c0(void);
int64_t function_2630(int64_t result);
int64_t function_2bf8(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0x65697571; // 0x33b2
int64_t g2; // 0x5008
int64_t g3 = 0; // 0x5018
int64_t g4; // 0x5019
int32_t g5;

// ------- Dynamically Linked Functions Without Header --------

int32_t __cxa_atexit(void (*a1)(int64_t *), int64_t * a2, int64_t * a3);
void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);
void _Unwind_Resume(struct _Unwind_Exception * a1);
int64_t _Z10InitOutputPSt15basic_streambufIcSt11char_traitsIcEE(int64_t * a1);
int64_t _Z11InitSignalsv(void);
int64_t _Z16ParseCommandLineR11CommandLine7APT_CMDPKP13ConfigurationPP9pkgSystemiPPKcPFbS0_EPFSt6vectorI19aptDispatchWithHelpSaISF_EEvE(int64_t * a1, int64_t a2, int64_t ** a3, int64_t ** a4, int32_t a5, char ** a6, bool (*a7)(int64_t *), int64_t (*a8)());
int64_t _Z19CheckIfSimulateModeR11CommandLine(int64_t * a1);
int64_t _Z19DispatchCommandLineR11CommandLineRKSt6vectorINS_8DispatchESaIS2_EE(int64_t * a1, int64_t * a2);
int64_t _Z21CheckIfCalledByScriptiPPKc(int32_t a1, char ** a2);
int64_t _ZdlPvm(int64_t * a1, int64_t a2);
int64_t _ZN11CommandLineC1Ev(void);
int64_t _ZN11CommandLineD1Ev(void);
int64_t _ZN13Configuration3SetEPKcRKi(char * a1, int32_t * a2);
int64_t _ZN13Configuration6CndSetEPKci(char * a1, int32_t a2);
int64_t _ZNK13Configuration5FindIEPKcRKi(char * a1, int32_t * a2);
int64_t _ZNSt8ios_base4InitC1Ev(void);
int64_t _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate(int64_t a1);
int64_t _Znwm(int64_t a1);
int64_t _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l(int64_t * a1, char * a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x2000 - 0x201b
int64_t function_2000(void) {
    int64_t result = 0; // 0x2012
    if (*(int64_t *)0x4fe0 != 0) {
        // 0x2014
        __gmon_start__();
        result = &g5;
    }
    // 0x2016
    return result;
}

// Address range: 0x2180 - 0x218b
void function_2180(int64_t * d) {
    // 0x2180
    __cxa_finalize(d);
}

// Address range: 0x2190 - 0x219b
int64_t function_2190(int64_t * a1) {
    // 0x2190
    return _Z10InitOutputPSt15basic_streambufIcSt11char_traitsIcEE(a1);
}

// Address range: 0x21a0 - 0x21ab
int32_t function_21a0(char * s) {
    // 0x21a0
    return strlen(s);
}

// Address range: 0x21b0 - 0x21bb
int64_t function_21b0(int64_t * a1) {
    // 0x21b0
    return _Z19CheckIfSimulateModeR11CommandLine(a1);
}

// Address range: 0x21c0 - 0x21cb
int64_t function_21c0(void) {
    // 0x21c0
    return _ZN11CommandLineD1Ev();
}

// Address range: 0x21d0 - 0x21db
char * function_21d0(char * domainname, char * msgid) {
    // 0x21d0
    return dgettext(domainname, msgid);
}

// Address range: 0x21e0 - 0x21eb
int64_t function_21e0(char * a1, int32_t * a2) {
    // 0x21e0
    return _ZNK13Configuration5FindIEPKcRKi(a1, a2);
}

// Address range: 0x21f0 - 0x21fb
int64_t function_21f0(int32_t a1, char ** a2) {
    // 0x21f0
    return _Z21CheckIfCalledByScriptiPPKc(a1, a2);
}

// Address range: 0x2200 - 0x220b
int32_t function_2200(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle) {
    // 0x2200
    return __cxa_atexit(func, arg, dso_handle);
}

// Address range: 0x2210 - 0x221b
int64_t function_2210(int64_t a1) {
    // 0x2210
    return _Znwm(a1);
}

// Address range: 0x2220 - 0x222b
int64_t function_2220(int64_t * a1, int64_t a2) {
    // 0x2220
    return _ZdlPvm(a1, a2);
}

// Address range: 0x2230 - 0x223b
int64_t function_2230(void) {
    // 0x2230
    return _ZN11CommandLineC1Ev();
}

// Address range: 0x2240 - 0x224b
void function_2240(void) {
    // 0x2240
    __stack_chk_fail();
}

// Address range: 0x2250 - 0x225b
int64_t function_2250(int64_t * a1, char * a2, int32_t a3) {
    // 0x2250
    return _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l(a1, a2, a3);
}

// Address range: 0x2260 - 0x226b
int64_t function_2260(int64_t * a1, int64_t * a2) {
    // 0x2260
    return _Z19DispatchCommandLineR11CommandLineRKSt6vectorINS_8DispatchESaIS2_EE(a1, a2);
}

// Address range: 0x2270 - 0x227b
int64_t function_2270(int64_t * a1, int64_t a2, int64_t ** a3, int64_t ** a4, int32_t a5, char ** a6, bool (*a7)(int64_t *), int64_t (*a8)()) {
    // 0x2270
    return _Z16ParseCommandLineR11CommandLine7APT_CMDPKP13ConfigurationPP9pkgSystemiPPKcPFbS0_EPFSt6vectorI19aptDispatchWithHelpSaISF_EEvE(a1, a2, a3, a4, a5, a6, a7, a8);
}

// Address range: 0x2280 - 0x228b
int64_t function_2280(void) {
    // 0x2280
    return _ZNSt8ios_base4InitC1Ev();
}

// Address range: 0x2290 - 0x229b
int64_t function_2290(int64_t a1) {
    // 0x2290
    return _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate(a1);
}

// Address range: 0x22a0 - 0x22ab
void function_22a0(struct _Unwind_Exception * object) {
    // 0x22a0
    _Unwind_Resume(object);
}

// Address range: 0x22b0 - 0x22bb
int64_t function_22b0(char * a1, int32_t a2) {
    // 0x22b0
    return _ZN13Configuration6CndSetEPKci(a1, a2);
}

// Address range: 0x22c0 - 0x22cb
int64_t function_22c0(char * a1, int32_t * a2) {
    // 0x22c0
    return _ZN13Configuration3SetEPKcRKi(a1, a2);
}

// Address range: 0x22d0 - 0x22db
int64_t function_22d0(void) {
    // 0x22d0
    return _Z11InitSignalsv();
}

// Address range: 0x22e0 - 0x2465
int64_t function_22e0(int64_t a1, int64_t a2, int64_t a3) {
    // 0x22e0
    int64_t v1; // 0x22e0
    int64_t v2 = v1;
    int64_t v3 = *(int64_t *)(v2 + 16) - v2; // 0x22e9
    if (v2 != 0) {
        // 0x22f1
        _ZdlPvm((int64_t *)v2, v3);
    }
    // 0x22f6
    _Unwind_Resume((struct _Unwind_Exception *)v1);
    int64_t v4 = __readfsqword(40); // 0x2326
    _ZN11CommandLineC1Ev();
    int64_t v5 = *(int64_t *)0x4fc8; // 0x2351
    int64_t v6 = *(int64_t *)0x4fa8; // 0x2366
    int64_t v7; // bp-120, 0x22e0
    int64_t v8; // bp-88, 0x22e0
    _Z16ParseCommandLineR11CommandLine7APT_CMDPKP13ConfigurationPP9pkgSystemiPPKcPFbS0_EPFSt6vectorI19aptDispatchWithHelpSaISF_EEvE(&v7, (int64_t)&v8, NULL, (int64_t **)v5, (int32_t)v6, (char **)(v1 & 0xffffffff), (bool (*)(int64_t *))v3, (int64_t (*)())0x25c0);
    int64_t * v9 = (int64_t *)v5; // 0x237c
    int64_t v10 = *v9; // 0x237c
    if ((int32_t)_ZNK13Configuration5FindIEPKcRKi((char *)v10, (int32_t *)"quiet") == 2) {
        // 0x2425
        _ZN13Configuration6CndSetEPKci((char *)*v9, (int32_t)&g1);
        _ZN13Configuration3SetEPKcRKi((char *)*v9, (int32_t *)"quiet");
    }
    // 0x23a2
    _Z11InitSignalsv();
    int64_t v11 = *(int64_t *)(*(int64_t *)0x4fc0 + 240); // 0x23ae
    _Z10InitOutputPSt15basic_streambufIcSt11char_traitsIcEE((int64_t *)v11);
    _Z21CheckIfCalledByScriptiPPKc((int32_t)v1, (char **)v3);
    _Z19CheckIfSimulateModeR11CommandLine(&v8);
    uint64_t v12 = _Z19DispatchCommandLineR11CommandLineRKSt6vectorINS_8DispatchESaIS2_EE(&v8, &v7); // 0x23da
    int64_t v13 = v7; // 0x23df
    if (v13 != 0) {
        // 0x23ec
        _ZdlPvm((int64_t *)v13, v1 - v13);
    }
    // 0x23f8
    _ZN11CommandLineD1Ev();
    if (v4 == __readfsqword(40)) {
        // 0x2413
        return v12 % 0x10000;
    }
    // 0x2457
    __stack_chk_fail();
    return function_246e();
}

// Address range: 0x2465 - 0x246e
int64_t function_2465(void) {
    // 0x2465
    int64_t result; // 0x2465
    return result;
}

// Address range: 0x246e - 0x24cb
int64_t function_246e(void) {
    // 0x246e
    int64_t v1; // 0x246e
    int64_t v2 = *(int64_t *)(v1 - 112); // 0x246e
    if (v2 != 0) {
        // 0x247e
        _ZdlPvm((int64_t *)v2, *(int64_t *)(v1 - 96) - v2);
    }
    // 0x2483
    _ZN11CommandLineD1Ev();
    _Unwind_Resume((struct _Unwind_Exception *)v1);
    _ZNSt8ios_base4InitC1Ev();
    int64_t v3 = *(int64_t *)0x4ff8; // 0x24b4
    return __cxa_atexit((void (*)(int64_t *))v3, &g4, (int64_t *)0x5008);
}

// Address range: 0x24d0 - 0x24f6
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x24d0
    int64_t v1; // 0x24d0
    __libc_start_main(0x2300, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x2500 - 0x2529
int64_t function_2500(void) {
    // 0x2500
    return &g3;
}

// Address range: 0x2530 - 0x2569
int64_t function_2530(void) {
    // 0x2530
    return 0;
}

// Address range: 0x2570 - 0x25a9
int64_t function_2570(void) {
    // 0x2570
    if (*(char *)&g3 != 0) {
        // 0x25a8
        int64_t result; // 0x2570
        return result;
    }
    // 0x257d
    if (*(int64_t *)0x4f50 != 0) {
        // 0x258b
        __cxa_finalize((int64_t *)g2);
    }
    int64_t result2 = function_2500(); // 0x2597
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x25b0 - 0x25b9
int64_t function_25b0(void) {
    // 0x25b0
    return function_2530();
}

// Address range: 0x25c0 - 0x2628
int64_t function_25c0(void) {
    char * str = dgettext("apt", "Usage: apt [options] command\n\napt is a commandline package manager and provides commands for\nsearching and managing as well as querying information about packages.\nIt provides the same functionality as the specialized APT tools,\nlike apt-get and apt-cache, but enables options more suitable for\ninteractive use by default.\n"); // 0x25d3
    if (str == NULL) {
        int64_t v1 = *(int64_t *)0x4fc0; // 0x2608
        int64_t v2 = *(int64_t *)(*(int64_t *)v1 - 24); // 0x2612
        _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate(v2 + v1);
        return 1;
    }
    int32_t len = strlen(str); // 0x25e3
    int64_t v3 = *(int64_t *)0x4fc0; // 0x25e8
    _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l((int64_t *)v3, str, len);
    return 1;
}

// Address range: 0x2630 - 0x2bf5
int64_t function_2630(int64_t result) {
    int64_t v1 = __readfsqword(40); // 0x2657
    char * v2 = "list"; // bp-776, 0x266f
    dgettext("apt", "list packages based on package names");
    dgettext("apt", "search in package descriptions");
    dgettext("apt", "show package details");
    dgettext("apt", "install packages");
    dgettext("apt", "reinstall packages");
    dgettext("apt", "remove packages");
    dgettext("apt", "Remove automatically all unused packages");
    dgettext("apt", "update list of available packages");
    dgettext("apt", "upgrade the system by installing/upgrading packages");
    dgettext("apt", "upgrade the system by removing/installing/upgrading packages");
    dgettext("apt", "edit the source information file");
    dgettext("apt", "satisfy dependency strings");
    int64_t * v3 = (int64_t *)result; // 0x2a9b
    *v3 = 0;
    int64_t * v4 = (int64_t *)(result + 8); // 0x2ac1
    *v4 = 0;
    int64_t * v5 = (int64_t *)(result + 16); // 0x2ae8
    *v5 = 0;
    int64_t v6 = _Znwm(720); // 0x2b70
    *v3 = v6;
    int64_t v7 = v6 + 720; // 0x2b84
    int64_t v8 = v6 + 8 & -8; // 0x2b8b
    *v5 = v7;
    *(int64_t *)v6 = (int64_t)v2;
    *(int64_t *)(v6 + 712) = 0;
    int64_t v9 = v6 - v8; // 0x2ba6
    uint64_t v10 = (v9 + 720) / 8 % 0x20000000; // 0x2bb4
    __asm_rep_movsq_memcpy((char *)v8, (char *)((int64_t)&v2 - v9), v10);
    *v4 = v7;
    if (v1 == __readfsqword(40)) {
        // 0x2bd1
        return result;
    }
    // 0x2be4
    bool v11; // 0x2630
    int64_t v12 = v10 * (v11 ? -8 : 8) + v8; // 0x2bb6
    __stack_chk_fail();
    return function_22e0(v12, v12, v7);
}

// Address range: 0x2bf8 - 0x2c05
int64_t function_2bf8(void) {
    // 0x2bf8
    int64_t result; // 0x2bf8
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.7.0)
// Detected functions: 34

