//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float80_t;

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t askdo(int64_t a1);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
void function_10c0(int64_t * d);
int32_t function_10d0(char * s);
float64_t function_10e0(float64_t a1, float64_t a2);
void function_10f0(void);
int32_t function_1100(char * command);
float64_t function_1110(float64_t a1);
float64_t function_1120(float64_t a1);
int32_t function_1130(int32_t flag, char * format, ...);
float64_t function_1140(float64_t a1);
int32_t function_1150(char * format, ...);
int64_t register_tm_clones(void);
int64_t repeat(void);

// --------------------- Global Variables ---------------------

char * g1 = "\x1b[1;32m%Lf\x1b[0m\n"; // 0x201a
char * g2 = "\x1b[1;32m---------------------------------------\x1b[0m"; // 0x2078
int32_t * g3 = (int32_t *)-0xc7300000b21; // 0x2194
int64_t g4 = 0; // 0x4010
float80_t * g5 = NULL; // 0x4020
float80_t g6 = 0.0L; // 0x4030
float80_t * g7 = NULL; // 0x4040
float80_t * g8 = NULL; // 0x4050
int32_t g9;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
int32_t __printf_chk(int32_t a1, char * a2, ...);
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g9;
    }
    // 0x1016
    return result;
}

// Address range: 0x10c0 - 0x10ca
void function_10c0(int64_t * d) {
    // 0x10c0
    __cxa_finalize(d);
}

// Address range: 0x10d0 - 0x10da
int32_t function_10d0(char * s) {
    // 0x10d0
    return puts(s);
}

// Address range: 0x10e0 - 0x10ea
float64_t function_10e0(float64_t a1, float64_t a2) {
    // 0x10e0
    return pow(a1, a2);
}

// Address range: 0x10f0 - 0x10fa
void function_10f0(void) {
    // 0x10f0
    __stack_chk_fail();
}

// Address range: 0x1100 - 0x110a
int32_t function_1100(char * command) {
    // 0x1100
    return system(command);
}

// Address range: 0x1110 - 0x111a
float64_t function_1110(float64_t a1) {
    // 0x1110
    return cos(a1);
}

// Address range: 0x1120 - 0x112a
float64_t function_1120(float64_t a1) {
    // 0x1120
    return tan(a1);
}

// Address range: 0x1130 - 0x113a
int32_t function_1130(int32_t flag, char * format, ...) {
    // 0x1130
    return __printf_chk(flag, format);
}

// Address range: 0x1140 - 0x114a
float64_t function_1140(float64_t a1) {
    // 0x1140
    return sin(a1);
}

// Address range: 0x1150 - 0x115a
int32_t function_1150(char * format, ...) {
    // 0x1150
    return scanf(format);
}

// Address range: 0x1160 - 0x1176
int main(int argc, char ** argv) {
    // 0x1160
    askdo((int64_t)&g9);
    return 0;
}

// Address range: 0x1180 - 0x11a6
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1180
    int64_t v1; // 0x1180
    __libc_start_main(0x1160, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x11b0 - 0x11d9
int64_t deregister_tm_clones(void) {
    // 0x11b0
    return &g4;
}

// Address range: 0x11e0 - 0x1219
int64_t register_tm_clones(void) {
    // 0x11e0
    return 0;
}

// Address range: 0x1220 - 0x1259
int64_t __do_global_dtors_aux(void) {
    // 0x1220
    if (*(char *)&g4 != 0) {
        // 0x1258
        int64_t result; // 0x1220
        return result;
    }
    // 0x122d
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x123b
        __cxa_finalize((int64_t *)*(int64_t *)0x4008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1247
    *(char *)&g4 = 1;
    return result2;
}

// Address range: 0x1260 - 0x1269
int64_t frame_dummy(void) {
    // 0x1260
    return register_tm_clones();
}

// Address range: 0x1270 - 0x1690
int64_t askdo(int64_t a1) {
    int64_t v1 = __readfsqword(40); // 0x128b
    system("clear");
    puts((char *)&g2);
    __printf_chk(2, (char *)&g1);
    __printf_chk(2, (char *)&g2);
    puts("\n0. Clear all\n1. Addition\n2. Subtraction\n3. Multiplication\n4. Division\n5. sin (deg)\n6. cos (deg)\n7.tan (deg)\n8. n Power\n9. n Root");
    __printf_chk(2, "Enter function option number/memory input num>9: ");
    scanf("%Lf", (float80_t *)&g5);
    int3_t v2; // 0x1270
    int3_t v3 = v2 - 1;
    __frontend_reg_store_fpr(v3, *(float80_t *)&g5);
    int3_t v4 = v2 - 2;
    __frontend_reg_store_fpr(v4, 0.0L);
    int3_t v5 = v2 - 3; // 0x1317
    __frontend_reg_store_fpr(v5, __frontend_reg_load_fpr(v4));
    float80_t v6 = __frontend_reg_load_fpr(v5); // 0x1319
    __frontend_reg_store_fpr(v5, __frontend_reg_load_fpr(v3));
    __frontend_reg_store_fpr(v3, v6);
    float80_t v7 = __frontend_reg_load_fpr(v5); // 0x131b
    float80_t v8 = __frontend_reg_load_fpr(v3); // 0x131b
    __frontend_reg_store_fpr(v3, __frontend_reg_load_fpr(v5));
    float80_t v9 = __frontend_reg_load_fpr(v4);
    if (v7 != v8 == v7 == v8) {
        // 0x132b
        __frontend_reg_store_fpr(v4, v9);
    } else {
        if (v7 != v8) {
            // 0x1327
            __frontend_reg_store_fpr(v4, v9);
        } else {
            // 0x1460
            __frontend_reg_store_fpr(v3, v9);
            float80_t v10 = __frontend_reg_load_fpr(v3); // 0x1462
            g6 = v10;
            __frontend_reg_store_fpr(v3, v10);
            *(float80_t *)&g8 = __frontend_reg_load_fpr(v3);
            system("clear");
            askdo((int64_t)&g9);
            __frontend_reg_store_fpr(v3, *(float80_t *)&g5);
        }
    }
    // 0x1330
    __frontend_reg_store_fpr(v4, 10.0L);
    float80_t v11 = __frontend_reg_load_fpr(v4); // 0x1336
    __frontend_reg_store_fpr(v4, __frontend_reg_load_fpr(v3));
    __frontend_reg_store_fpr(v3, v11);
    float80_t v12 = __frontend_reg_load_fpr(v4); // 0x1338
    float80_t v13 = __frontend_reg_load_fpr(v3); // 0x1338
    __frontend_reg_store_fpr(v3, __frontend_reg_load_fpr(v4));
    float80_t v14 = __frontend_reg_load_fpr(v3);
    if (v12 >= v13) {
        // 0x1438
        __frontend_reg_store_fpr(v4, v14);
        g6 = __frontend_reg_load_fpr(v4);
        *(float80_t *)&g8 = __frontend_reg_load_fpr(v3);
        system("clear");
        askdo((int64_t)&g9);
    } else {
        // 0x1342
        __frontend_reg_store_fpr(v3, v14);
    }
    // 0x1344
    __frontend_reg_store_fpr(v3, 0.0L);
    __frontend_reg_store_fpr(v4, *(float80_t *)&g8);
    float80_t v15 = __frontend_reg_load_fpr(v4); // 0x134c
    float80_t v16 = __frontend_reg_load_fpr(v3); // 0x134c
    __frontend_reg_store_fpr(v3, __frontend_reg_load_fpr(v3));
    if (v15 != v16) {
        goto lab_0x13ce;
    } else {
        // 0x1354
        __frontend_reg_store_fpr(v3, *(float80_t *)&g5);
        __frontend_reg_store_fpr(v4, 2.0L);
        float80_t v17 = __frontend_reg_load_fpr(v4); // 0x1365
        float80_t v18 = __frontend_reg_load_fpr(v3); // 0x1365
        __frontend_reg_store_fpr(v4, 1.0L);
        float80_t v19 = __frontend_reg_load_fpr(v4); // 0x136f
        float80_t v20 = __frontend_reg_load_fpr(v3); // 0x136f
        __frontend_reg_store_fpr(v4, 3.0L);
        float80_t v21 = __frontend_reg_load_fpr(v4); // 0x137f
        float80_t v22 = __frontend_reg_load_fpr(v3); // 0x137f
        bool v23 = v17 == v18 == v17 == v18 | v19 == v20 == v19 == v20 | v21 == v22 == v21 == v22;
        if (v23) {
            // 0x13a8
            __frontend_reg_store_fpr(v3, __frontend_reg_load_fpr(v3));
            // 0x13aa
            __printf_chk(2, "Enter memory number/primary number:");
            scanf("%Lf", (float80_t *)&g8);
            goto lab_0x13ce;
        } else {
            // 0x138b
            __frontend_reg_store_fpr(v4, 4.0L);
            float80_t v24 = __frontend_reg_load_fpr(v4); // 0x1391
            float80_t v25 = __frontend_reg_load_fpr(v3); // 0x1391
            __frontend_reg_store_fpr(v3, __frontend_reg_load_fpr(v3));
            if (!((v24 != v25 ? v23 : v24 == v25))) {
                goto lab_0x13ce;
            } else {
                // 0x13aa
                __printf_chk(2, "Enter memory number/primary number:");
                scanf("%Lf", (float80_t *)&g8);
                goto lab_0x13ce;
            }
        }
    }
  lab_0x13ce:
    // 0x13ce
    __printf_chk(2, "Enter performing number:");
    scanf("%Lf", (float80_t *)&g7);
    __frontend_reg_store_fpr(v3, *(float80_t *)&g5);
    uint32_t v26 = (int32_t)__frontend_reg_load_fpr(v3); // 0x140d
    if (v26 < 10) {
        int32_t v27 = *(int32_t *)(4 * (int64_t)v26 + (int64_t)&g3); // 0x1429
        return (int64_t)v27 + (int64_t)&g3;
    }
    // 0x1673
    __frontend_reg_store_fpr(v3, g6);
    *(float80_t *)&g8 = __frontend_reg_load_fpr(v3);
    system("clear");
    askdo((int64_t)&g9);
    if (v1 == __readfsqword(40)) {
        // 0x1516
        return 0;
    }
    // 0x167e
    __stack_chk_fail();
    return &g9;
}

// Address range: 0x1690 - 0x16bd
int64_t repeat(void) {
    // 0x1690
    *(float80_t *)&g8 = g6;
    system("clear");
    return askdo((int64_t)&g9);
}

// Address range: 0x16c0 - 0x16cd
int64_t _fini(void) {
    // 0x16c0
    int64_t result; // 0x16c0
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 20

