//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <libintl.h>
#include <locale.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_1000(void);
void function_1150(int64_t * d);
int64_t function_1160(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1170(int64_t a1, int64_t a2);
void function_1180(void);
int64_t function_1190(void);
char * function_11a0(char * domainname, char * dirname);
char * function_11b0(char * domainname, char * codeset);
int64_t function_11c0(int64_t a1, int64_t * a2);
int64_t function_11d0(void);
int64_t function_11e0(int64_t a1);
int64_t function_11f0(int64_t a1, char * a2, int64_t a3, char * a4, char * a5, int32_t a6);
int64_t function_1200(void);
char * function_1210(int32_t category, char * locale);
int64_t function_1220(void);
int64_t function_1230(int64_t a1, char * a2, char * a3, char * a4, int64_t a5, int32_t a6);
char * function_1240(char * domainname);
int64_t function_1250(int64_t a1);
int64_t function_1260(void);
int64_t function_1270(void);
int64_t function_1420(void);
int64_t function_1450(void);
int64_t function_1490(void);
int64_t function_14d0(void);
int64_t function_14dc(void);

// --------------------- Global Variables ---------------------

char * g1; // 0x2009
int64_t g2 = 0; // 0x4010
int32_t g3;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);
char * bind_textdomain_codeset(char * a1, char * a2);
int64_t g_application_get_type(void);
int64_t g_application_run(int64_t a1, int64_t a2, int64_t a3);
int64_t g_object_add_weak_pointer(int64_t a1, int64_t * a2);
int64_t g_object_new(int64_t a1, char * a2, char * a3, char * a4, int64_t a5, int32_t a6);
int64_t g_object_run_dispose(int64_t a1);
int64_t g_object_unref(int64_t a1);
int64_t g_type_check_instance_cast(int64_t a1, int64_t a2);
int64_t gedit_app_get_type(void);
int64_t gedit_debug_message(int64_t a1, char * a2, int64_t a3, char * a4, char * a5, int32_t a6);
int64_t gedit_dirs_get_gedit_locale_dir(void);
int64_t gedit_dirs_init(void);
int64_t gedit_dirs_shutdown(void);
int64_t gedit_settings_unref_singleton(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t function_1000(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g3;
    }
    // 0x1016
    return result;
}

// Address range: 0x1150 - 0x115b
void function_1150(int64_t * d) {
    // 0x1150
    __cxa_finalize(d);
}

// Address range: 0x1160 - 0x116b
int64_t function_1160(int64_t a1, int64_t a2, int64_t a3) {
    // 0x1160
    return g_application_run(a1, a2, a3);
}

// Address range: 0x1170 - 0x117b
int64_t function_1170(int64_t a1, int64_t a2) {
    // 0x1170
    return g_type_check_instance_cast(a1, a2);
}

// Address range: 0x1180 - 0x118b
void function_1180(void) {
    // 0x1180
    __stack_chk_fail();
}

// Address range: 0x1190 - 0x119b
int64_t function_1190(void) {
    // 0x1190
    return gedit_dirs_get_gedit_locale_dir();
}

// Address range: 0x11a0 - 0x11ab
char * function_11a0(char * domainname, char * dirname) {
    // 0x11a0
    return bindtextdomain(domainname, dirname);
}

// Address range: 0x11b0 - 0x11bb
char * function_11b0(char * domainname, char * codeset) {
    // 0x11b0
    return bind_textdomain_codeset(domainname, codeset);
}

// Address range: 0x11c0 - 0x11cb
int64_t function_11c0(int64_t a1, int64_t * a2) {
    // 0x11c0
    return g_object_add_weak_pointer(a1, a2);
}

// Address range: 0x11d0 - 0x11db
int64_t function_11d0(void) {
    // 0x11d0
    return g_application_get_type();
}

// Address range: 0x11e0 - 0x11eb
int64_t function_11e0(int64_t a1) {
    // 0x11e0
    return g_object_run_dispose(a1);
}

// Address range: 0x11f0 - 0x11fb
int64_t function_11f0(int64_t a1, char * a2, int64_t a3, char * a4, char * a5, int32_t a6) {
    // 0x11f0
    return gedit_debug_message(a1, a2, a3, a4, a5, a6);
}

// Address range: 0x1200 - 0x120b
int64_t function_1200(void) {
    // 0x1200
    return gedit_dirs_init();
}

// Address range: 0x1210 - 0x121b
char * function_1210(int32_t category, char * locale) {
    // 0x1210
    return setlocale(category, locale);
}

// Address range: 0x1220 - 0x122b
int64_t function_1220(void) {
    // 0x1220
    return gedit_app_get_type();
}

// Address range: 0x1230 - 0x123b
int64_t function_1230(int64_t a1, char * a2, char * a3, char * a4, int64_t a5, int32_t a6) {
    // 0x1230
    return g_object_new(a1, a2, a3, a4, a5, a6);
}

// Address range: 0x1240 - 0x124b
char * function_1240(char * domainname) {
    // 0x1240
    return textdomain(domainname);
}

// Address range: 0x1250 - 0x125b
int64_t function_1250(int64_t a1) {
    // 0x1250
    return g_object_unref(a1);
}

// Address range: 0x1260 - 0x126b
int64_t function_1260(void) {
    // 0x1260
    return gedit_dirs_shutdown();
}

// Address range: 0x1270 - 0x127b
int64_t function_1270(void) {
    // 0x1270
    return gedit_settings_unref_singleton();
}

// Address range: 0x1280 - 0x13f0
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x129c
    int64_t v2 = gedit_app_get_type(); // 0x12ac
    gedit_dirs_init();
    setlocale(LC_ALL, (char *)&g1);
    bindtextdomain("gedit", (char *)gedit_dirs_get_gedit_locale_dir());
    bind_textdomain_codeset("gedit", "UTF-8");
    textdomain("gedit");
    int64_t v3 = g_object_new(v2, "application-id", "org.gnome.gedit", "flags", 12, 0);
    int64_t v4 = v3; // bp-56, 0x131c
    int64_t v5 = g_application_get_type(); // 0x1320
    int64_t v6 = g_application_run(g_type_check_instance_cast(v3, v5), argc & 0xffffffff, (int64_t)argv); // 0x1339
    gedit_settings_unref_singleton();
    g_object_run_dispose(g_type_check_instance_cast(v3, 80));
    g_object_add_weak_pointer(g_type_check_instance_cast(v3, 80), &v4);
    g_object_unref(v4);
    if (v4 != 0) {
        int32_t v7 = *(int32_t *)(g_type_check_instance_cast(v4, 80) + 8); // 0x13a4
        gedit_debug_message(256, "../gedit/gedit.c", 161, "main", "Leaking with %i refs", v7);
    }
    // 0x13bb
    gedit_dirs_shutdown();
    if (v1 == __readfsqword(40)) {
        // 0x13d0
        return v6 & 0xffffffff;
    }
    // 0x13df
    __stack_chk_fail();
    return &g3;
}

// Address range: 0x13f0 - 0x1416
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x13f0
    int64_t v1; // 0x13f0
    __libc_start_main(0x1280, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1420 - 0x1449
int64_t function_1420(void) {
    // 0x1420
    return &g2;
}

// Address range: 0x1450 - 0x1489
int64_t function_1450(void) {
    // 0x1450
    return 0;
}

// Address range: 0x1490 - 0x14c9
int64_t function_1490(void) {
    // 0x1490
    if (*(char *)&g2 != 0) {
        // 0x14c8
        int64_t result; // 0x1490
        return result;
    }
    // 0x149d
    if (*(int64_t *)0x3fe0 != 0) {
        // 0x14ab
        __cxa_finalize((int64_t *)*(int64_t *)0x4008);
    }
    int64_t result2 = function_1420(); // 0x14b7
    *(char *)&g2 = 1;
    return result2;
}

// Address range: 0x14d0 - 0x14d9
int64_t function_14d0(void) {
    // 0x14d0
    return function_1450();
}

// Address range: 0x14dc - 0x14e9
int64_t function_14dc(void) {
    // 0x14dc
    int64_t result; // 0x14dc
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (3.4.3)
// Detected functions: 27

