//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <error.h>
#include <getopt.h>
#include <langinfo.h>
#include <libintl.h>
#include <locale.h>
#include <pwd.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <wchar.h>
#include <wctype.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct _TYPEDEF___mbstate_t {
    int32_t e0;
    int64_t e1;
};

struct option {
    char * e0;
    int32_t e1;
    int32_t * e2;
    int32_t e3;
};

struct passwd {
    char * e0;
    char * e1;
    int32_t e2;
    int32_t e3;
    char * e4;
    char * e5;
    char * e6;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2000(void);
void function_22e0(int64_t * d);
void function_22f0(int64_t * ptr);
int64_t function_2300(void);
int32_t * function_2310(void);
int32_t function_2320(char * s1, char * s2, int32_t n);
void function_2330(int32_t status);
int32_t function_2340(struct _IO_FILE * fp);
int32_t function_2350(char * s);
char * function_2360(char * domainname);
int32_t function_2370(struct _IO_FILE * stream);
struct passwd * function_2380(int32_t uid);
char * function_2390(char * domainname, char * dirname);
char * function_23a0(char * domainname, char * msgid, int32_t category);
int32_t function_23b0(void);
int32_t function_23c0(char * s);
void function_23d0(void);
int32_t function_23e0(int32_t argc, char ** argv, char * shortopts, struct option * longopts, int32_t * longind);
int32_t function_23f0(int32_t * pwc, char * s, int32_t n, struct _TYPEDEF___mbstate_t * p);
char * function_2400(char * s, int32_t c);
int32_t function_2410(int32_t fd, int32_t offset, int32_t whence);
int64_t * function_2420(int64_t * s, int32_t c, int32_t n);
int32_t function_2430(void);
int32_t function_2440(int64_t * s1, int64_t * s2, int32_t n);
int32_t function_2450(char * s, struct _IO_FILE * stream);
int32_t function_2460(char * s1, char * s2);
int32_t function_2470(int32_t c, struct _IO_FILE * stream);
int64_t * function_2480(int64_t * dest, int64_t * src, int32_t len, int32_t dstlen);
int32_t function_2490(struct _IO_FILE * stream);
int64_t * function_24a0(int32_t size);
int32_t function_24b0(struct _IO_FILE * stream);
char * function_24c0(int32_t item);
int32_t function_24d0(struct _IO_FILE * fp);
int64_t * function_24e0(int64_t * ptr, int32_t size);
char * function_24f0(int32_t category, char * locale);
int32_t function_2500(int32_t flag, char * format, ...);
void function_2510(int32_t status, int32_t errnum, char * format, ...);
int32_t function_2520(struct _IO_FILE * stream, int32_t off, int32_t whence);
int32_t function_2530(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle);
void function_2540(int32_t status);
int32_t function_2550(int64_t * ptr, int32_t size, int32_t n, struct _IO_FILE * s);
int32_t function_2560(struct _IO_FILE * stream, int32_t flag, char * format, ...);
int32_t function_2570(struct _TYPEDEF___mbstate_t * ps);
int32_t function_2580(int32_t wc);
int16_t ** function_2590(void);
int64_t function_25a0(void);
int64_t function_25b0(int64_t a1, int64_t str);
int64_t function_27e0(void);
int64_t function_2810(void);
int64_t function_2850(void);
int64_t function_2890(void);
int64_t function_28a0(int64_t a1, char * a2, int32_t a3, int32_t a4);
int64_t function_2990(int64_t a1);
int64_t function_2cd0(int64_t a1);
int64_t function_2d10(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_2e00(int64_t a1, int64_t a2);
int64_t function_2f60(int64_t a1, int64_t a2, char * a3, char * a4, char * a5, int64_t a6, int64_t a7, int64_t a8);
int64_t function_36e9(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7, int64_t a8);
int64_t function_4ae0(int64_t a1, int64_t * a2);
int64_t function_4c80(void);
int64_t function_4d00(int64_t a1, int64_t a2);
int64_t function_4d14(void);

// --------------------- Global Variables ---------------------

char * g1; // 0x5021
int64_t g2 = 0x692074736574005b; // 0x5022
int64_t g3 = 0x2200afa1009980e2; // 0x50d6
int64_t g4 = -0x5effd8ffddff505f; // 0x50da
int64_t g5 = 0x6507a100270022; // 0x50dd
int64_t g6 = 0x9880e2006507a1; // 0x50e1
int64_t g7 = 0x38314247009880e2; // 0x50e5
int32_t * g8 = (int32_t *)-0x221f000021e6; // 0x55c0
int32_t * g9 = (int32_t *)-0x1a7700001a42; // 0x55e4
int32_t * g10 = (int32_t *)-0x1c04000018d2; // 0x5610
int32_t * g11 = (int32_t *)-0x1d04000018a1; // 0x5710
int32_t * g12 = (int32_t *)-0x1e0700001ae0; // 0x5810
char (*g13)[5] = "help"; // 0x7be0
int32_t g14 = 17; // 0x7e4
int64_t g15; // 0x8008
int32_t g16 = 1; // 0x8020
int32_t g17 = 1; // 0x8024
int64_t g18 = 8; // 0x8040
int128_t g19; // 0x8080
char g21 = 0; // 0x80a0
int64_t g22 = 0; // 0x80c0
int64_t g23 = 0; // 0x81c0
int32_t g24;
int64_t * g20 = (int64_t *)&g19; // 0x8090

// ------- Dynamically Linked Functions Without Header --------

int32_t __cxa_atexit(void (*a1)(int64_t *), int64_t * a2, int64_t * a3);
void __cxa_finalize(int64_t * a1);
int32_t __fpending(struct _IO_FILE * a1);
int32_t __fprintf_chk(struct _IO_FILE * a1, int32_t a2, char * a3, ...);
int32_t __freading(struct _IO_FILE * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
int64_t * __memcpy_chk(int64_t * a1, int64_t * a2, int32_t a3, int32_t a4);
int32_t __printf_chk(int32_t a1, char * a2, ...);
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x2000 - 0x201b
int64_t function_2000(void) {
    int64_t result = 0; // 0x2012
    if (*(int64_t *)0x7fc0 != 0) {
        // 0x2014
        __gmon_start__();
        result = &g24;
    }
    // 0x2016
    return result;
}

// Address range: 0x22e0 - 0x22eb
void function_22e0(int64_t * d) {
    // 0x22e0
    __cxa_finalize(d);
}

// Address range: 0x22f0 - 0x22fb
void function_22f0(int64_t * ptr) {
    // 0x22f0
    free(ptr);
}

// Address range: 0x2300 - 0x230b
int64_t function_2300(void) {
    // 0x2300
    return abort();
}

// Address range: 0x2310 - 0x231b
int32_t * function_2310(void) {
    // 0x2310
    return __errno_location();
}

// Address range: 0x2320 - 0x232b
int32_t function_2320(char * s1, char * s2, int32_t n) {
    // 0x2320
    return strncmp(s1, s2, n);
}

// Address range: 0x2330 - 0x233b
void function_2330(int32_t status) {
    // 0x2330
    _exit(status);
}

// Address range: 0x2340 - 0x234b
int32_t function_2340(struct _IO_FILE * fp) {
    // 0x2340
    return __fpending(fp);
}

// Address range: 0x2350 - 0x235b
int32_t function_2350(char * s) {
    // 0x2350
    return puts(s);
}

// Address range: 0x2360 - 0x236b
char * function_2360(char * domainname) {
    // 0x2360
    return textdomain(domainname);
}

// Address range: 0x2370 - 0x237b
int32_t function_2370(struct _IO_FILE * stream) {
    // 0x2370
    return fclose(stream);
}

// Address range: 0x2380 - 0x238b
struct passwd * function_2380(int32_t uid) {
    // 0x2380
    return getpwuid(uid);
}

// Address range: 0x2390 - 0x239b
char * function_2390(char * domainname, char * dirname) {
    // 0x2390
    return bindtextdomain(domainname, dirname);
}

// Address range: 0x23a0 - 0x23ab
char * function_23a0(char * domainname, char * msgid, int32_t category) {
    // 0x23a0
    return dcgettext(domainname, msgid, category);
}

// Address range: 0x23b0 - 0x23bb
int32_t function_23b0(void) {
    // 0x23b0
    return __ctype_get_mb_cur_max();
}

// Address range: 0x23c0 - 0x23cb
int32_t function_23c0(char * s) {
    // 0x23c0
    return strlen(s);
}

// Address range: 0x23d0 - 0x23db
void function_23d0(void) {
    // 0x23d0
    __stack_chk_fail();
}

// Address range: 0x23e0 - 0x23eb
int32_t function_23e0(int32_t argc, char ** argv, char * shortopts, struct option * longopts, int32_t * longind) {
    // 0x23e0
    return getopt_long(argc, argv, shortopts, longopts, longind);
}

// Address range: 0x23f0 - 0x23fb
int32_t function_23f0(int32_t * pwc, char * s, int32_t n, struct _TYPEDEF___mbstate_t * p) {
    // 0x23f0
    return mbrtowc(pwc, s, n, p);
}

// Address range: 0x2400 - 0x240b
char * function_2400(char * s, int32_t c) {
    // 0x2400
    return strrchr(s, c);
}

// Address range: 0x2410 - 0x241b
int32_t function_2410(int32_t fd, int32_t offset, int32_t whence) {
    // 0x2410
    return lseek(fd, offset, whence);
}

// Address range: 0x2420 - 0x242b
int64_t * function_2420(int64_t * s, int32_t c, int32_t n) {
    // 0x2420
    return memset(s, c, n);
}

// Address range: 0x2430 - 0x243b
int32_t function_2430(void) {
    // 0x2430
    return geteuid();
}

// Address range: 0x2440 - 0x244b
int32_t function_2440(int64_t * s1, int64_t * s2, int32_t n) {
    // 0x2440
    return memcmp(s1, s2, n);
}

// Address range: 0x2450 - 0x245b
int32_t function_2450(char * s, struct _IO_FILE * stream) {
    // 0x2450
    return fputs_unlocked(s, stream);
}

// Address range: 0x2460 - 0x246b
int32_t function_2460(char * s1, char * s2) {
    // 0x2460
    return strcmp(s1, s2);
}

// Address range: 0x2470 - 0x247b
int32_t function_2470(int32_t c, struct _IO_FILE * stream) {
    // 0x2470
    return fputc_unlocked(c, stream);
}

// Address range: 0x2480 - 0x248b
int64_t * function_2480(int64_t * dest, int64_t * src, int32_t len, int32_t dstlen) {
    // 0x2480
    return __memcpy_chk(dest, src, len, dstlen);
}

// Address range: 0x2490 - 0x249b
int32_t function_2490(struct _IO_FILE * stream) {
    // 0x2490
    return fileno(stream);
}

// Address range: 0x24a0 - 0x24ab
int64_t * function_24a0(int32_t size) {
    // 0x24a0
    return malloc(size);
}

// Address range: 0x24b0 - 0x24bb
int32_t function_24b0(struct _IO_FILE * stream) {
    // 0x24b0
    return fflush(stream);
}

// Address range: 0x24c0 - 0x24cb
char * function_24c0(int32_t item) {
    // 0x24c0
    return nl_langinfo(item);
}

// Address range: 0x24d0 - 0x24db
int32_t function_24d0(struct _IO_FILE * fp) {
    // 0x24d0
    return __freading(fp);
}

// Address range: 0x24e0 - 0x24eb
int64_t * function_24e0(int64_t * ptr, int32_t size) {
    // 0x24e0
    return realloc(ptr, size);
}

// Address range: 0x24f0 - 0x24fb
char * function_24f0(int32_t category, char * locale) {
    // 0x24f0
    return setlocale(category, locale);
}

// Address range: 0x2500 - 0x250b
int32_t function_2500(int32_t flag, char * format, ...) {
    // 0x2500
    return __printf_chk(flag, format);
}

// Address range: 0x2510 - 0x251b
void function_2510(int32_t status, int32_t errnum, char * format, ...) {
    // 0x2510
    error(status, errnum, format);
}

// Address range: 0x2520 - 0x252b
int32_t function_2520(struct _IO_FILE * stream, int32_t off, int32_t whence) {
    // 0x2520
    return fseeko(stream, off, whence);
}

// Address range: 0x2530 - 0x253b
int32_t function_2530(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle) {
    // 0x2530
    return __cxa_atexit(func, arg, dso_handle);
}

// Address range: 0x2540 - 0x254b
void function_2540(int32_t status) {
    // 0x2540
    exit(status);
}

// Address range: 0x2550 - 0x255b
int32_t function_2550(int64_t * ptr, int32_t size, int32_t n, struct _IO_FILE * s) {
    // 0x2550
    return fwrite(ptr, size, n, s);
}

// Address range: 0x2560 - 0x256b
int32_t function_2560(struct _IO_FILE * stream, int32_t flag, char * format, ...) {
    // 0x2560
    return __fprintf_chk(stream, flag, format);
}

// Address range: 0x2570 - 0x257b
int32_t function_2570(struct _TYPEDEF___mbstate_t * ps) {
    // 0x2570
    return mbsinit(ps);
}

// Address range: 0x2580 - 0x258b
int32_t function_2580(int32_t wc) {
    // 0x2580
    return iswprint(wc);
}

// Address range: 0x2590 - 0x259b
int16_t ** function_2590(void) {
    // 0x2590
    return __ctype_b_loc();
}

// Address range: 0x25a0 - 0x25a5
int64_t function_25a0(void) {
    // 0x25a0
    abort();
    // UNREACHABLE
}

// Address range: 0x25b0 - 0x27b0
int64_t function_25b0(int64_t a1, int64_t str) {
    int64_t stream; // 0x2762
    if (str == 0) {
        // 0x274a
        stream = *(int64_t *)*(int64_t *)0x7ff0;
        fwrite((int64_t *)"A NULL argv[0] was passed through an exec system call.\n", 1, 55, (struct _IO_FILE *)stream);
        abort();
        // UNREACHABLE
    }
    char * found_char_pos = strrchr((char *)str, 47); // 0x25d6
    int64_t v1 = str; // 0x25e1
    if (found_char_pos != NULL) {
        int64_t v2 = (int64_t)found_char_pos; // 0x25d6
        int64_t str2 = v2 + 1; // 0x25e3
        v1 = str;
        if (str2 - str >= 7) {
            // 0x25f3
            v1 = str;
            if (strncmp((char *)(v2 - 6), "/.libs/", 7) == 0) {
                int32_t strncmp_rc = strncmp((char *)str2, "lt-", 3); // 0x261e
                v1 = str2;
                if (strncmp_rc == 0) {
                    int64_t v3 = v2 + 4; // 0x2717
                    *(int64_t *)*(int64_t *)0x7fd8 = v3;
                    v1 = v3;
                }
            }
        }
    }
    // 0x2630
    g23 = v1;
    *(int64_t *)*(int64_t *)0x7fc8 = v1;
    setlocale(LC_ALL, (char *)&g1);
    bindtextdomain("coreutils", "/usr/share/locale");
    textdomain("coreutils");
    function_4d00(0x4c80, (int64_t)"/usr/share/locale");
    function_2f60(a1 & 0xffffffff, str, "whoami", "GNU coreutils", "8.32", 1, 0x2990, (int64_t)"Richard Mlynarik");
    int32_t v4 = *(int32_t *)*(int64_t *)0x7fb8; // 0x26c5
    if (v4 != (int32_t)a1) {
        // 0x276f
        function_4ae0(*(int64_t *)(8 * (int64_t)v4 + str), &g18);
        error(0, (int32_t)"extra operand %s" ^ (int32_t)"extra operand %s", dcgettext(NULL, "extra operand %s", 5));
        return function_2990(1);
    }
    int32_t * err_num = __errno_location(); // 0x26d1
    *err_num = 0;
    int32_t uid = geteuid(); // 0x26df
    if (uid != -1) {
        goto lab_0x26f1;
    } else {
        // 0x26eb
        if (*err_num != 0) {
            goto lab_0x2723;
        } else {
            goto lab_0x26f1;
        }
    }
  lab_0x26f1:;
    struct passwd * str3 = getpwuid(uid); // 0x26f3
    if (str3 != NULL) {
        // 0x26fd
        puts((char *)*(int64_t *)str3);
        return 0;
    }
    goto lab_0x2723;
  lab_0x2723:
    // 0x2723
    error(1, *err_num, dcgettext(NULL, "cannot find name for user ID %lu", 5));
    // 0x274a
    stream = *(int64_t *)*(int64_t *)0x7ff0;
    fwrite((int64_t *)"A NULL argv[0] was passed through an exec system call.\n", 1, 55, (struct _IO_FILE *)stream);
    abort();
    // UNREACHABLE
}

// Address range: 0x27b0 - 0x27d6
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x27b0
    int64_t v1; // 0x27b0
    __libc_start_main(0x25b0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x27e0 - 0x2809
int64_t function_27e0(void) {
    // 0x27e0
    return 0x8098;
}

// Address range: 0x2810 - 0x2849
int64_t function_2810(void) {
    // 0x2810
    return 0;
}

// Address range: 0x2850 - 0x2889
int64_t function_2850(void) {
    // 0x2850
    if (g21 != 0) {
        // 0x2888
        int64_t result; // 0x2850
        return result;
    }
    // 0x285d
    if (*(int64_t *)0x7fe0 != 0) {
        // 0x286b
        __cxa_finalize((int64_t *)*(int64_t *)0x8008);
    }
    int64_t result2 = function_27e0(); // 0x2877
    g21 = 1;
    return result2;
}

// Address range: 0x2890 - 0x2899
int64_t function_2890(void) {
    // 0x2890
    return function_2810();
}

// Address range: 0x28a0 - 0x298b
int64_t function_28a0(int64_t a1, char * a2, int32_t a3, int32_t a4) {
    int32_t v1 = 0x1000000 * a3;
    char v2 = *(char *)(a1 + 7); // 0x28ac
    bool v3; // 0x28a0
    if (v1 == 0x5a000000 || v1 >> 24 < 90) {
        // 0x28ba
        v3 = (v2 & -33) == (char)a3;
    } else {
        // 0x2970
        v3 = v2 == (char)a3;
    }
    // 0x28c5
    if (!v3) {
        // 0x28d4
        return 0;
    }
    // 0x28ca
    if ((char)a3 == 0) {
        // 0x28d4
        return 1;
    }
    char v4 = *(char *)(a1 + 8); // 0x28e3
    int32_t v5 = 0x1000000 * a4;
    bool v6; // 0x28a0
    if (v5 == 0x5a000000 || v5 >> 24 < 90) {
        // 0x28f3
        v6 = (v4 & -33) == (char)a4;
    } else {
        // 0x2980
        v6 = v4 == (char)a4;
    }
    // 0x28fc
    if (!v6) {
        // 0x28d4
        return 0;
    }
    int64_t v7 = (int64_t)a2;
    if (v7 == a1 || (char)a4 == 0) {
        // 0x28d4
        return 1;
    }
    int64_t v8 = 9; // 0x2908
    unsigned char v9 = *(char *)(v8 + a1); // 0x2929
    int64_t v10 = v9; // 0x2929
    int64_t v11 = v9 == 90 | (int32_t)v9 < 90 ? v10 + 32 : v10;
    unsigned char v12 = *(char *)(v8 + v7); // 0x2941
    bool v13 = v12 == 90 | (int32_t)v12 < 90; // 0x2951
    char v14 = v11; // 0x295a
    while (v14 != 0) {
        // 0x2920
        v8++;
        if ((v13 ? v12 + 32 : v12) != v14) {
            // break -> 0x295e
            break;
        }
        v9 = *(char *)(v8 + a1);
        v10 = v9;
        v11 = v9 == 90 | (int32_t)v9 < 90 ? v10 + 32 : v10;
        v12 = *(char *)(v8 + v7);
        v13 = v12 == 90 | (int32_t)v12 < 90;
        v14 = v11;
    }
    int64_t v15 = v12; // 0x2941
    // 0x28d4
    return (int32_t)v11 == (int32_t)(v13 ? v15 + 32 : v15);
}

// Address range: 0x2990 - 0x2cc7
int64_t function_2990(int64_t a1) {
    // 0x2990
    __readfsqword(40);
    int32_t status = a1; // 0x29c3
    if (status != 0) {
        char * v1 = dcgettext(NULL, "Try '%s --help' for more information.\n", 5); // 0x29d0
        __fprintf_chk((struct _IO_FILE *)*(int64_t *)*(int64_t *)0x7ff0, 1, v1);
        // 0x29f1
        exit(status);
        // UNREACHABLE
    }
    // 0x29f8
    __printf_chk(1, dcgettext(NULL, "Usage: %s [OPTION]...\n", 5));
    int64_t * v2 = (int64_t *)*(int64_t *)0x7fb0; // 0x2a30
    int64_t v3 = *v2; // 0x2a30
    fputs_unlocked(dcgettext(NULL, "Print the user name associated with the current effective user ID.\nSame as id -un.\n\n", 5), (struct _IO_FILE *)v3);
    fputs_unlocked(dcgettext(NULL, "      --help     display this help and exit\n", 5), (struct _IO_FILE *)*v2);
    int64_t v4 = *v2; // 0x2a66
    fputs_unlocked(dcgettext(NULL, "      --version  output version information and exit\n", 5), (struct _IO_FILE *)v4);
    int64_t v5 = &g2; // bp-184, 0x2aa6
    int64_t v6 = &v5;
    int64_t v7 = v6 + 16; // 0x2b20
    int64_t str = *(int64_t *)v7; // 0x2b20
    while (str != 0) {
        // 0x2b2d
        if (strcmp("whoami", (char *)str) == 0) {
            // break -> 0x2b39
            break;
        }
        v6 = v7;
        v7 = v6 + 16;
        str = *(int64_t *)v7;
    }
    // 0x2b39
    __printf_chk(1, dcgettext(NULL, "\n%s online help: <%s>\n", 5));
    char * locale = setlocale(LC_MESSAGES, NULL);
    if (*(int64_t *)(v6 + 24) == 0) {
        if (locale == NULL) {
            goto lab_0x2c5e;
        } else {
            // 0x2c49
            if (strncmp(locale, "en_", 3) != 0) {
                goto lab_0x2ca0;
            } else {
                goto lab_0x2c5e;
            }
        }
    } else {
        if (locale == NULL) {
            goto lab_0x2ba6;
        } else {
            // 0x2b8d
            if (strncmp(locale, "en_", 3) != 0) {
                goto lab_0x2ca0;
            } else {
                goto lab_0x2ba6;
            }
        }
    }
  lab_0x2c5e:
    // 0x2c5e
    __printf_chk(1, dcgettext(NULL, "Full documentation <%s%s>\n", 5));
    // 0x2be3
    __printf_chk(1, dcgettext(NULL, "or available locally via: info '(coreutils) %s%s'\n", 5));
    // 0x29f1
    exit(status);
    // UNREACHABLE
  lab_0x2ba6:
    // 0x2ba6
    __printf_chk(1, dcgettext(NULL, "Full documentation <%s%s>\n", 5));
    // 0x2be3
    __printf_chk(1, dcgettext(NULL, "or available locally via: info '(coreutils) %s%s'\n", 5));
    // 0x29f1
    exit(status);
    // UNREACHABLE
  lab_0x2ca0:;
    int64_t v8 = *v2; // 0x2ca0
    fputs_unlocked(dcgettext(NULL, "Report any translation bugs to <https://translationproject.org/team/>\n", 5), (struct _IO_FILE *)v8);
    goto lab_0x2ba6;
}

// Address range: 0x2cd0 - 0x2d07
int64_t function_2cd0(int64_t a1) {
    // 0x2cd0
    error(g17, (int32_t)"memory exhausted" ^ (int32_t)"memory exhausted", "%s", dcgettext(NULL, "memory exhausted", 5));
    abort();
    // UNREACHABLE
}

// Address range: 0x2d10 - 0x2dfe
int64_t function_2d10(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    char * v1 = nl_langinfo(14); // 0x2d20
    int64_t result; // 0x2d9f
    if (v1 == NULL) {
        // 0x2d8e
        result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
        return result;
    }
    char v2 = *v1; // 0x2d2d
    if (v2 == 0) {
        // 0x2d8e
        result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
        return result;
    }
    int64_t v3 = (int64_t)v1; // 0x2d20
    char v4 = v3;
    char v5 = v2 & -33;
    if (v5 == 85) {
        // 0x2d3b
        if ((*(char *)(v3 + 1) & -33) != 84 || (*(char *)(v3 + 2) & -33) != 70 || *(char *)(v3 + 3) != 45 || *(char *)(v3 + 4) != 56) {
            // 0x2d8e
            result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
            return result;
        }
        // 0x2d5d
        if (*(char *)(v3 + 5) == 0) {
            // 0x2d63
            return v4 != 96 ? (int64_t)&g3 : (int64_t)&g7;
        }
        // 0x2d8e
        result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
        return result;
    }
    if (v5 != 71 || (*(char *)(v3 + 1) & -33) != 66 || *(char *)(v3 + 2) != 49 || *(char *)(v3 + 3) != 56 || *(char *)(v3 + 4) != 48 || *(char *)(v3 + 5) != 51 || *(char *)(v3 + 6) != 48) {
        // 0x2d8e
        result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
        return result;
    }
    // 0x2dce
    if ((int32_t)function_28a0(v3, "GB18030", 0, 0) != 0) {
        // 0x2de2
        return v4 != 96 ? (int64_t)&g4 : (int64_t)&g6;
    }
    // 0x2d8e
    result = (int32_t)a2 != 9 ? (int64_t)"'" : (int64_t)&g5;
    return result;
}

// Address range: 0x2e00 - 0x2f60
int64_t function_2e00(int64_t a1, int64_t a2) {
    struct _IO_FILE * stream = (struct _IO_FILE *)a1;
    int32_t v1 = __fpending(stream); // 0x2e0b
    int64_t v2; // 0x2e00
    int32_t v3 = (int32_t)v2 & 32; // 0x2e1e
    int32_t v4; // 0x2e00
    if (fileno(stream) < 0) {
        // 0x2e9f
        v4 = fclose(stream);
        goto lab_0x2ea4;
    } else {
        // 0x2e28
        if (__freading(stream) != 0) {
            // 0x2e80
            if (lseek(fileno(stream), 0, SEEK_CUR) != -1) {
                goto lab_0x2e31;
            } else {
                // 0x2e9f
                v4 = fclose(stream);
                goto lab_0x2ea4;
            }
        } else {
            goto lab_0x2e31;
        }
    }
  lab_0x2ea4:
    // 0x2ea4
    if (v3 != 0) {
        // 0x2f48
        if (v4 == 0) {
            // 0x2f50
            *__errno_location() = 0;
        }
        // 0x2e75
        return 0xffffffff;
    }
    // 0x2eac
    if (v4 == 0) {
        // 0x2e75
        return 0;
    }
    goto lab_0x2eb0;
  lab_0x2e31:;
    int32_t v7 = a1;
    if ((v7 & 256) == 0 | __freading(stream) == 0) {
        goto lab_0x2e41;
    } else {
        // 0x2edd
        if (*(int64_t *)(a1 + 16) == *(int64_t *)(a1 + 8)) {
            // 0x2f00
            if (*(int64_t *)(a1 + 40) != *(int64_t *)(a1 + 32)) {
                // 0x2ee7
                fseeko(stream, 0, SEEK_CUR);
                goto lab_0x2e41;
            } else {
                // 0x2f0a
                if (*(int64_t *)(a1 + 72) != 0) {
                    // 0x2ee7
                    fseeko(stream, 0, SEEK_CUR);
                    goto lab_0x2e41;
                } else {
                    int32_t v8 = lseek(fileno(stream), 0, SEEK_CUR); // 0x2f22
                    if (v8 != -1) {
                        // 0x2f31
                        *(int32_t *)a1 = v7 & -17;
                        *(int64_t *)(a1 + 144) = (int64_t)v8;
                    }
                    goto lab_0x2e41;
                }
            }
        } else {
            // 0x2ee7
            fseeko(stream, 0, SEEK_CUR);
            goto lab_0x2e41;
        }
    }
  lab_0x2eb0:
    // 0x2eb0
    if (v1 == 0) {
        // 0x2eb5
        return *__errno_location() != 9 ? 0xffffffff : 0;
    }
    // 0x2e75
    return 0xffffffff;
  lab_0x2e41:
    // 0x2e41
    if (fflush(stream) == 0) {
        // 0x2e9f
        v4 = fclose(stream);
        goto lab_0x2ea4;
    } else {
        int32_t * v5 = __errno_location(); // 0x2e4d
        int32_t v6 = *v5; // 0x2e55
        v4 = fclose(stream);
        if (v6 == 0) {
            goto lab_0x2ea4;
        } else {
            // 0x2e65
            *v5 = v6;
            if (v3 != 0) {
                // 0x2e75
                return 0xffffffff;
            }
            goto lab_0x2eb0;
        }
    }
}

// Address range: 0x2f60 - 0x36e9
int64_t function_2f60(int64_t a1, int64_t a2, char * a3, char * a4, char * a5, int64_t a6, int64_t a7, int64_t a8) {
    // 0x2f60
    int64_t v1; // 0x2f60
    if ((char)v1 != 0) {
        // 0x2f78
        int128_t v2; // 0x2f60
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = __readfsqword(40); // 0x2fd0
    int32_t * v4 = (int32_t *)*(int64_t *)0x7fe8; // 0x2fe3
    *v4 = 1;
    int32_t v5 = getopt_long((int32_t)a1, (char **)a2, (char *)&g1, (struct option *)&g13, NULL); // 0x2fec
    int64_t result2; // 0x2f60
    int64_t v6; // 0x2f60
    int64_t v7; // 0x357e
    switch (v5) {
        case -1: {
            int64_t result = v3 - __readfsqword(40); // 0x30b8
            if (result == 0) {
                // 0x30c7
                return result;
            }
            // 0x3564
            __stack_chk_fail();
            v7 = __readfsqword(40);
            char * locale = setlocale(LC_CTYPE, NULL); // 0x3591
            v6 = (int64_t)&g13;
            result2 = 0;
            if (locale != NULL) {
                uint32_t len = strlen(locale); // 0x35a8
                v6 = (int64_t)&g13;
                result2 = 0;
                if (len < 257) {
                    // 0x35e0
                    int64_t v8; // bp-688, 0x2f60
                    int64_t * str = __memcpy_chk(&v8, (int64_t *)locale, len + 1, 257); // 0x35ef
                    v6 = 257;
                    result2 = 0;
                    char v9; // 0x2f60
                    if (v9 == 0 != ((char)v8 == 67)) {
                        // 0x35fd
                        v6 = 257;
                        result2 = strcmp((char *)str, "POSIX") != 0;
                    }
                }
            }
            // break -> 0x35b5
            break;
        }
        case 104: {
            // 0x30a6
            function_2990(0);
            // UNREACHABLE
        }
        default: {
            if (v5 != 118) {
                // 0x309b
                function_2990((int64_t)g17);
                // UNREACHABLE
            }
            int64_t v10 = *(int64_t *)*(int64_t *)0x7fb0; // 0x3053
            int64_t v11; // bp+16, 0x2f60
            int64_t v12 = &v11; // 0x3056
            int64_t v13 = 0;
            int64_t v14 = *(int64_t *)v12; // 0x306e
            int64_t v15; // bp-328, 0x2f60
            *(int64_t *)(8 * v13 + (int64_t)&v15) = v14;
            while (v14 != 0) {
                // 0x307a
                v12 += 8;
                if (v13 == 9) {
                    struct _IO_FILE * stream = (struct _IO_FILE *)v10; // 0x3493
                    __fprintf_chk(stream, 1, "%s (%s) %s\n", "whoami", "GNU coreutils", a5);
                    char * v16 = dcgettext(NULL, "(C)", 5); // 0x34a6
                    __fprintf_chk(stream, 1, "Copyright %s %d Free Software Foundation, Inc.", v16, (int64_t)&g14);
                    fputc_unlocked(10, stream);
                    __fprintf_chk(stream, 1, dcgettext(NULL, "License GPLv3+: GNU GPL version 3 or later <%s>.\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n", 5));
                    fputc_unlocked(10, stream);
                    __fprintf_chk(stream, 1, dcgettext(NULL, "Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n", 5));
                    goto lab_0x322b;
                }
                v13++;
                v14 = *(int64_t *)v12;
                *(int64_t *)(8 * v13 + (int64_t)&v15) = v14;
            }
            uint64_t v17 = v13 - 1; // 0x310e
            struct _IO_FILE * stream2 = (struct _IO_FILE *)v10; // 0x3112
            __fprintf_chk(stream2, 1, "%s (%s) %s\n", "whoami", "GNU coreutils", a5);
            char * v18 = dcgettext(NULL, "(C)", 5); // 0x3125
            __fprintf_chk(stream2, 1, "Copyright %s %d Free Software Foundation, Inc.", v18, (int64_t)&g14);
            fputc_unlocked(10, stream2);
            __fprintf_chk(stream2, 1, dcgettext(NULL, "License GPLv3+: GNU GPL version 3 or later <%s>.\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n", 5));
            fputc_unlocked(10, stream2);
            if (v17 < 9) {
                int32_t v19 = *(int32_t *)(4 * v17 + (int64_t)&g8); // 0x31a0
                return (int64_t)v19 + (int64_t)&g8;
            }
          lab_0x322b:
            // 0x322b
            exit(0);
            // UNREACHABLE
        }
    }
    // 0x35b5
    if (v7 == __readfsqword(40)) {
        // 0x30c7
        return result2;
    }
    // 0x362d
    __stack_chk_fail();
    __readfsqword(40);
    __ctype_get_mb_cur_max();
    if ((int32_t)v6 < 11) {
        int32_t v20 = *(int32_t *)((4 * v6 & 0x3fffffffc) + (int64_t)&g9); // 0x36df
        return (int64_t)v20 + (int64_t)&g9;
    }
    abort();
    // UNREACHABLE
}

// Address range: 0x36e9 - 0x4adc
int64_t function_36e9(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7, int64_t a8) {
    // 0x36e9
    int64_t v1; // 0x36e9
    char * str; // 0x36e9
    char * v2; // 0x36e9
    int64_t v3; // 0x36e9
    if ((int32_t)v3 != 10) {
        // 0x36ef
        v2 = dcgettext(NULL, "`", 5);
        str = dcgettext(NULL, "'", 5);
        v1 = v3 & 0xffffffff;
    }
    int64_t v4 = 0; // 0x3756
    if ((int32_t)v3 == 0) {
        char v5 = *v2; // 0x47c7
        v4 = 0;
        if (v5 != 0) {
            uint64_t v6 = 0;
            if (v3 > v6) {
                // 0x47dd
                *(char *)(v6 + v3) = v5;
            }
            int64_t v7 = v6 + 1; // 0x47e2
            char v8 = *(char *)(v7 + (int64_t)v2); // 0x47e6
            v4 = v7;
            while (v8 != 0) {
                // 0x47d8
                v6 = v7;
                if (v3 > v6) {
                    // 0x47dd
                    *(char *)(v6 + v3) = v8;
                }
                // 0x47e2
                v7 = v6 + 1;
                v8 = *(char *)(v7 + (int64_t)v2);
                v4 = v7;
            }
        }
    }
    int32_t len = strlen(str); // 0x3778
    char * str2 = (char *)a8;
    int64_t v9 = v3 + 1;
    int32_t v10 = (int32_t)v3 != 0; // 0x3798
    int64_t v11 = (int64_t)str; // 0x3798
    int32_t v12 = len; // 0x3798
    int64_t v13 = a7; // 0x3798
    int64_t v14 = v1 & 0xffffffff; // 0x3798
    int64_t v15 = v4; // 0x3798
    int32_t v16; // 0x36e9
    int64_t v17; // 0x36e9
    bool v18; // 0x36e9
    int64_t v19; // 0x36e9
    int64_t v20; // 0x36e9
    int64_t v21; // 0x36e9
    int64_t v22; // 0x36e9
    int64_t v23; // 0x36e9
    int64_t v24; // 0x36e9
    int64_t v25; // 0x36e9
    int64_t v26; // 0x36e9
    int64_t v27; // 0x36e9
    int64_t v28; // 0x36e9
    int64_t v29; // 0x36e9
    int64_t v30; // 0x36e9
    int64_t v31; // 0x36e9
    int64_t v32; // 0x36e9
    int64_t v33; // 0x36e9
    int64_t v34; // 0x36e9
    int64_t v35; // 0x36e9
    int64_t v36; // 0x36e9
    int64_t v37; // 0x36e9
    int64_t v38; // 0x36e9
    int64_t v39; // 0x36e9
    int64_t v40; // 0x36e9
    int64_t v41; // 0x36e9
    int64_t v42; // 0x36e9
    int64_t v43; // 0x36e9
    int64_t v44; // 0x36e9
    int64_t v45; // 0x36e9
    int64_t v46; // 0x36e9
    int64_t v47; // 0x36e9
    int64_t v48; // 0x36e9
    int64_t v49; // 0x36e9
    int64_t v50; // 0x36e9
    int64_t v51; // 0x36e9
    int64_t v52; // 0x36e9
    int64_t v53; // 0x36e9
    int64_t v54; // 0x36e9
    int64_t v55; // 0x36e9
    int64_t v56; // 0x36e9
    int64_t v57; // 0x36e9
    int64_t v58; // 0x36e9
    int64_t v59; // 0x36e9
    int64_t v60; // 0x36e9
    int64_t v61; // 0x36e9
    int64_t v62; // 0x36e9
    int64_t v63; // 0x36e9
    int64_t v64; // 0x36e9
    int64_t v65; // 0x36e9
    int64_t v66; // 0x36e9
    int64_t v67; // 0x36e9
    int64_t v68; // 0x36e9
    int64_t v69; // 0x36e9
    int64_t v70; // 0x36e9
    int64_t v71; // 0x36e9
    int64_t v72; // 0x36e9
    int64_t v73; // 0x36e9
    int64_t v74; // 0x36e9
    int64_t v75; // 0x36e9
    int64_t v76; // 0x36e9
    int64_t v77; // 0x36e9
    int64_t v78; // 0x36e9
    int64_t v79; // 0x36e9
    int64_t v80; // 0x36e9
    int64_t v81; // 0x36e9
    int64_t v82; // 0x36e9
    int64_t v83; // 0x36e9
    int64_t v84; // 0x36e9
    int64_t v85; // 0x36e9
    int64_t v86; // 0x36e9
    int64_t v87; // 0x36e9
    int64_t v88; // 0x36e9
    int64_t v89; // 0x36e9
    int64_t v90; // 0x36e9
    int64_t v91; // 0x36e9
    int64_t v92; // 0x36e9
    int64_t v93; // 0x36e9
    int64_t v94; // 0x36e9
    int64_t v95; // 0x36e9
    int64_t v96; // 0x36e9
    int64_t result; // 0x36e9
    int64_t v97; // 0x36e9
    int64_t v98; // 0x36e9
    int64_t v99; // 0x36e9
    int64_t v100; // 0x36e9
    int64_t v101; // 0x36e9
    int64_t v102; // 0x36e9
    int64_t v103; // 0x36e9
    int64_t v104; // 0x36e9
    int64_t v105; // 0x36e9
    int64_t v106; // 0x36e9
    int64_t v107; // 0x36e9
    int32_t v108; // 0x36e9
    int64_t v109; // 0x36e9
    int64_t v110; // 0x36e9
    int64_t v111; // 0x36e9
    int32_t v112; // 0x36e9
    int64_t str3; // 0x37f4
    int64_t v113; // 0x3e00
    while (true) {
      lab_0x37a1:
        // 0x37a1
        v110 = v109;
        v111 = v13;
        int32_t n = v12;
        int64_t v114 = v11;
        v108 = v10;
        int64_t v115 = n;
        int64_t * str4 = (int64_t *)v114;
        v18 = v108 == 0 | n == 0;
        int64_t v116 = v108 ^ 1;
        char * v117 = (char *)v114;
        v93 = 0;
        v23 = v53;
        v51 = 0;
        v62 = v76;
        v72 = v14;
        v79 = v15;
        while (true) {
          lab_0x37c0:
            // 0x37c0
            v80 = v79;
            v73 = v72;
            int64_t v118 = v62;
            int64_t v119 = v51;
            int64_t v120 = v23;
            v94 = v93;
            bool v121 = v94 == v118; // 0x37cb
            if (v118 == -1) {
                // 0x37cd
                v121 = *(char *)(v94 + a8) == 0;
            }
            // 0x37db
            v112 = v73;
            if (v121) {
                // 0x449d
                v58 = v120;
                v77 = v118;
                if (((char)(v108 & (int32_t)(v112 == 2)) & (char)(v80 == 0)) != 0) {
                    // break -> 0x3c88
                    break;
                }
                int64_t v122 = v112 == 2;
                int64_t v123 = v122 & v116;
                int64_t v124 = v80; // 0x48c2
                if (v114 != 0 && (v123 == 0 ? v116 : v123) != 0) {
                    char v125 = *v117; // 0x48c8
                    v124 = v80;
                    if (v125 != 0) {
                        char v126 = v125; // 0x48da
                        uint64_t v127 = v80;
                        if (v120 > v127) {
                            // 0x48e2
                            *(char *)(v127 + v3) = v126;
                        }
                        int64_t v128 = v127 + 1; // 0x48e5
                        char v129 = *(char *)(v114 - v80 + v128); // 0x48e9
                        v124 = v128;
                        while (v129 != 0) {
                            // 0x48dd
                            v127 = v128;
                            if (v120 > v127) {
                                // 0x48e2
                                *(char *)(v127 + v3) = v129;
                            }
                            // 0x48e5
                            v128 = v127 + 1;
                            v129 = *(char *)(v114 - v80 + v128);
                            v124 = v128;
                        }
                    }
                }
                int64_t v130 = v124;
                if (v120 > v130) {
                    // 0x49c2
                    *(char *)(v130 + v3) = 0;
                }
                // 0x48fd
                result = v130;
                if (v3 == __readfsqword(40)) {
                  lab_0x39f1_2:
                    // 0x39f1
                    return result;
                }
                // 0x4ab7
                __stack_chk_fail();
                v17 = v122;
                v96 = &g24;
                v32 = v120;
                v50 = v119;
                v69 = v118;
                v78 = v130;
                goto lab_0x4abc;
            } else {
                // 0x37e4
                str3 = v94 + a8;
                if (v112 == 2) {
                    char v131 = *(char *)str3; // 0x3e00
                    v113 = v131;
                    if (v131 > 63) {
                        if (v131 > 122) {
                            // 0x3f50
                            v90 = 0;
                            v31 = v120;
                            v49 = v119;
                            v68 = v118;
                            if (v131 == 125) {
                                goto lab_0x43e0;
                            } else {
                                if (v131 > 125) {
                                    // 0x3f5f
                                    v104 = 126;
                                    v85 = 0;
                                    v22 = v120;
                                    v41 = v119;
                                    v59 = v118;
                                    if (v131 == 126) {
                                        goto lab_0x3da0;
                                    } else {
                                        // 0x3f6d
                                        v100 = v113;
                                        v83 = 0;
                                        v19 = v120;
                                        v38 = v119;
                                        v55 = v118;
                                        v102 = v113;
                                        v86 = 0;
                                        v24 = v120;
                                        v42 = v119;
                                        v60 = v118;
                                        if (v110 == 1) {
                                            goto lab_0x3a20;
                                        } else {
                                            goto lab_0x3f79;
                                        }
                                    }
                                } else {
                                    // 0x423e
                                    v105 = 123;
                                    v87 = 0;
                                    v25 = v120;
                                    v43 = v119;
                                    v61 = v118;
                                    if (v131 != 123) {
                                        // 0x39b0
                                        v98 = v113;
                                        v92 = 0;
                                        v34 = v120;
                                        v36 = v119;
                                        v71 = v118;
                                        v99 = v113;
                                        v82 = 0;
                                        v35 = v120;
                                        v37 = v119;
                                        v54 = v118;
                                        if (v131 != 124) {
                                            goto lab_0x3a0b;
                                        } else {
                                            goto lab_0x39b7;
                                        }
                                    } else {
                                        goto lab_0x424c;
                                    }
                                }
                            }
                        } else {
                            // 0x3edd
                            v99 = 64;
                            v82 = 0;
                            v35 = v120;
                            v37 = v119;
                            v54 = v118;
                            if (v131 == 64) {
                                goto lab_0x3a0b;
                            } else {
                                unsigned char v132 = (v131 + 63) % 64;
                                int64_t v133 = v132 == 0 ? 1 : 1 << (int64_t)v132;
                                v16 = v112;
                                v101 = v113;
                                v84 = 0;
                                v20 = v120;
                                v39 = v119;
                                v56 = v118;
                                v75 = v73;
                                if ((v133 & 0x3ffffff53ffffff) != 0) {
                                    goto lab_0x3a78;
                                } else {
                                    // 0x3f04
                                    v98 = v113;
                                    v92 = 0;
                                    v34 = v120;
                                    v36 = v119;
                                    v71 = v118;
                                    if ((v133 & 0xa4000000) != 0) {
                                        goto lab_0x39b7;
                                    } else {
                                        // 0x3f0f
                                        if (v131 != 92) {
                                            goto lab_0x3a0b;
                                        } else {
                                            if (v112 == 2) {
                                                // 0x4540
                                                v58 = v120;
                                                v77 = v118;
                                                v29 = v120;
                                                v47 = v119;
                                                v66 = v118;
                                                if (v108 != 0) {
                                                    // break -> 0x3c88
                                                    break;
                                                }
                                                goto lab_0x4347;
                                            } else {
                                                // 0x3f22
                                                v103 = v113;
                                                v21 = v120;
                                                v40 = v119;
                                                v57 = v118;
                                                v29 = v120;
                                                v47 = v119;
                                                v66 = v118;
                                                if (((char)(n != 0) & (char)v108) != 0) {
                                                    goto lab_0x4347;
                                                } else {
                                                    goto lab_0x3c33;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        // 0x3e0c
                        v99 = v113;
                        v82 = 0;
                        v35 = v120;
                        v37 = v119;
                        v54 = v118;
                        if (v131 < 64) {
                            // break (via goto) -> 0x3e1d
                            goto lab_0x3e1d;
                        }
                        goto lab_0x3a0b;
                    }
                } else {
                    // 0x3801
                    v27 = v120;
                    v45 = v119;
                    v64 = v118;
                    if (n == 0) {
                        goto lab_0x4280;
                    } else {
                        int64_t v134 = v119; // 0x3817
                        int64_t len2 = v118; // 0x3817
                        if (n != 1 && v118 == -1) {
                            // 0x381f
                            v134 = v119 % 256;
                            len2 = strlen(str2);
                        }
                        int64_t v135 = len2;
                        int64_t v136 = v134;
                        v27 = v120;
                        v45 = v136;
                        v64 = v135;
                        if (v94 + v115 > v135) {
                            goto lab_0x4280;
                        } else {
                            int32_t memcmp_rc = memcmp((int64_t *)str3, str4, n); // 0x3885
                            int64_t v137 = v136 % 256; // 0x3897
                            int64_t v138 = 0x100000000000000 * v120 >> 56; // 0x389d
                            v27 = v138;
                            v45 = v137;
                            v64 = v135;
                            if (memcmp_rc != 0) {
                                goto lab_0x4280;
                            } else {
                                if (v108 != 0) {
                                    // 0x39f1
                                    result = memcmp_rc;
                                    return result;
                                }
                                char v139 = *(char *)str3; // 0x38b3
                                int64_t v140 = v139; // 0x38b3
                                if (v139 > 63) {
                                    if (v139 > 122) {
                                        // 0x4460
                                        v90 = 1;
                                        v31 = v138;
                                        v49 = v137;
                                        v68 = v135;
                                        if (v139 == 125) {
                                            goto lab_0x43e0;
                                        } else {
                                            if (v139 > 125) {
                                                // 0x446b
                                                v99 = v140;
                                                v82 = 1;
                                                v35 = v138;
                                                v37 = v137;
                                                v54 = v135;
                                                v95 = 1;
                                                v30 = v138;
                                                v48 = v137;
                                                v67 = v135;
                                                if (v139 == 126) {
                                                    goto lab_0x439a;
                                                } else {
                                                    goto lab_0x3a0b;
                                                }
                                            } else {
                                                // 0x447c
                                                v99 = v140;
                                                v82 = 1;
                                                v35 = v138;
                                                v37 = v137;
                                                v54 = v135;
                                                v105 = 123;
                                                v87 = 1;
                                                v25 = v138;
                                                v43 = v137;
                                                v61 = v135;
                                                v106 = 124;
                                                v88 = 1;
                                                v26 = v138;
                                                v44 = v137;
                                                v63 = v135;
                                                switch (v139) {
                                                    case 123: {
                                                        goto lab_0x424c;
                                                    }
                                                    case 124: {
                                                        goto lab_0x4270;
                                                    }
                                                    default: {
                                                        goto lab_0x3a0b;
                                                    }
                                                }
                                            }
                                        }
                                    } else {
                                        // 0x441d
                                        v99 = 64;
                                        v82 = 1;
                                        v35 = v138;
                                        v37 = v137;
                                        v54 = v135;
                                        if (v139 == 64) {
                                            goto lab_0x3a0b;
                                        } else {
                                            unsigned char v141 = (v139 + 63) % 64;
                                            int64_t v142 = v141 == 0 ? 1 : 1 << (int64_t)v141;
                                            v107 = v140;
                                            v91 = 1;
                                            v33 = v138;
                                            v52 = v137;
                                            v70 = v135;
                                            v74 = v73;
                                            v81 = v80;
                                            if ((v142 & 0x3ffffff53ffffff) != 0) {
                                                goto lab_0x3900;
                                            } else {
                                                // 0x4447
                                                v106 = v140;
                                                v88 = 1;
                                                v26 = v138;
                                                v44 = v137;
                                                v63 = v135;
                                                v97 = v140;
                                                v89 = 1;
                                                v28 = v138;
                                                v46 = v137;
                                                v65 = v135;
                                                if ((v142 & 0xa4000000) != 0) {
                                                    goto lab_0x4270;
                                                } else {
                                                    goto lab_0x4322;
                                                }
                                            }
                                        }
                                    }
                                } else {
                                    // 0x38bf
                                    v99 = v140;
                                    v82 = 1;
                                    v35 = v138;
                                    v37 = v137;
                                    v54 = v135;
                                    if (v139 < 64) {
                                        int32_t v143 = *(int32_t *)(4 * v140 + (int64_t)&g10); // 0x38da
                                        return (int64_t)v143 + (int64_t)&g10;
                                    }
                                    goto lab_0x3a0b;
                                }
                            }
                        }
                    }
                }
            }
        }
        goto lab_0x3c88_2;
    }
  lab_0x3e1d:;
    int32_t v144 = *(int32_t *)(4 * v113 + (int64_t)&g11); // 0x3e27
    return (int64_t)v144 + (int64_t)&g11;
  lab_0x3c50_2:
    // 0x3c50
    result = 0;
    int64_t v145; // 0x36e9
    v58 = v145;
    int64_t v146; // 0x36e9
    v77 = v146;
    bool v147; // 0x36e9
    if (!v147) {
        return result;
    } else {
        goto lab_0x3c88_2;
    }
  lab_0x4105:;
    // 0x4105
    int64_t v148; // 0x36e9
    int64_t v149 = v148; // 0x4109
    int64_t v150; // 0x36e9
    int64_t v151 = v150; // 0x4109
    int64_t v152; // 0x36e9
    int64_t v153 = v152; // 0x4109
    int64_t v154; // 0x36e9
    int64_t v155 = 0x100000000000000 * v154 >> 56; // 0x4109
    int64_t v156; // 0x36e9
    int64_t v157 = v156; // 0x4109
    int64_t v158; // 0x36e9
    int64_t v159 = v158; // 0x4109
    int64_t v160; // 0x4004
    int64_t v161 = v160 & 0xffffffff; // 0x4109
    int64_t v162; // 0x36e9
    if (v162 < 2) {
        goto lab_0x3a6d;
    } else {
        goto lab_0x410f;
    }
  lab_0x47f4:
    // 0x47f4
    v148 = 1;
    int64_t v163; // 0x36e9
    v162 = v163;
    int64_t v164; // 0x402c
    int64_t v165 = v164; // 0x4837
    int64_t v166 = v163; // 0x4837
    if (v158 > v164) {
        int64_t v167 = v166;
        v148 = 1;
        v162 = v167;
        while (*(char *)(v165 + a8) != 0) {
            int64_t v168 = v167 + 1; // 0x4840
            int64_t v169 = v168 + v94; // 0x4844
            v148 = 1;
            v162 = v168;
            v165 = v169;
            v166 = v168;
            if (v158 <= v169) {
                // break -> 0x4105
                break;
            }
            v167 = v166;
            v148 = 1;
            v162 = v167;
        }
    }
    goto lab_0x4105;
  lab_0x3984:;
    // 0x3984
    int64_t v170; // 0x36e9
    uint64_t v171 = v170;
    int64_t v172; // 0x36e9
    int64_t v173; // 0x36e9
    if (v171 < v172) {
        // 0x3989
        *(char *)(v171 + v3) = (char)v173;
    }
    // 0x398d
    int64_t v174; // 0x36e9
    v93 = v174;
    v23 = v172;
    int64_t v175; // 0x36e9
    v51 = v175;
    int64_t v176; // 0x36e9
    v62 = v176;
    int64_t v177; // 0x36e9
    v72 = v177;
    v79 = v171 + 1;
    goto lab_0x37c0;
  lab_0x407e:;
    // 0x407e
    uint32_t v178; // 0x4042
    int64_t v179 = v178; // 0x4042
    int64_t v180; // 0x36e9
    if ((int32_t)v160 == 2 && v108 != 0 && v178 >= 2) {
        int64_t v181 = v180 + 1; // 0x4633
        char v182 = *(char *)v181; // 0x4645
        if (v182 < 125) {
            if ((1 << (int64_t)((v182 + 37) % 64) & 0x20000002b) != 0) {
                // 0x465f
                v58 = 0x100000000000000 * v154 >> 56;
                v77 = v158;
                goto lab_0x3c88_2;
            }
        }
        // 0x4638
        v181++;
        while (v180 + v179 != v181) {
            // 0x4645
            v182 = *(char *)v181;
            if (v182 < 125) {
                if ((1 << (int64_t)((v182 + 37) % 64) & 0x20000002b) != 0) {
                    // 0x465f
                    v58 = 0x100000000000000 * v154 >> 56;
                    v77 = v158;
                    goto lab_0x3c88_2;
                }
            }
            // 0x4638
            v181++;
        }
    }
    // 0x4090
    int32_t pwc; // bp+172, 0x36e9
    int32_t wc = pwc; // 0x4090
    int64_t v183 = v179; // 0x4090
    goto lab_0x4097;
  lab_0x4097:;
    int64_t v184 = v183 + v163; // 0x40ae
    int32_t v185; // 0x36e9
    int32_t v186 = iswprint(wc) == 0 ? 0 : v185; // 0x40b1
    int64_t ps; // bp+176, 0x36e9
    int32_t v187 = mbsinit((struct _TYPEDEF___mbstate_t *)&ps); // 0x40b5
    int32_t v188 = v186; // 0x40bc
    int64_t v189 = v184; // 0x40bc
    int32_t v190 = v186; // 0x40bc
    int64_t v191 = v184; // 0x40bc
    if (v187 != 0) {
        // break -> 0x40c2
        goto lab_0x40c2;
    }
    goto lab_0x401a;
  lab_0x4abc:;
    int64_t v193 = 126; // 0x4ace
    int64_t v194 = v17; // 0x4ace
    int64_t v195 = v96 & 0xffffffff; // 0x4ace
    int64_t v196 = v32; // 0x4ace
    int64_t v197 = v50; // 0x4ace
    int64_t v198 = v69; // 0x4ace
    int64_t v199 = v73; // 0x4ace
    int64_t v200 = v78; // 0x4ace
    goto lab_0x3a81;
  lab_0x3a81:;
    int64_t v201 = v200;
    int64_t v202 = v199;
    int64_t v203 = v198;
    int64_t v204 = v197;
    int64_t v205 = v196;
    int64_t v206 = v195;
    int64_t v207 = v193;
    v107 = v207;
    v91 = v206;
    v33 = v205;
    v52 = v204;
    v70 = v203;
    v74 = v202;
    v81 = v201;
    int64_t v208; // 0x36e9
    int64_t v209; // 0x36e9
    int64_t v210; // 0x36e9
    int64_t v211; // 0x36e9
    int64_t v212; // 0x36e9
    int64_t v213; // 0x36e9
    int64_t v214; // 0x36e9
    int64_t v215; // 0x36e9
    int64_t v216; // 0x36e9
    int64_t v217; // 0x36e9
    int64_t v218; // 0x36e9
    int64_t v219; // 0x36e9
    if (v108 != 0 || (char)v194 == 0) {
        goto lab_0x3900;
    } else {
        // 0x3aa0
        v219 = v207;
        v209 = v205;
        v211 = v204;
        v213 = v203;
        v215 = v202;
        v217 = v201;
        v218 = v207;
        v208 = v205;
        v210 = v204;
        v212 = v203;
        v214 = v202;
        v216 = v201;
        if ((char)v206 != 0) {
            goto lab_0x3925;
        } else {
            goto lab_0x3aa9;
        }
    }
  lab_0x4280:;
    int64_t v220 = v64;
    int64_t v221 = v45;
    int64_t v222 = v27;
    char v223 = *(char *)str3; // 0x4280
    int64_t v224 = v223; // 0x4280
    if (v223 > 63) {
        if (v223 > 122) {
            // 0x4388
            v105 = 125;
            v87 = 0;
            v25 = v222;
            v43 = v221;
            v61 = v220;
            if (v223 == 125) {
                goto lab_0x424c;
            } else {
                if (v223 > 125) {
                    // 0x438f
                    v99 = v224;
                    v82 = 0;
                    v35 = v222;
                    v37 = v221;
                    v54 = v220;
                    v95 = 0;
                    v30 = v222;
                    v48 = v221;
                    v67 = v220;
                    if (v223 != 126) {
                        goto lab_0x3a0b;
                    } else {
                        goto lab_0x439a;
                    }
                } else {
                    // 0x43b9
                    v99 = v224;
                    v82 = 0;
                    v35 = v222;
                    v37 = v221;
                    v54 = v220;
                    v105 = 123;
                    v87 = 0;
                    v25 = v222;
                    v43 = v221;
                    v61 = v220;
                    v106 = 124;
                    v88 = 0;
                    v26 = v222;
                    v44 = v221;
                    v63 = v220;
                    switch (v223) {
                        case 123: {
                            goto lab_0x424c;
                        }
                        case 124: {
                            goto lab_0x4270;
                        }
                        default: {
                            goto lab_0x3a0b;
                        }
                    }
                }
            }
        } else {
            // 0x42e9
            v99 = 64;
            v82 = 0;
            v35 = v222;
            v37 = v221;
            v54 = v220;
            if (v223 == 64) {
                goto lab_0x3a0b;
            } else {
                unsigned char v225 = (v223 + 63) % 64;
                int64_t v226 = v225 == 0 ? 1 : 1 << (int64_t)v225;
                v107 = v224;
                v91 = 0;
                v33 = v222;
                v52 = v221;
                v70 = v220;
                v74 = v73;
                v81 = v80;
                if ((v226 & 0x3ffffff53ffffff) != 0) {
                    goto lab_0x3900;
                } else {
                    // 0x4312
                    v106 = v224;
                    v88 = 0;
                    v26 = v222;
                    v44 = v221;
                    v63 = v220;
                    v97 = v224;
                    v89 = 0;
                    v28 = v222;
                    v46 = v221;
                    v65 = v220;
                    if ((v226 & 0xa4000000) != 0) {
                        goto lab_0x4270;
                    } else {
                        goto lab_0x4322;
                    }
                }
            }
        }
    } else {
        // 0x4288
        v99 = v224;
        v82 = 0;
        v35 = v222;
        v37 = v221;
        v54 = v220;
        if (v223 < 64) {
            int32_t v227 = *(int32_t *)(4 * v224 + (int64_t)&g12); // 0x42a3
            return (int64_t)v227 + (int64_t)&g12;
        }
        goto lab_0x3a0b;
    }
  lab_0x3900:;
    int64_t v228 = v81;
    int64_t v229 = v74;
    int64_t v230 = v70;
    int64_t v231 = v52;
    int64_t v232 = v33;
    int64_t v233 = v91;
    int64_t v234 = v107;
    if (v111 == 0) {
        goto lab_0x391c;
    } else {
        int32_t v235 = *(int32_t *)((v234 / 8 & 28) + v111); // 0x3912
        v219 = v234;
        v209 = v232;
        v211 = v231;
        v213 = v230;
        v215 = v229;
        v217 = v228;
        if ((v235 & 1 << (int32_t)v234 % 32) != 0) {
            goto lab_0x3925;
        } else {
            goto lab_0x391c;
        }
    }
  lab_0x3a0b:
    // 0x3a0b
    v100 = v99;
    v83 = v82;
    v19 = v35;
    v38 = v37;
    v55 = v54;
    v102 = v99;
    v86 = v82;
    v24 = v35;
    v42 = v37;
    v60 = v54;
    if (v110 != 1) {
        goto lab_0x3f79;
    } else {
        goto lab_0x3a20;
    }
  lab_0x391c:
    // 0x391c
    v219 = v234;
    v209 = v232;
    v211 = v231;
    v213 = v230;
    v215 = v229;
    v217 = v228;
    v218 = v234;
    v208 = v232;
    v210 = v231;
    v212 = v230;
    v214 = v229;
    v216 = v228;
    if ((char)v233 == 0) {
        goto lab_0x3aa9;
    } else {
        goto lab_0x3925;
    }
  lab_0x3925:;
    int64_t v236 = v219; // 0x3933
    bool v237 = (int32_t)v215 == 2; // 0x3933
    int64_t v238 = v209; // 0x3933
    int64_t v239 = v211; // 0x3933
    int64_t v240 = v213; // 0x3933
    int64_t v241 = v215; // 0x3933
    int64_t v242 = v217; // 0x3933
    v147 = (int32_t)v215 == 2;
    v145 = v209;
    v146 = v213;
    if (v108 != 0) {
        goto lab_0x3c50_2;
    }
    goto lab_0x3939;
  lab_0x3aa9:;
    int64_t v260 = v210 % 2; // 0x3ab3
    int64_t v258 = v218; // 0x3ab3
    int64_t v255 = v208; // 0x3ab3
    int64_t v259 = v210; // 0x3ab3
    int64_t v253 = v212; // 0x3ab3
    int64_t v251 = v214; // 0x3ab3
    int64_t v249 = v216; // 0x3ab3
    goto lab_0x4358;
  lab_0x43e0:;
    int64_t v261 = 125; // 0x43e9
    int64_t v262 = v90; // 0x43e9
    int64_t v263 = v31; // 0x43e9
    int64_t v264 = v49; // 0x43e9
    int64_t v265 = v68; // 0x43e9
    int64_t v266 = 125; // 0x43e9
    int64_t v267 = v90; // 0x43e9
    int64_t v268 = v31; // 0x43e9
    int64_t v269 = v49; // 0x43e9
    int64_t v270 = v68; // 0x43e9
    if (v68 != -1) {
        goto lab_0x4260;
    } else {
        goto lab_0x43ef;
    }
  lab_0x3f79:;
    int64_t v342 = v42;
    int64_t v343 = v24;
    int64_t v344 = v86;
    ps = 0;
    int64_t v345 = v344; // 0x3f96
    int64_t v346 = v343; // 0x3f96
    int64_t v347 = v342; // 0x3f96
    int64_t len3 = v60; // 0x3f96
    if (v60 == -1) {
        // 0x3f98
        v345 = v344 % 256;
        v346 = 0x100000000000000 * v343 >> 56;
        v347 = v342 % 256;
        len3 = strlen(str2);
    }
    // 0x3fcf
    v158 = len3;
    v154 = v346;
    v152 = v345 % 256;
    v156 = v347 % 256;
    v160 = 0x100000000 * v73 >> 32;
    v150 = v102 % 256;
    v188 = 1;
    v189 = 0;
    while (true) {
      lab_0x401a:
        // 0x401a
        v163 = v189;
        v185 = v188;
        v164 = v163 + v94;
        int64_t n2 = v158 - v164; // 0x4035
        v180 = v164 + a8;
        char * wstr = (char *)v180; // 0x4042
        v178 = mbrtowc(&pwc, wstr, (int32_t)n2, (struct _TYPEDEF___mbstate_t *)&ps);
        if (v178 < 0xfffffffe || n2 == 0) {
            // 0x45c0
            v190 = v185;
            v191 = v163;
            if (v178 == 0) {
                // break -> 0x40c2
                break;
            }
            // 0x45c9
            v148 = 1;
            v162 = v163;
            if (v178 == -1) {
                goto lab_0x4105;
            }
            if (v178 == -2) {
                goto lab_0x47f4;
            }
            goto lab_0x407e;
        } else {
            if ((char)v178 == 0) {
                int32_t v192 = (int32_t)*wstr; // 0x476b
                pwc = v192;
                wc = v192;
                v183 = 1;
                goto lab_0x4097;
            } else {
                // 0x406a
                switch (v178) {
                    case -1: {
                        goto lab_0x4105;
                    }
                    case -2: {
                        goto lab_0x47f4;
                    }
                    default: {
                        goto lab_0x407e;
                    }
                }
            }
        }
    }
  lab_0x40c2:
    // 0x40c2
    v148 = v190 % 2 ^ 1;
    v162 = v191;
    goto lab_0x4105;
  lab_0x3a20:;
    char v348 = *(char *)((2 * v100 & 510 | 1) + (int64_t)*__ctype_b_loc()); // 0x3a5d
    v149 = (v348 & 64) == 0;
    v151 = v100;
    v153 = v83 % 256;
    v155 = 0x100000000000000 * v19 >> 56;
    v157 = v38 % 256;
    v159 = v55;
    v161 = v73;
    goto lab_0x3a6d;
  lab_0x3939:;
    int64_t v243 = v242;
    uint64_t v244 = v238;
    int64_t v245 = v239; // 0x3941
    int64_t v246 = v243; // 0x3941
    if (((v239 ^ 1) & (int64_t)v237) != 0) {
        if (v244 > v243) {
            // 0x3948
            *(char *)(v243 + v3) = 39;
        }
        if (v244 > v243 + 1) {
            // 0x3956
            *(char *)(v243 + v9) = 36;
        }
        if (v244 > v243 + 2) {
            // 0x3965
            *(char *)(v243 + v3 + 2) = 39;
        }
        // 0x396b
        v245 = 1;
        v246 = v243 + 3;
    }
    uint64_t v247 = v246;
    if (v247 < v244) {
        // 0x3977
        *(char *)(v247 + v3) = 92;
    }
    // 0x397c
    v173 = v236;
    v174 = v94 + 1;
    v172 = v244;
    v175 = v245;
    v176 = v240;
    v177 = v241;
    v170 = v247 + 1;
    goto lab_0x3984;
  lab_0x4358:;
    int64_t v248 = v249;
    int64_t v250 = v251;
    int64_t v252 = v253;
    int64_t v254 = v255;
    int64_t v256 = v94 + 1;
    int64_t v257 = v258;
    v173 = v257;
    v174 = v256;
    v172 = v254;
    v175 = v259;
    v176 = v252;
    v177 = v250;
    v170 = v248;
    if ((char)v260 != 0) {
        if (v254 > v248) {
            // 0x4365
            *(char *)(v248 + v3) = 39;
        }
        if (v254 > v248 + 1) {
            // 0x4373
            *(char *)(v248 + v9) = 39;
        }
        // 0x4379
        v173 = v257;
        v174 = v256;
        v172 = v254;
        v175 = 0;
        v176 = v252;
        v177 = v250;
        v170 = v248 + 2;
    }
    goto lab_0x3984;
  lab_0x4260:
    // 0x4260
    v104 = v261;
    v85 = v262;
    v22 = v263;
    v41 = v264;
    v59 = 1;
    v106 = v261;
    v88 = v262;
    v26 = v263;
    v44 = v264;
    v63 = v265;
    if (v265 == 1) {
        goto lab_0x3da0;
    } else {
        goto lab_0x4270;
    }
  lab_0x43ef:
    // 0x43ef
    v104 = v266;
    v85 = v267;
    v22 = v268;
    v41 = v269;
    v59 = v270;
    v106 = v266;
    v88 = v267;
    v26 = v268;
    v44 = v269;
    v63 = v270;
    if (*(char *)(a8 + 1) != 0) {
        goto lab_0x4270;
    } else {
        goto lab_0x3da0;
    }
  lab_0x3a78:;
    bool v271 = v16 == 2; // 0x3a7c
    int64_t v272 = v101; // 0x3a7c
    int64_t v273 = v84; // 0x3a7c
    int64_t v274 = v20; // 0x3a7c
    int64_t v275 = v39; // 0x3a7c
    int64_t v276 = v56; // 0x3a7c
    int64_t v277 = v75; // 0x3a7c
    goto lab_0x3a7f;
  lab_0x3a6d:
    // 0x3a6d
    if ((char)v149 != 0) {
        goto lab_0x410f;
    } else {
        // 0x3a6d
        v16 = v161;
        v101 = v151;
        v84 = v153;
        v20 = v155;
        v39 = v157;
        v56 = v159;
        v75 = v161;
        goto lab_0x3a78;
    }
  lab_0x424c:
    // 0x424c
    v261 = v105;
    v262 = v87;
    v263 = v25;
    v264 = v43;
    v265 = v61;
    v266 = v105;
    v267 = v87;
    v268 = v25;
    v269 = v43;
    v270 = -1;
    if (v61 == -1) {
        goto lab_0x43ef;
    } else {
        goto lab_0x4260;
    }
  lab_0x3da0:;
    int64_t v337 = v59;
    int64_t v338 = v41;
    int64_t v339 = v22;
    int64_t v340 = v85;
    int64_t v341 = v104;
    int64_t v325 = v340 & 0xffffffff; // 0x3da6
    int64_t v324 = v341; // 0x3da6
    int64_t v326 = v339; // 0x3da6
    int64_t v327 = v338; // 0x3da6
    int64_t v328 = v337; // 0x3da6
    if (v94 != 0) {
        goto lab_0x43a8;
    } else {
        // 0x3dac
        v98 = v341 & 0xffffffff;
        v92 = v340;
        v34 = v339;
        v36 = v338;
        v71 = v337;
        goto lab_0x39b7;
    }
  lab_0x4270:
    // 0x4270
    v193 = v106;
    v194 = v112 == 2;
    v195 = v88;
    v196 = v26;
    v197 = v44;
    v198 = v63;
    v199 = v73;
    v200 = v80;
    goto lab_0x3a81;
  lab_0x3a7f:
    // 0x3a7f
    v193 = v272 & 0xffffffff;
    v194 = v271;
    v195 = v273;
    v196 = v274;
    v197 = v275;
    v198 = v276;
    v199 = v277;
    v200 = v80;
    goto lab_0x3a81;
  lab_0x39b7:
    // 0x39b7
    v271 = v112 == 2;
    v272 = v98;
    v273 = v92;
    v274 = v34;
    v275 = v36;
    v276 = v71;
    v277 = v73;
    v58 = v34;
    v77 = v71;
    if (v108 != 0 && v112 == 2) {
        // break -> 0x3c88
        goto lab_0x3c88_2;
    }
    goto lab_0x3a7f;
  lab_0x410f:;
    // 0x410f
    uint64_t v278; // 0x36e9
    int64_t v279; // 0x36e9
    int64_t v280; // 0x36e9
    int64_t v281; // 0x36e9
    int64_t v282; // 0x36e9
    uint64_t v283; // 0x36e9
    int64_t v284; // 0x41ee
    while (true) {
        // 0x41e1
        int64_t v285; // 0x36e9
        int64_t v286 = v285;
        int64_t v287; // 0x36e9
        v279 = v287;
        int64_t v288; // 0x36e9
        int64_t v289 = v288;
        int64_t v290; // 0x36e9
        int64_t v291 = v290;
        int64_t v292; // 0x36e9
        int64_t v293 = v292;
        int64_t v294; // 0x36e9
        v283 = v294;
        int64_t v295; // 0x36e9
        int64_t v296; // 0x36e9
        int64_t v297; // 0x36e9
        int64_t v298; // 0x36e9
        int64_t v299; // 0x36e9
        int64_t v300; // 0x36e9
        int64_t v301; // 0x36e9
        int64_t v302; // 0x36e9
        uint64_t v303; // 0x4123
        if ((char)v300 != 0) {
            // 0x4130
            int64_t v304; // 0x36e9
            int64_t v305 = v293 & -256 | v304; // 0x4134
            if (v108 != 0) {
                // 0x39e9
                v58 = v278;
                v77 = v280;
                if ((int32_t)v281 == 2) {
                    goto lab_0x3c88_2;
                } else {
                    // 0x39f1
                    result = v305 & 0xffffff01;
                    goto lab_0x39f1_2;
                }
            }
            uint64_t v306 = (v279 & 0xffffff01 ^ 1) & v305;
            int64_t v307 = v279; // 0x414c
            int64_t v308 = v286; // 0x414c
            if ((char)v306 != 0) {
                if (v278 > v286) {
                    // 0x4153
                    *(char *)(v286 + v302) = 39;
                }
                if (v278 > v286 + 1) {
                    // 0x4161
                    *(char *)(v286 + v9) = 36;
                }
                if (v278 > v286 + 2) {
                    // 0x4170
                    *(char *)(v286 + v302 + 2) = 39;
                }
                // 0x4176
                v307 = v306 % 2;
                v308 = v286 + 3;
            }
            uint64_t v309 = v308;
            int64_t v310 = v307;
            if (v278 > v309) {
                // 0x4182
                *(char *)(v309 + v302) = 92;
            }
            if (v278 > v309 + 1) {
                // 0x4190
                *(char *)(v309 + v9) = (char)(v283 / 64) % 4 | 48;
            }
            if (v278 > v309 + 2) {
                // 0x41a6
                int64_t v311; // 0x36e9
                *(char *)(v309 + v311) = (char)(v283 / 8) % 8 | 48;
            }
            int64_t v312 = v289 + 1; // 0x41b9
            int64_t v313 = v309 + 3; // 0x41bd
            int64_t v314 = v283 % 8 | 48; // 0x41c1
            v173 = v314;
            v174 = v312;
            v172 = v278;
            v175 = v310;
            v176 = v280;
            v177 = v281;
            v170 = v313;
            v299 = v314;
            v301 = v300;
            v297 = v291;
            v298 = v312;
            v295 = v310;
            v296 = v313;
            if (v303 <= v312) {
                goto lab_0x3984;
            }
        } else {
            int64_t v315 = v286; // 0x41f4
            if ((char)v291 != 0) {
                if (v278 > v286) {
                    // 0x41fb
                    *(char *)(v286 + v302) = 92;
                }
                // 0x4200
                v315 = v286 + 1;
            }
            // 0x4204
            v284 = v279 & (v293 ^ 1);
            v282 = v315;
            int64_t v316 = v289 + 1; // 0x4204
            if (v303 <= v316) {
                // break -> 0x4736
                break;
            }
            // 0x4211
            v299 = v283;
            v301 = v293;
            v297 = 0;
            v298 = v316;
            v295 = v279;
            v296 = v282;
            if ((char)v284 != 0) {
                if (v278 > v282) {
                    // 0x421e
                    *(char *)(v282 + v302) = 39;
                }
                if (v278 > v282 + 1) {
                    // 0x422c
                    *(char *)(v282 + v9) = 39;
                }
                // 0x4232
                v299 = v283;
                v301 = v293;
                v297 = 0;
                v298 = v316;
                v295 = 0;
                v296 = v282 + 2;
            }
        }
        uint64_t v317 = v296;
        int64_t v318 = v295;
        int64_t v319 = v298;
        int64_t v320 = v297;
        int64_t v321 = v301;
        if (v278 > v317) {
            int64_t v322 = v299;
            *(char *)(v317 + v302) = (char)v322;
        }
        unsigned char v323 = *(char *)(v319 + a8); // 0x41d8
        v294 = v323;
        v292 = v321;
        v290 = v320;
        v288 = v319;
        v287 = v318;
        v285 = v317 + 1;
    }
    // 0x4736
    v260 = v284;
    v258 = v283 & 0xffffffff;
    v255 = v278;
    v259 = v279;
    v253 = v280;
    v251 = v281;
    v249 = v282;
    goto lab_0x4358;
  lab_0x43a8:
    // 0x43a8
    v193 = v324;
    v194 = v112 == 2;
    v195 = v325 & 0xffffffff;
    v196 = v326;
    v197 = v327;
    v198 = v328;
    v199 = v73;
    v200 = v80;
    goto lab_0x3a81;
  lab_0x439a:;
    int64_t v329 = v67;
    int64_t v330 = v48;
    int64_t v331 = v30;
    int64_t v332 = v95;
    v325 = v332;
    v324 = 126;
    v326 = v331;
    v327 = v330;
    v328 = v329;
    if (v94 == 0) {
        // 0x439a
        v17 = v112 == 2;
        v96 = v332;
        v32 = v331;
        v50 = v330;
        v69 = v329;
        v78 = v80;
        goto lab_0x4abc;
    } else {
        goto lab_0x43a8;
    }
  lab_0x4322:;
    int64_t v333 = v65;
    int64_t v334 = v46;
    int64_t v335 = v28;
    v99 = v97;
    v82 = v89;
    v35 = v335;
    v37 = v334;
    v54 = v333;
    if (v97 != 92) {
        goto lab_0x3a0b;
    } else {
        // 0x432b
        v103 = 92;
        v21 = v335;
        v40 = v334;
        v57 = v333;
        v29 = v335;
        v47 = v334;
        v66 = v333;
        if (v18) {
            goto lab_0x3c33;
        } else {
            goto lab_0x4347;
        }
    }
  lab_0x4347:
    // 0x4347
    v260 = v47;
    v258 = 92;
    v255 = v29;
    v259 = v47;
    v253 = v66;
    v251 = v73;
    v249 = v80;
    goto lab_0x4358;
  lab_0x3c33:
    // 0x3c33
    v236 = v103;
    v237 = v112 == 2;
    v238 = v21;
    v239 = v40;
    v240 = v57;
    v241 = v73;
    v242 = v80;
    v147 = v112 == 2;
    v145 = v21;
    v146 = v57;
    if (v108 != 0) {
        goto lab_0x3c50_2;
    }
    goto lab_0x3939;
  lab_0x3c88_2:;
    int32_t v336 = __ctype_get_mb_cur_max(); // 0x3c70
    if (v58 != 0) {
        // 0x4509
        *(char *)v3 = 39;
    }
    // 0x37a1
    v10 = 0;
    v11 = (int64_t)"'";
    v12 = 1;
    v13 = 0;
    v109 = v336;
    v14 = 2;
    v53 = v58;
    v76 = v77;
    v15 = 1;
    goto lab_0x37a1;
}

// Address range: 0x4ae0 - 0x4c77
int64_t function_4ae0(int64_t a1, int64_t * a2) {
    int32_t * v1 = __errno_location(); // 0x4af4
    int32_t v2 = g16; // 0x4af9
    int64_t v3 = (int64_t)g20; // 0x4b00
    uint32_t v4 = *v1; // 0x4b0a
    int64_t set_mem = v4; // 0x4b13
    int64_t v5 = v3; // 0x4b13
    if (v2 >= 0 != v2 != 0) {
        int64_t v6; // 0x4ae0
        if (g20 == (int64_t *)&g19) {
            int64_t * mem = malloc(16); // 0x4c4d
            if (mem == NULL) {
                // 0x4c72
                function_2cd0(16);
                // UNREACHABLE
            }
            int64_t v7 = (int64_t)mem; // 0x4c4d
            int128_t v8 = __asm_movdqa(g19); // 0x4c5a
            *(int64_t *)&g20 = v7;
            __asm_movups(*(int128_t *)mem, v8);
            v6 = v7;
        } else {
            int64_t * mem2 = realloc(g20, 16); // 0x4b2d
            if (mem2 == NULL) {
                // 0x4c72
                function_2cd0(v3);
                // UNREACHABLE
            }
            int64_t v9 = (int64_t)mem2; // 0x4b2d
            *(int64_t *)&g20 = v9;
            v6 = v9;
        }
        // 0x4b45
        v5 = v6;
        int64_t v10 = 0x100000000 * (int64_t)v2;
        g16 = 1;
        set_mem = (int64_t)memset((int64_t *)(v5 + (v10 >> 28)), 0, (int32_t)((0x100000000 - v10) / 0x10000000));
    }
    int64_t * v11 = (int64_t *)v5; // 0x4b75
    int64_t * v12 = (int64_t *)(v5 + 8); // 0x4b80
    int64_t result = *v12; // 0x4b80
    if (*v11 > set_mem) {
        // 0x4c2b
        *v1 = v4;
        return result;
    }
    int64_t size = set_mem + 1; // 0x4bb1
    *v11 = size;
    if (result != (int64_t)&g22) {
        // 0x4bca
        free((int64_t *)result);
    }
    int64_t * mem3 = malloc((int32_t)size); // 0x4bf3
    if (size != 0 == mem3 == NULL) {
        // 0x4c72
        function_2cd0(size);
        // UNREACHABLE
    }
    int64_t result2 = (int64_t)mem3; // 0x4bf3
    *v12 = result2;
    // 0x4c2b
    *v1 = v4;
    return result2;
}

// Address range: 0x4c80 - 0x4cf9
int64_t function_4c80(void) {
    // 0x4c80
    int64_t v1; // 0x4c80
    if ((int32_t)function_2e00(*(int64_t *)*(int64_t *)0x7fb0, v1) != 0) {
        // 0x4c99
        error(0, *__errno_location(), "%s", dcgettext(NULL, "write error", 5));
        _exit(g17);
        // UNREACHABLE
    }
    int64_t result = function_2e00(*(int64_t *)*(int64_t *)0x7ff0, v1); // 0x4ce2
    if ((int32_t)result == 0) {
        // 0x4ceb
        return result;
    }
    // 0x4cee
    _exit(g17);
    // UNREACHABLE
}

// Address range: 0x4d00 - 0x4d12
int64_t function_4d00(int64_t a1, int64_t a2) {
    // 0x4d00
    return __cxa_atexit((void (*)(int64_t *))a1, NULL, (int64_t *)g15);
}

// Address range: 0x4d14 - 0x4d21
int64_t function_4d14(void) {
    // 0x4d14
    int64_t result; // 0x4d14
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.7.0)
// Detected functions: 63

